#!/usr/bin/env bash
# this finds the largest swap partition and *offers* to replace important instances of the backed up source with the uuid
set -euC -o pipefail
# Source utils
SOURCE_DIR="${CHEZMOI_SOURCE_DIR:-"$(chezmoi source-path)"}"
# shellcheck source=../.utils.sh
. "$SOURCE_DIR/.chezmoiscripts/.utils.sh"

GRUB_RESUME_FILE=/etc/default/grub.d/resume.cfg
# Empty if initramfs-tools is not installed
INITRAMFS_RESUME_FILE=/etc/initramfs-tools/conf.d/resume

if ! [ -d "$(dirname -- "$INITRAMFS_RESUME_FILE")" ]; then INITRAMFS_RESUME_FILE=''; fi

BIG_SWAP_LINE=$(tail -n+2 /proc/swaps | grep -v '^/dev/zram' | LC_ALL=C sort -t$'\t' -nk3 | tail -n1) || true
if [ -z "$BIG_SWAP_LINE" ]; then abort 'No swap partitions could be found' 0; fi
BIG_SWAP_PATH=$(awk '{print $1}' <<<"$BIG_SWAP_LINE") # /dev/sda1
BIG_SWAP_TYPE=$(awk '{print $2}' <<<"$BIG_SWAP_LINE") # file | partition

if [ "$BIG_SWAP_TYPE" = "file" ]; then abort0 "Swap files are not supported by this script. Please use a swap partition or setup youself :)"; fi

WARNING=""
if [ -f "$INITRAMFS_RESUME_FILE" ]; then
  WARNING="WARNING: This will overwrite '$INITRAMFS_RESUME_FILE'"
fi
if [ -f "$GRUB_RESUME_FILE" ]; then
  if [ -z "$WARNING" ]; then
    WARNING="WARNING: This will overwrite '$GRUB_RESUME_FILE'"
  else
    WARNING="$WARNING and '$GRUB_RESUME_FILE'"
  fi
fi

BIG_SWAP_LABEL=$(sudo blkid -s LABEL -o value "$BIG_SWAP_PATH" 2>/dev/null || printf '')
# fallback to parition label
[ -z "$BIG_SWAP_LABEL" ] && BIG_SWAP_LABEL="$(sudo blkid -o value -s PARTLABEL "$BIG_SWAP_PATH" 2>/dev/null || printf '')"
[ -z "$BIG_SWAP_LABEL" ] && BIG_SWAP_LABEL="No Label"

BIG_SWAP_UUID="$(sudo blkid -o value -s UUID "$BIG_SWAP_PATH")"

if [ -z "$BIG_SWAP_UUID" ]; then
  abort "failed to get UUID for $BIG_SWAP_PATH" 1
fi

use=1
confirm "Would you like to use $BIG_SWAP_PATH ($BIG_SWAP_LABEL) as your swap to resume from? $WARNING" || use=0
if [ "$use" -eq 0 ]; then
  if confirm "Would you like to disable resuming from swap? $WARNING"; then
    BIG_SWAP_UUID=none # This should disable resuming from swap
  else
    abort 'Aborting!' 0
  fi
fi

# Setup initramfs resume file
if [ -n "$INITRAMFS_RESUME_FILE" ]; then
  cat <<EOF | sudo tee "$INITRAMFS_RESUME_FILE" >/dev/null
# THIS FILE IS AUTOGENERATED. Edits will likely be lost.
RESUME=UUID=$BIG_SWAP_UUID
EOF
fi

# Setup grub config file
cat <<EOF | sudo tee "$GRUB_RESUME_FILE" >/dev/null
#!/usr/bin/env sh
# THIS FILE IS AUTOGENERATED. Edits will likely be lost.
# MAKE SURE this matches your swap partition's UUID
GRUB_CMDLINE_LINUX_DEFAULT="\$GRUB_CMDLINE_LINUX_DEFAULT resume=UUID='$BIG_SWAP_UUID'"
EOF

success
log "Run these commands to use the changes:" "'update-initramfs -u -k all'" "'update-grub'" "Press enter to continue."
# Make sure the user reads this!
read -r || true
