#! /usr/bin/env bash

# ~/.bashrc.d/01_overrides
# 
# Overrides to certain system defaults,
# such as the less history file location,
# 
# May also be a good place for init scripts
# If required by other files
#

# Stop less from saving it's history
export LESSHISTFILE=-
# Move gnupg home out of my $HOME
export GNUPGHOME=${XDG_CONFIG_HOME}/gnupg


# Ensure blank prompt command for later commands
PROMPT_COMMAND=''
