#! /usr/bin/env bash

# ~/.bashrc.d/02_path
#
# Includes changes to the path variable
# May include certain paths necessary for
# programs that install in unusual locations
#

# fix java path to allow running
PATH=$PATH:/usr/lib/jvm/jdk-19.0.2/bin

# allow pnpm bin
export PNPM_HOME="/home/aaron/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

