#! /usr/bin/env bash

# ~/.bashrc.d/02_path
#
# Includes changes to the path variable
# May include certain paths necessary for
# programs that install in unusual locations
#

# Add the bin files if not already added from the .profile
if [[ -d "$HOME/bin" ]] && [[ ! "$PATH" == *"$HOME/bin"* ]]; then
  PATH="$HOME/bin:$PATH"
fi
if [[ -d "$HOME/.local/bin" ]] && [[ ! "$PATH" == *"$HOME/.local/bin"* ]]; then
  PATH="$HOME/.local/bin:$PATH"
fi

# fix java path to allow running
export JAVA_HOME=/usr/lib/jvm/jdk-19.0.2
export PATH=$JAVA_HOME/bin:$PATH

# allow pnpm bin
export PNPM_HOME="/home/aaron/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

# include flatpaks in path. (Have org.example.app names)
export PATH=${PATH:+$PATH:}/var/lib/flatpak/exports/bin
