#!/usr/bin/env bash
# shellcheck disable=SC2034 # allow unused variables

# ~/.bashrc.d/03_secrets
#
# Stores variables and functions which contain
# secret information which should be encrypted
#

# Release-it Github Key
export RELEASE_IT_GITHUB_KEY='***REMOVED***'

