#!/usr/bin/env bash

# ~/.bashrc.d/20_alias
#
# Sets up aliases for user usage
#

# Alias sudo to call sudo with *my* $HOME/ENV
alias sudo="sudo -E"
# Unrestrict fd by default
alias fd="fd -u"
# Ask before overwriting
alias mv="mv -i"
alias cp="cp -ai"

alias backup="~/.backup/dobackup"
alias lastbackup="/usr/bin/cat ~/.backup/backup-time"
alias browser="sensible-browser"
alias fslite="browser fslite.vercel.app 2>/dev/null"
alias la="ls -A"
alias ll="ls -hl"
alias lla="ls -Ahl"
alias cl='clear'

# alias for 7z zipping files that should be hidden
alias secret-zip='7z a -r -P -mhe=on'
alias secret-unzip='7z x'

# Alias to remove error messages on opening google-chrome
# Also allows css detection of dark mode
alias google-chrome='2>/dev/null google-chrome --enable-features=WebUIDarkMode --force-dark-mode'

# Allow usage of `has` with non-defined programs
alias has='HAS_ALLOW_UNSAFE=y has'

# Replace `cat` with `bat`, if installed
if bat -V &>/dev/null; then
  alias cat='bat'
fi

# if `z` is installed, initiate it and set `cd` to `z`
if zoxide -V &>/dev/null; then
  eval "$(zoxide init bash)"
  alias cd='z'
fi

# if `bc` is installed set aliases for it
if command -v bc &>/dev/null; then
  alias bc='bc -l'
  alias calc='bc -l'
fi
