#!/usr/bin/env bash

# ~/.bashrc.d/40-fzf
#
# Sets up fzf bindings and customization
#
#

# Ensure fzf is installed, and key-bindings are reachable
if ! command -v fzf &>/dev/null || ! [ -r /usr/share/doc/fzf/examples/key-bindings.bash ]; then
  return
fi

# Add fzf key bindings
source /usr/share/doc/fzf/examples/key-bindings.bash

# Advanced customization of fzf options via _fzf_comprun function
# - The first argument to the function is the name of the command.
# - You should make sure to pass the rest of the arguments to fzf.
_fzf_comprun() {
  local command=$1
  shift

  case "$command" in
  cd) fzf --preview 'tree -C {} | head -200' "$@" ;;
  export | unset) fzf --preview "eval 'echo \$'{}" "$@" ;;
  ssh) fzf --preview 'dig {}' "$@" ;;
  *) fzf --preview 'bat -n --color=always {}' "$@" ;;
  esac
}

export _fzf_comprun
