#! /usr/bin/env bash

# ~/.bashrc.d/80_config-sync
#
# Updates config files with `chezmoi re-add`
# on login to first shlvl
#
#

# Only runs on first shell level if chezmoi is installed
if command -v chezmoi &>/dev/null; then
  vim(){
    if chezmoi source-path "$@"; then
        chezmoi edit -a -- "$@"
    else "$(which vim)" "$@"
    fi
  }
fi
