#! /usr/bin/env bash

# ~/.bashrc.d/80_chezmoi-functions
#
# Creates vim function to open chezmoi edit if possible
# also creates editor function to call the vim()
#
#

# Only runs on first shell level if chezmoi is installed
if command -v chezmoi &>/dev/null; then
  vim(){
    if chezmoi source-path "$@"; then
        chezmoi edit -a -- "$@"
    else "$(which vim)" "$@"
    fi
  }
  editor(){ vim "$@"; }
  export -f vim editor
fi
