#! /usr/bin/env bash

# ~/.bashrc.d/80_config-chezmoi
#
# Updates config files with `chezmoi re-add`
# on login to first shlvl
# Created vim function to open chezmoi edit if possible,
# else vim 
#

# Only runs on first shell level if chezmoi is installed
if command -v chezmoi &>/dev/null; then
  if [[ $SHLVL -eq 1 ]]; then
      chezmoi re-add >/dev/null
  fi
  vim(){
    if chezmoi source-path "$1"; then
        chezmoi edit "$1"
    else "$(which vim)" "$1"
    fi
  }
  export -f vim
fi
