#! /usr/bin/env bash

# ~/.bashrc.d/01_overrides
#
# Overrides to certain system defaults,
# such as the less history file location,
#
# May also be a good place for init scripts
# If required by other files
#
case " ${!PROMPT_COMMAND*} " in
# PROMPT_COMMAND is defined
*" PROMPT_COMMAND "*) : ;;
# PROMPT_COMMAND is not defined
*)
  # Define it *as an array*
  declare -ax PROMPT_COMMAND
  ;;
esac

# Rm the stupid files in HOME from chrome
rm -rf ~/.pki ~/.dotnet/ 2>/dev/null
# RM the firefox files
rm -rf ~/.mozilla 2>/dev/null
# RM the hplip files
rm -rf ~/.hplip 2>/dev/null
