#! /usr/bin/env bash

# ~/.bashrc.d/01_overrides
#
# Overrides to certain system defaults,
# such as the less history file location,
#
# May also be a good place for init scripts
# If required by other files
#
case " ${!PROMPT_COMMAND*} " in
# PROMPT_COMMAND is defined
*" PROMPT_COMMAND "*) : ;;
# PROMPT_COMMAND is not defined
*)
  # Define it *as an array*
  declare -ax PROMPT_COMMAND
  ;;
esac

# RM the stupid files in HOME from chrome
rm -rf ~/.pki ~/.dotnet/ 2>/dev/null
# RM the firefox files - I don't even care.
rm -rf ~/.mozilla 2>/dev/null
# RM the hplip files - This is just configuration
rm -rf ~/.hplip 2>/dev/null
# RM the dbus files - This is fine.
rm -rf ~/.dbus 2>/dev/null
# RM the java files - should be in ~/.config/java/
rm -rf ~/.java 2>/dev/null
# RM the snap warnings file
rm -rf ~/.snap/warnings.json 2>/dev/null
rmdir ~/.snap 2>/dev/null
rmdir ~/.sane/xsane/ 2>/dev/null
rmdir ~/.sane/ 2>/dev/null
