#! /usr/bin/env bash

# ~/.bashrc.d/02_path
#
# Includes changes to the path variable
# May include certain paths necessary for
# programs that install in unusual locations
#
function path_contains() { [[ ":$PATH:" = *":${1:-}:"* ]]; }
function append_path() { local p="${1:-}" && ! path_contains "$p" && PATH="${PATH:+$PATH:}$p"; }
function prepend_path() { local p="${1:-}" && ! path_contains "$p" && PATH="$p${PATH:+:$PATH}"; }

# Add the bin files if not already added from the .profile
prepend_path "$HOME/bin"
prepend_path "$HOME/.local/bin"

if [ -d /usr/lib/jvm ]; then
  # set JAVA_HOME to latest jvm available
  # use sort -V to sort versions. only available in core-utils-7
  # Remove trailing NULL byte with tr -d to avoid bash warning
  JAVA_HOME="$(find /usr/lib/jvm -maxdepth 1 -type d -print0 | sort -zV | tail -zn1 | tr -d '\0')"
  export JAVA_HOME
  # removed because should be linked to /usr/bin/*
  # prepend_path "$JAVA_HOME/bin"
fi

# allow npm bin
# My own variable, for symetry with PNPM_HOME
NPM_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/npm/bin"
prepend_path "$NPM_HOME"

# allow pnpm bin
export PNPM_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/pnpm"
prepend_path "$PNPM_HOME"

# Cargo and rustup
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_CONFIG_HOME/cargo"
append_path "$CARGO_HOME"

# include flatpaks in path. (Have org.example.app names)
append_path "/var/lib/flatpak/exports/bin/"

# include go in path
append_path "/usr/local/go/bin"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
if command -v go &>/dev/null; then PATH="$PATH:$(go env GOPATH)/bin"; fi
