#!/usr/bin/env bash
# ~/.bashrc.d/02_tty
# Handle tty specific settings

[ "${TERM,,}" = "linux" ] || return 0
case "$(tty)" in /dev/tty*) ;; *) return 0 ;; esac

# merge config with tty-config.yml to disable nerd-fonts
export LG_CONFIG_FILE="$XDG_CONFIG_HOME/lazygit/config.yml,$XDG_CONFIG_HOME/lazygit/tty-config.yml"

if command -v setleds &>/dev/null; then
  setleds -D +num
fi
if command -v isotope.dark &>/dev/null; then
  isotope.dark
fi
if [ -f /run/motd.dynamic ]; then
  \cat /run/motd.dynamic
elif [ -f /var/run/motd.dynamic ]; then
  \cat /var/run/motd.dynamic
fi
if [ -f /etc/motd ]; then \cat /etc/motd; fi
