#!/usr/bin/env bash
# ~/.bashrc.d/02_tty
# Handle tty specific settings

if ! [ "${TERM,,}" = "linux" ]; then
  return
fi
case "$(tty)" in
/dev/tty*) ;;
*) return ;;
esac

if command -v setleds &>/dev/null; then
  setleds -D +num
fi
if command -v isotope.dark &>/dev/null; then
  isotope.dark
fi
