#!/usr/bin/env bash

# ~/.bashrc.d/05_ENV
#
# Stores environment variables which don't fit into
# other catagories
#

# Case *in*sensitive
export LESS="-I"
export CARGO_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/cargo"
