#!/usr/bin/env bash
# shellcheck disable=SC2034 # allow unused variables

# ~/.bashrc.d/10_utilVars
#
# Stores variables useful to end-user usage
# Includes token keys and common directory variables
#

# File locations
code=~/code
bash=$code/bashScripts
js=$code/js
javascript=$js
java=$code/Java
python=$code/Python
chromeext=$code/chromeExtensions
config=$code/config
backup=/media/aaron/Backup/
