#!/usr/bin/env bash
# shellcheck disable=SC2034 # allow unused variables

# ~/.bashrc.d/10_utilVars
#
# Stores variables useful to end-user usage
# Includes token keys and common directory variables
#

# File locations
code=~/code
bash=$code/bashScripts
js=$code/js
javascript=$js
java=$code/java
python=$code/Python
chromeext=$code/chromeExtensions
config=$code/config
backup=/media/$USER/Backup/

dirs=("$code" "$bash" "$js" "$javascript" "$java" "$python" "$chromeext" "$config")
for d in "${dirs[@]}"; do
  if ! [ -d "$d" ]; then
    mkdir -p -- "$d"
  fi
done
unset d dirs
