#!/usr/bin/env bash

# ~/.bashrc.d/20_alias
#
# Sets up aliases for user usage
#

# Alias sudo to call sudo with *my* $HOME/ENV
alias sudo="sudo -E"
# Unrestrict fd by default
alias fd="fd -u"
# Ask before overwriting
alias mv="mv -i"
alias cp="cp -ai"

alias backup="~/.backup/dobackup"
alias lastbackup="/usr/bin/cat ~/.backup/backup-time"
alias browser="sensible-browser"
alias fslite="browser fslite.vercel.app 2>/dev/null"
alias la="ls -A"
alias ll="ls -hl"
alias lla="ls -Ahl"
alias cl='clear'
if command -v google-chrome &>/dev/null; then
  # Alias to remove error messages on opening google-chrome
  # Also allows css detection of dark mode
  chrome='2>/dev/null google-chrome --enable-features=WebUIDarkMode --force-dark-mode'
  # shellcheck disable=SC2139 # They are intended to expand at definition
  {
    alias google-chrome="$chrome"
    alias chrome="$chrome"
  }
  unset chrome
fi
# Show battery information
alias battery='upower -i $(upower -e | grep BAT)'

if command -v 7z; then
  # alias for 7z zipping files that should be hidden
  alias secret-zip='7z a -r -P -mhe=on'
  alias secret-unzip='7z x'
fi

if comamnd -v has; then
  # Allow usage of `has` with non-defined programs
  alias has='HAS_ALLOW_UNSAFE=y has'
fi

# Replace `cat` with `bat`, if installed
if bat -V &>/dev/null; then
  alias cat='bat'
elif batcat -V &>/dev/null; then
  alias cat='batcat'
fi

# if `z` is installed, initiate it and set `cd` to `z`
if zoxide -V &>/dev/null; then
  eval "$(zoxide init bash)"
  alias cd='z'
fi

# if `bc` is installed set aliases for it
if command -v bc &>/dev/null; then
  alias bc='bc -l'
  alias calc='bc -l'
fi

# if `pnpm` is installed set alias for pnpx
if command -v pnpm &>/dev/null; then
  alias pnpx='pnpm dlx'
fi

# If tealdeer is installed set alias for tldr
if command -v tldr &>/dev/null; then
  alias tldrf='tldr --list | fzf --preview "tldr {1} --color=always" --preview-window=right,70% | xargs tldr --pager'
fi

# Shorter lazygit
if command -v lazygit &>/dev/null; then
  alias lg='lazygit'
fi

# Shorter git
if command -v git &>/dev/null; then
  alias g='git'
fi

# Allow nvchad if it's installed
if [ -d "${NVCHAD_CONFIG:-"${XDG_CONFIG_HOME:-$HOME/.config}/NvChad"}" ]; then
  alias nvchad='NVIM_APPNAME=NvChad nvim'
else
  function nvchad-install() {
    local DESTINATION="${NVCHAD_CONFIG:-"${XDG_CONFIG_HOME:-$HOME/.config}/NvChad"}"
    printf '%s\n' "Creating a treeless clone of the nvchad repository in $DESTINATION"
    git clone --filter=tree:0 "https://github.com/NvChad/NvChad" "$DESTINATION" || {
      local err=$?
      printf 'Something went wrong while cloning the nvchad repository!' >&2
      return "$err"
    }
    alias nvchad='NVIM_APPNAME=NvChad nvim'
    printf '%s\n' 'Please run "nvchad" to complete the installation'
    unset -f nvchad-install
  }
fi
# https://nvchad.com/
