#!/usr/bin/env bash

# ~/.bashrc.d/20_sudo
#
#
# Use zenity for sudo_askpass if display is set

# Allow environment
alias sudo='sudo -EA '
[ -z "${SUDO_ASKPASS:-}" ] || return # don't override existing value
if SUDO_ASKPASS=$(command -v systemd-ask-password) && [ -x "${SUDO_ASKPASS}" ]; then
  export SUDO_ASKPASS
else
  unset SUDO_ASKPASS
fi
