#!/usr/bin/env bash
if ! command -v fff &>/dev/null; then return; fi
fff() {
  command fff "$@"
  cd "$(cat "${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d")" || return
}
# Show/Hide hidden files on open.
export FFF_HIDDEN=1
# File Opener
export FFF_OPENER="xdg-open"
# File Attributes Command
export FFF_STAT_CMD="stat"
# Trash Directory
export FFF_TRASH=~/.local/share/Trash/files
if command -v trash &>/dev/null; then
  export FFF_TRASH_CMD="trash"
fi
export FFF_FAV1=~/vscode
export FFF_FAV2=~/.bashrc.d
