#!/usr/bin/env bash

# ~/.bashrc.d/42-mcfly
#
# Sets up mcfly bindings and customization
#
#

# Ensure mcfly is installed
if ! command -v mcfly &>/dev/null; then
  return
fi
export MCFLY_KEY_SCHEME=vim
export MCFLY_FUZZY=2
export MCFLY_RESULTS=50
export MCFLY_INTERFACE_VIEW=BOTTOM
export MCFLY_RESULTS_SORT=LAST_RUN
# export MCFLY_HISTORY_LIMIT=10000

# DB: ~/.local/share/mcfly/history.db
if [ -n "${HISTFILE:-}" ]; then
  eval "$(mcfly init bash)"
fi
