#!/usr/bin/env bash

# ~/.bashrc.d/45_neofetch_info
#
# Displays neofetch if shlvl = 1
# This should be before backup information
#
if [ -n "${NONEOFETCH:-}" ]; then
  unset NONEOFETCH
  return 0
fi
[ "$SHLVL" -eq 1 ] || return 0

has() { command -v "$1" >/dev/null 2>&1; }
if has fastfetch; then
  fastfetch
elif has neofetch; then
  neofetch
fi
unset -f has
