#!/usr/bin/env bash

# ~/.bashrc.d/46_file_count_home
#
# Displays count of files in home directory if shlvl = 1
# This should be after neofetch
#
[ "$SHLVL" -eq 1 ] || return 0
command -v file-count &>/dev/null || return 0

count=$(file-count "$HOME")
printf '%s\n' "$(file-count "$HOME") files found in $HOME"
