#!/usr/bin/env bash
# ~/.bashrc.d/47_todo_count
#
# Displays number of todos using the todo program
# This should be after neofetch
#

[ "$SHLVL" -eq 1 ] || return 0
printf '%s\n' "You have $(todo count) todos!" || true
