#!/usr/bin/env bash
# ~/.bashrc.d/47_todo_count
#
# Displays number of todos using the todo program
# This should be after neofetch
#

[ "$SHLVL" -eq 1 ] || return 0
command -v todo &>/dev/null || return 0

_count=$(todo count) || true
if [ "$_count" -gt 0 ]; then
  _msg="You have $_count todo"
  [ "$_count" -eq 1 ] || _msg+="s"
  _msg+="!"
  printf '%s\n' "$_msg" || true
  unset _msg
fi
unset _count
