#!/usr/bin/env bash
# ~/.bashrc.d/47_todo_count
#
# Displays number of todos using the todo program
# This should be after neofetch
#

[ "$SHLVL" -eq 1 ] || return 0
command -v todo &>/dev/null || return 0

_count=$(todo count)
if [ "$_count" -gt 0 ]; then
  printf '%s\n' "You have $_count todos!" || true
fi
unset _count
