#! /usr/bin/env bash

# ~/.bashrc.d/50_backup
#
# If on first shell,
#
# Echos an error message to the user from
# ~/.backup/BACKUPFAILURE or ~/.backup/BACKUPCHECKFAILURE
# backup scripts should create a file there if failed.
#
# Always calls cat on ~/.backup/last-backup-time to alert
# user to when the most recent successful backup was.
#

if [[ "$SHLVL" -eq 1 ]]; then

  # Echo error message if last backup failed
  if [[ -f ~/.backup/BACKUPFAILURE ]]; then
    # Set color and bold
    tput setaf 1
    tput smso
    echo "Last attempted backup failed:"
    # Reset color and bold
    tput sgr0
    # Show error message
    cat ~/.backup/BACKUPFAILURE

  # Echo error message if last backup check failed but last backup success
  elif [[ -f ~/.backup/BACKUPCHECKFAILURE ]]; then
    # Set color and bold
    tput setaf 1
    tput smso
    echo "Next backup will not be possible. Last backup was successful:"
    # Reset color and bold
    tput sgr0
    # Show error message
    cat ~/.backup/BACKUPCHECKFAILURE
  fi

  if [[ -f ~/.backup/backup-time ]]; then
    # Print new line if already printed failure message
    [[ -f ~/.backup/BACKUPFAILURE || -f ~/.backup/BACKUPCHECKFAILURE ]] && echo
    # Echo last backup time
    cat ~/.backup/backup-time
  fi

fi
