#!/usr/bin/env bash
# ~/.bashrc.d/90_arch-specific
#
# This sets up things that are specific arch linux
# Be *very* careful to make sure everything here has
# conditions and will not break on debian, ubuntu, etc
#
#

if [ -f /usr/share/doc/find-the-command/ftc.bash ]; then
  source /usr/share/doc/find-the-command/ftc.bash
fi
