#!/usr/bin/env bash
# ~/.bashrc.d/90_arch-specific
#
# This sets up things that are specific arch linux
# Be *very* careful to make sure everything here has
# conditions and will not break on debian, ubuntu, etc
#
#

cnf=(/usr/share/doc/pkgfile/command-not-found.bash /usr/share/doc/find-the-command/ftc.bash)
for file in "${cnf[@]}"; do
  [ -r "$file" ] || continue
  # shellcheck disable=SC1090
  source "$file"
  break
done
unset file cnf
