#!/usr/bin/env bash
# ~/.bashrc.d/90_command-not-found
#
# Sets up command_not_found_handle to search for commands in repo packages
#

# Attempt to setup a command_not_found_handle, first one that exists will be used
cnf=(
  /usr/share/doc/pkgfile/command-not-found.bash
  /usr/share/doc/find-the-command/ftc.bash
)
for file in "${cnf[@]}"; do
  [ -r "$file" ] || continue
  # shellcheck disable=SC1090
  source -- "$file" && break
done

# Only if a command_not_found_handle is already defined, rename it and ask before executing it
# Note that this works with pre-defined command_not_found_handles, such as on ubuntu
if declare -f command_not_found_handle &>/dev/null; then
  # Hack to rename command_not_found_handle to _command_not_found_handle
  eval "_$(declare -f command_not_found_handle)" && unset -f command_not_found_handle
  command_not_found_handle() {
    local response
    printf '%s\n' "$0: $1: command not found" >&2
    read -r -p "Search for it? [y/N] " response >&2
    case "$response" in
    [yY][eE][sS] | [yY]) ;;
    *) return 127 ;;
    esac
    _command_not_found_handle "$@"
  }
fi
unset file cnf
