#!/usr/bin/env bash

# ~/.bashrc.d/91_bashrc-tmp
#
# Loads ~/.bashrc.tmp if it exists
# This file should be used for
# temporary changes to bashrc without
# including it in version control
#
[ -f ~/.bashrc.tmp ] || return
. ~/.bashrc.tmp
