#!/usr/bin/env bash

# ~/.bashrc.d/999_remove-duplicate-path
#
# Removes duplicate paths in the PATH variable.
# This should be the last thing to modify the path
# to ensure that it's effect is not removed
#

# remove duplicated paths in PATH variable
PATH="$(printf "%s" "$PATH" | awk -v RS=':' '!a[$1]++ {if (NR > 1) printf RS; printf $1}')"

# remove tailing slashes in PATH variable
PATH="$(printf "%s" "$PATH" | sed 's,/:,:,g')"
