#!/usr/bin/env bash

# ~/.bashrc.d/999_Prompt-Exit-Code
#
# Captures the exit code of last command before PROMPT_COMMAND
# and reissues it after execution for use in other programs,
# such as PS1 display.
# MUST be the last program to modify PROMPT_COMMAND to
# function properly
#
pre='__EXIT=$?'
# shellcheck disable=SC2016 # IK expressions do not expand. that is the point.
post='(exit $__EXIT)'
# Don't do if contains already
if ! [[ "${PROMPT_COMMAND[0]}" == "$pre" ]] || ! [[ "${PROMPT_COMMAND[-1]}" == "$post" ]]; then
  # Capture exit code before prompt and reinstantiate after
  PROMPT_COMMAND=("$pre" "${PROMPT_COMMAND[@]}" "$post")
fi
unset pre post
