#!/usr/bin/env bash

# ~/.bashrc.d/999_Prompt-Exit-Code
#
# Captures the exit code of last command before PROMPT_COMMAND
# and reissues it after execution for use in other programs,
# such as PS1 display.
# MUST be the last program to modify PROMPT_COMMAND to
# function properly
#

# Ensure prompt command ends with a ;
old_prompt="${PROMPT_COMMAND:+${PROMPT_COMMAND/%;/};}"

pre='__EXIT=$?;'
# shellcheck disable=SC2016 # IK expressions do not expand. that is the point.
post='(exit $__EXIT)'
if ! [[ "${PROMPT_COMMAND:-}" == "$pre"*"$post" ]]; then
	# Capture exit code before prompt and reinstantiate after
	PROMPT_COMMAND="$pre$old_prompt$post"
fi
