##########
# Player #
##########

hr-seek-framedrop=no
no-resume-playback
border=no
msg-color=yes
msg-module=yes

###### General
keep-open=yes # Don't close the player after finishing the video
autofit=85%x85% # Start mpv with a % smaller resolution of your screen
cursor-autohide=100 # Cursor hide in ms

###############
# Screenshots #
###############

screenshot-directory="~/Pictures/Screenshots/"
screenshot-template="mpv-%F-%P%#n"
screenshot-format=png # Set screenshot format
screenshot-png-compression=4 # Range is 0 to 10. 0 being no compression.
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes # Same output bitdepth as the video

#########
# Audio #
#########

volume-max=200                          # maximum volume in %, everything above 100 results in amplification
audio-file-auto=fuzzy                   # external audio doesn't has to match the file name exactly to autoload
audio-pitch-correction=yes              # automatically insert scaletempo when playing with higher speed

##################
# Video Profiles #
##################

profile=high-quality
vo=gpu-next # GPU-Next: https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU
hwdec=vaapi # Don't try to load cuda

###### Dither
dither-depth=auto

###### Debanding
deband=yes
deband-iterations=4
deband-threshold=35
deband-range=16
deband-grain=4

# ###### HDR
target-colorspace-hint=yes

############
# Playback #
############

deinterlace=no # global reset of deinterlacing to off

[default]
# apply all luma and chroma upscaling and downscaling settings
# apply motion interpolation

############################
# Protocol Specific Config #
############################

[protocol.http]
hls-bitrate=max # use max quality for HLS streams
cache=yes
no-cache-pause # don't pause when the cache runs low

[protocol.https]
profile=protocol.http

[protocol.ytdl]
profile=protocol.http
