#!/usr/bin/env sh
file=
if [ -f /opt/bfg-1.14.0.jar ]; then # Check for current version as of writing
  file=/opt/bfg-1.14.0.jar
elif [ -f /opt/bfg.jar ]; then # Check for no version
  file=/opt/bfg.jar
else
  for f in /opt/bfg*.jar; do # try to find one. No order is guarenteed.
    if [ -f "$f" ]; then
      file="$f"
      break
    fi
  done
fi
if [ -z "$file" ] || ! [ -f "$file" ]; then
  echo "Could not find bfg in /opt" >&2
  exit 1
fi
echo "Launching bfg at $file"
exec java -jar "$file" "$@"
