#!/usr/bin/env bash

# ~/.bashrc.d/20_alias
#
# Sets up fp function for fuzzy finding files, and
# fpd function to fuzzy find directories. Each command displays a
# preview through bat/cat and tree/ls respectively.
#
# Also sets default fzf command for direct invocations
#
# By default is colorized, but can be disabled by unsetting FZF_USE_COLOR
# Important: Also unset FZF_DEFAULT_OPTS to accelerate scanning!
#

# only do these if fzf exists
if ! command -v fzf &>/dev/null; then
  return
fi
# Allow color, slows down scanning!
export FZF_USE_COLOR=true
export FZF_DEFAULT_OPTS='--ansi'

# Use better find if installed
if command -v fd &>/dev/null; then
  # Echo if FZF_USE_COLOR is set
  export FZF_BASE_COMMAND='fd "$(test "$FZF_USE_COLOR" && echo --color=always)" --follow --hidden --exclude .git'
  export FZF_FIND_DIR="$FZF_BASE_COMMAND --type d . {}"
  export FZF_FIND_FILE="$FZF_BASE_COMMAND --type f . {}"
else
  export FZF_BASE_COMMAND='find'
  export FZF_FIND_DIR="$FZF_BASE_COMMAND {} --type d"
  export FZF_FIND_FILE="$FZF_BASE_COMMAND {} --type f"
fi

# Use better cat if installed
if command -v bat &>/dev/null; then
  export FZF_BAT_CMD='bat --style=numbers "$(test "$FZF_USE_COLOR" && echo --color=always)"'
  export FZF_BAT_CMD_JSON="$FZF_BAT_CMD --language JSON"
else
  export FZF_BAT_CMD="cat"
  export FZF_BAT_CMD_JSON="$FZF_BAT_CMD"
fi

if command -v tree &>/dev/null; then
  export FZF_DIR_PREVIEW='tree -C {}'
else
  export FZF_DIR_PREVIEW='ls {}'
fi
FZF_FILE_PREVIEW () {
  local json
  # Attempt to prettify json before display
  # will return false if prettier isn't installed
  if json=$(cat "$1" | prettier --parser json5 2>/dev/null); then
    # Shows first 500 lines
    printf '%s' "$json" | $FZF_BAT_CMD_JSON
  else $FZF_BAT_CMD "$1"
  fi
}
export -f FZF_FILE_PREVIEW

export FZF_DEFAULT_COMMAND="${FZF_FIND_FILE//\{\}/.}"

fp() ( 
  local output path
  if [ "$1" = '--help' ]; then
    printf '%s\n%s'
    \  'fp [--disable-color|-C] [PATH]'
    \  ''
    \  'find files in PATH to output the user'"'"'s choice'
    \  'Opens editor if stdout is connected to a tty'
    return 0
  fi
  if [ "$1" = '--disable-color' || "$1" - '-C' ]; then
    unset FZF_USE_COLOR
    FZF_DEFAULT_OPTS=''
    shift 1
  fi
  path=${1:-.}
  # set the command to call with
  FZF_DEFAULT_COMMAND="${FZF_FIND_FILE//\{\}/$path}" 

  # Call with the path given, if applicable, and find all files
  output=$(
    fzf --preview "FZF_FILE_PREVIEW {} | head -n500" "${@:2}"
  )
  if [[ -t 1 ]]; then
    editor "$output"
  else 
    printf '%s' "$output"
  fi
)

# For finding directories
fpd() {
  local output path
  if [ "$1" = '--help' ]; then
    printf '%s\n%s'
    \  'fpd [--disable-color|-C] [PATH]'
    \  ''
    \  'find directories in PATH to output the user'"'"'s choice'
    \  'calls cd if stdout is connected to a tty'
    return 0
  fi
  if [ "$1" = '--disable-color' || "$1" - '-C' ]; then
    unset FZF_USE_COLOR
    FZF_DEFAULT_OPTS=''
    shift 1
  fi
  path=${1:-.}
  # set the command to call with
  FZF_DEFAULT_COMMAND="${FZF_FIND_DIR//\{\}/$path}" 

  # Call with the path given, if applicable, and find all directories
  output=$(
  fzf --preview "$FZF_DIR_PREVIEW | head -n200" "${@:2}"
  )
  if [[ -t 1 ]]; then
    cd "$output"
  else 
    printf '%s' "$output"
  fi
}
