#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/new
#
# Creates a function 'new' that creates a TypeScript
# project in the current directory based on the github
# repositiory found here: https://github.com/aarondill/ts-template.git
# It uses git to ensure the most up-to-date version before copying
#
# -y or --yes can be passed to avoid most of the configuration
# questions
# A name can be passed to automatically select a name for the new 
# folder. It will not overwrite an already existing folder
#

export __ts_template_folder="${XDG_CACHE_HOME:-$HOME/.cache}/ts-template"
function new() (
  export yesarg=''
  # If first arg is -y or --yes set yes arg and shift
  if [[ "$1" = '-y' || "$1" = '--yes' ]]; then
    yesarg="$1"
    shift
  else
    # Otherwise, yesarg is the second argument(even if empty)
    yesarg="$2"
  fi

  # Get foldername from user or 1st argument
  folder_path="$1"
  [[ -d "$folder_path" ]] && echo "$folder_path already exists. Please choose another"
  while [[ -z "$folder_path" || -d "$folder_path" ]]; do
    read -rep 'What to call your folder? ' -i "$folder_path" folder_path
    [[ -z "$folder_path" ]] &&
      echo 'Please input a name' && echo
    [[ -d "$folder_path" ]] &&
      echo "$folder_path already exists. Please choose another"
  done

  export foldername="$(basename -- "$folder_path")"
  # Set __ts_template_folder in cache folder
  export __ts_template_folder="${XDG_CACHE_HOME:-$HOME/.cache}/ts-template"
  __update-cached-repo

  export tempdir=$(mktemp --tmpdir -d 'ts-template.XXXXXX')
  # on exit, remove the directory if it exists
  trap "[[ -d \"$tempdir\" ]] && rm -rf \"$tempdir\" ; echo" EXIT HUP INT QUIT TERM 
  export container="$tempdir"/"$foldername"
  __create-folder-install || return

  mkdir -p "$(dirname -- "$(realpath -m -- $folder_path)")"
  mv -T "$container" "$folder_path"
)

function __create-folder-install(
  # create folder by name desired
  mkdir -p "$container"

  # copy template to destination folder
  cp -nr -T "$__ts_template_folder" "$container" || exit

  # Remove git repository from destination folder
  rm -rf "$container/.git" || true
  
  # cd to the directory in this shell, for avoiding bugs
  cd "$container" || true

  # Run init script in new folder with args given(or not)
  "$container"/init "$yesarg" || exit
)

function __update-cached-repo()(
  gitrepo=https://github.com/aarondill/ts-template.git

  # Folder doesn't exist. Try to make one, if failed exit
  if [[ ! -d "$__ts_template_folder" ]]; then
    mkdir -p "$__ts_template_folder" || exit 1
  fi
  
  # cd into the template folder (only in this function)
  cd "$__ts_template_folder" || exit 1

  # if folder isn't a git repo, init git in it.
  if [[ ! -d "$__ts_template_folder/.git" ]]; then
    git init -q
    git remote add origin "$gitrepo"
  fi

  actual_remote="$(git config --get remote.origin.url)"
  if ! [[ "$actual_remote" == "$gitrepo" ]]; then
    # Add origin; Will fail if already exists
    git remote add origin "$gitrepo" &>/dev/null
    # set url of origin
    git remote set-url origin "$gitrepo"
  fi

  # pull for latest changes
  git fetch -q -n --update-shallow --depth 1 origin main:refs/remotes/origin/main
  # git reset origin/main -q --hard
)
