#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/new-tty
#
# Creates a new disowned gnome-terminal instance then exits this one
#
function new-tty(){
  local terminal=gnome-terminal
  if command -v "$terminal" &>/dev/null;
    gnome-terminal & disown & exit
  else 
    printf "%s\n" "could not find $terminal"
  fi
}
