#! /usr/bin/env bash

# ~/.bashrc.d/30_functions/parent-cd
#
# Creates a function to pushd the parent directory of a file
# *Follows Symlinks*
#

parent-cd() {
    local path truepath
    truepath=$(realpath -e -- "$1") || return
    path="$(dirname -- "$truepath")" || return
    pushd -- "$path" || return
}
