#! /usr/bin/env bash

# ~/.bashrc.d/30_functions/parent-cd
#
# Creates a function to pushd the parent directory of a file
# *Follows Symlinks*
#

parent-cd() {
    local path truepath filein

    if [ "$1" = "--help" ]; then
        printf '%s\n\n%s\n' "parent-cd [mesasge]" "pushds to the parent of a file, calls which if file doesn't exist"
        return 0
    fi
    filein=$1
    # If not a file, try which
    if [[ ! -e "$filein" ]]; then
        filein=$(which "$filein")
    fi
    # Last chance.
    if [[ ! -e "$filein" ]]; then
        printf '%s is not a file' "$filein"
        return 1
    fi

    truepath=$(realpath -e -- "$1") || return
    path="$(dirname -- "$truepath")" || return
    pushd -- "$path" || return
}
