#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/post-temp
#
# Hosts a temporary file on the internet for 60 mins at the url.
#
#
function post-temp(){
  if ! [[ -f "$1" ]]; then
      printf "The path given is not a file"
      return 2
  fi
  local result = "$(curl -F "file=@$1" https://tmpfiles.org/api/v1/upload)"
    # Example output:
    # {"status":"success","data":{"url":"https://tmpfiles.org/######/file"}} 
  if command -v 'fx'; then 
    # Print the result thru fx to get the data
    printf '%s' "$result" | fx '.status'
    printf '%s' "$result" | fx '.data.url'
    return 0
  fi
    # If fx isn't installed, print the pure json
    printf '%s' "$result"
}

