#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/post-temp
#
# Hosts a temporary file on the internet for 60 mins and returns the url.
#
#
function post-temp(){
  if [ "$1" = "--help" ];then
    printf '%s\n' "post-temp FILE" "" "Hosts a temporary file on the internet for 60 mins and returns the url."
    return 0;
  fi
  if ! [[ -f "$1" ]]; then
      printf "The path given is not a file"
      return 2
  fi
  local result="$(curl -F "file=@$1" https://tmpfiles.org/api/v1/upload)"
    # Example outputs:
    # {"message": "server error"}
    # {"status":"success","data":{"url":"https://tmpfiles.org/######/file"}} 
  if command -v 'fx' &>/dev/null; then 
    printf '%s\n' "$result"
    # Print the result thru fx to get the data
    (
    fx '.status'  <<< "$result"
    fx '.data?.url' <<< "$result"
    ) && return 0 
    fx '.message' <<<"$result" && return 2
  fi
    # If fx isn't installed, print the pure json
    printf '%s\n' "$result"
}

