#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/private
#
# Unsets histfile and opens a shell
function private(){
  HISTFILE='' bash -i
  # If is in history
  if history | tail -n1 | grep -q 'private'; then
  history -d $HISTCMD
  fi
}
