#! /usr/bin/env bash
function update-config() (
  # Finds files line-by-line, ignoring the first 3 lines
  readarray -t files <<<"$(tail -n+4 -- ~/.bashrc.d/30_functions/_update-config)"
  if target=$(chezmoi target-path); then
    # cd to home, so files are relative to home
    builtin cd "$target" || return
    chezmoi add "${files[@]}"
    # Ensure everything is updated
    chezmoi re-add
  else
    return 2
  fi
)
export -f update-config
