#! /usr/bin/env bash

# ~/.bashrc.d/30_functions/update-config
#
# Creates an update-config function to call chezmoi add on
# every file in _update-config
# Creates a cproot function to cp a file to ~/.root/FILEPATH
# and calls chezmoi add on it.
#

function update-config() ( 
  declare -a files
  declare target
  # Finds files line-by-line, ignoring the first 3 lines
  readarray -t files <<<"$(tail -n+4 -- ~/.bashrc.d/30_functions/_update-config)"
  if target=$(chezmoi target-path); then
    # cd to home, so files are relative to home
    builtin cd "$target" || return
    printf '%s\n' "Press 'n' if asked about encrypted files. They will still be updated!"
    chezmoi add "${files[@]}"
    # Ensure everything is updated
    chezmoi re-add
  else
    return 2
  fi
)

# Copies the files to $HOME/.root/FILEPATH. `.root` should be backed up
function cproot() {
  declare -i exitCode=0
  files=()
  for file in; do
    if [[ -e "$file" ]]; then
      local old_path
      old_path="$(realpath -s -- "$file")"
      local new_path="$HOME/.root$old_path"
      # ensure destination exists
      mkdir -p "$(dirname -- "$new_path")"
      # cp to home, so files are relative to home
      /usr/bin/sudo cp -r "$file" "$new_path"
      /usr/bin/sudo chown -hR "$(whoami)" "$new_path"
      # add to the array so i can update all at once
      files+=("$new_path")
    else
      printf '%s is not a file\n' "$file"
      # Exit 1 at end if any args were invalid
      exitCode=1
    fi
  done
  # Add all files to chezmoi repo
  chezmoi add "${files[@]}"

  # Exit with the saved code
  return $exitCode
}

# Adds to chezmoi and adds to ~/.bashrc.d/30_functions/_update-config
function add-config() {
  declare -i exitCode=0
  local file
  files=()
  for file in "$@"; do
    if [[ -r "$file" ]]; then
      # add to the array so i can update all at once
      files+=("$(realpath -s -- "$file")")
    else
      printf '%s is not a file\n' "$file"
      # Exit 1 at end if any args were invalid
      exitCode=1
    fi
  done

  # Add all files to chezmoi repo
  chezmoi add "${files[@]}"
  # Add files to the _update-config file
  for file in "${files[@]}"; do
    local short_file=${file#"$HOME"/} # remove /home/user/
    # If not already in the file
    if ! grep -F -x -q "$short_file" ~/.bashrc.d/30_functions/_update-config; then
      printf '%s\n' "$short_file" >>~/.bashrc.d/30_functions/_update-config
    fi
  done

  # Exit with the saved code
  return $exitCode
}
