# Hard coded username! Set this to your github username
# {{ $username := "aarondill" }}

# Note: chromeext variable is set in ~/.bashrc.d/10_util-vars. If not defined, use code/chromeExtensions
# {{ $path := env "chromeext" | trimPrefix (print (env "HOME") "/") | default "code/chromeExtensions" }}
# {{ $repos := list "googleCopyUser" "chrome-hist" "seizureChrome" }}
# Path: {{$path}}
# Repos: {{$repos | toJson}}

# {{range $index, $repo := $repos}}
['{{$path}}/{{$repo}}']
type = 'git-repo'
url = 'https://github.com/{{$username}}/{{$repo}}.git'
clone.args = ['--filter=tree:0']
# End of {{ $repo -}} {{end}}
