[".config/awesome"]
type = "git-repo"
url = "https://github.com/aarondill/awesome.git"
refreshPeriod = "12h"
clone.args = ['--filter=tree:0']

[".config/nvim"]
type = "git-repo"
url = "https://github.com/aarondill/nvim.git"
refreshPeriod = "12h"
clone.args = ['--filter=tree:0']

[".config/wezterm"]
type = "git-repo"
url = "https://github.com/aarondill/wezterm.git"
refreshPeriod = "12h"
clone.args = ['--filter=tree:0']
