[".config/awesome"]
type = "git-repo"
url = "https://github.com/aarondill/awesome.git"
clone.args = ['--filter=tree:0']

[".config/nvim"]
type = "git-repo"
url = "https://github.com/aarondill/nvim.git"
clone.args = ['--filter=tree:0']

[".config/wezterm"]
type = "git-repo"
url = "https://github.com/aarondill/wezterm.git"
clone.args = ['--filter=tree:0']

[".config/mpv"]
type = "git-repo"
url = "https://github.com/aarondill/mpv.git"
clone.args = ['--filter=tree:0']

[".config/yazi"]
type = "git-repo"
url = "https://github.com/aarondill/yazi.git"
clone.args = ['--filter=tree:0', "--recurse-submodules", "--shallow-submodules"]
