#!/usr/bin/env bash

# Change this file to configure the script

export stdin=           # A string written to stdin
export stdin_file=      # This will override stdin. Relative to output_dir (use input_files if needed), use - to specify stdin
export cargs=()         # javac
export jargs=()         # java
export dargs=()         # javadoc
export classpath=       # output_dir will be automatically included
export output_dir=      # or "dist". Relative to this_dir
export input_files=()   # a list of files to copy (symlink) to the output_dir. Releative to this_dir
export main_class=      # the class containing the main method if different
export cleanup_files=() # A list of files to remove when cleaning up. Releative to this_dir
