#!/bin/sh
# Create a "rescue mode" grub entry that boots into a /boot/systemrescue.iso file

# Source grub library
# shellcheck source=/usr/lib/grub/grub-mkconfig_lib
. "$pkgdatadir/grub-mkconfig_lib"

set -eC # HACK: -u is disabled because the grub libraries don't expect it.

# log to stderr bc stdout is to grub
log() { printf '%s\n' "$@" >&2; }
err() { printf '%s\n' "$@" >&2; }
abort() {
  log "$1"
  exit "${2:-1}"
}

system_rescue_iso=${SYSTEM_RESCUE_ISO:-/boot/systemrescue.iso}
if ! [ -f "$system_rescue_iso" ]; then
  abort "'$system_rescue_iso' not found. Not creating rescue entry." 0
fi

mount=$("$grub_probe" --target=device "$system_rescue_iso")

CLASS="--class rescue --class gnu-linux --class gnu --class os"

log "Found rescue mode linux: $system_rescue_iso"

# DO NOT output anything to stdout BEFORE THIS!
# At any point before this cat, you should assume
# that the program can end at any time, and that
# if it does, the user's computer *will not* boot
# This is likely exaggerated, as grub would likely save it
# but that's not a risk that should be unnecessarily taken.

cat <<-EOF
menuentry "systemrescue.iso" $CLASS {
        $(prepare_grub_to_access_device "$mount")
        iso_path="$system_rescue_iso"
        export iso_path
        kernelopts="   "
        export kernelopts
        # support booting recent GRUB versions on UEFI systems
        rmmod tpm
        loopback loop "\$is_path"
        set root=(loop)
        configfile /boot/grub/loopback.cfg
}
EOF
