#!/bin/sh
# Create a "text mode" grub entry that boots to runlevel 3, instead of graphical.target

# Source grub library
# shellcheck source=/usr/lib/grub/grub-mkconfig_lib
. "$pkgdatadir/grub-mkconfig_lib"

set -eC # HACK: -u is disabled because the grub libraries don't expect it.

# log to stderr bc stdout is to grub
log() { printf '%s\n' "$@" >&2; }
err() { printf '%s\n' "$@" >&2; }
abort() {
  log "$1"
  exit "${2:-1}"
}

# taken from 10_linux
# btrfs may reside on multiple devices. We cannot pass them as value of root= parameter
# and mounting btrfs requires user space scanning, so force UUID in this case.
if
  { [ -z "$GRUB_DEVICE_UUID" ] && [ -z "$GRUB_DEVICE_PARTUUID" ]; } ||
    { [ "${GRUB_DISABLE_LINUX_UUID:-}" = "true" ] && [ "${GRUB_DISABLE_LINUX_PARTUUID:-}" = "true" ]; } ||
    { ! test -e "/dev/disk/by-uuid/$GRUB_DEVICE_UUID" && ! test -e "/dev/disk/by-partuuid/$GRUB_DEVICE_PARTUUID"; } ||
    { test -e "$GRUB_DEVICE" && uses_abstraction "$GRUB_DEVICE" lvm; }
then
  LINUX_ROOT_DEVICE=$GRUB_DEVICE
elif [ -z "$GRUB_DEVICE_UUID" ] || [ "${GRUB_DISABLE_LINUX_UUID:-}" = "true" ]; then
  LINUX_ROOT_DEVICE=PARTUUID=$GRUB_DEVICE_PARTUUID
else
  LINUX_ROOT_DEVICE=UUID=$GRUB_DEVICE_UUID
fi

log "Creating text mode linux: $LINUX_ROOT_DEVICE"

get_init_rd_path() { # {{{1
  _linux=$1
  _version="$(printf "%s" "$(basename "$linux")" | sed -e "s,^[^0-9]*-,,g")"
  _alt_version=$(echo "$_version" | sed -e "s,\.old$,,g")
  _dirname=$(dirname "$_linux")
  _rel_dirname=$(make_system_path_relative_to_its_root "$_dirname")

  case "$(uname -m)" in
  i?86) GENKERNEL_ARCH="x86" ;;
  mips | mips64) GENKERNEL_ARCH="mips" ;;
  mipsel | mips64el) GENKERNEL_ARCH="mipsel" ;;
  arm*) GENKERNEL_ARCH="arm" ;;
  *) GENKERNEL_ARCH="$(uname -m)" ;;
  esac

  initrd_early=
  for i in ${GRUB_EARLY_INITRD_LINUX_STOCK} ${GRUB_EARLY_INITRD_LINUX_CUSTOM}; do
    if test -e "${_dirname}/${i}"; then initrd_early="${initrd_early} ${i}"; fi
  done

  initrd_real=
  for i in "initrd.img-${_version}" "initrd-${_version}.img" "initrd-${_version}.gz" \
    "initrd-${_version}" "initramfs-${_version}.img" \
    "initrd.img-${_alt_version}" "initrd-${_alt_version}.img" \
    "initrd-${_alt_version}" "initramfs-${_alt_version}.img" \
    "initramfs-genkernel-${_version}" \
    "initramfs-genkernel-${_alt_version}" \
    "initramfs-genkernel-${GENKERNEL_ARCH}-${_version}" \
    "initramfs-genkernel-${GENKERNEL_ARCH}-${_alt_version}"; do
    if test -e "${_dirname}/${i}"; then
      initrd_real="${i}"
      break
    fi
  done

  initrd=
  if test -n "${initrd_early}" || test -n "${initrd_real}"; then
    initrd="${initrd_early} ${initrd_real}"

    initrd_display=
    for i in ${initrd}; do
      initrd_display="${initrd_display} ${_dirname}/${i}"
    done
    log "Found initrd image: ${initrd_display}"
  fi

  initrd_path=
  for i in ${initrd}; do
    initrd_path="${initrd_path} ${_rel_dirname}/${i}"
  done
  printf "%s" "$initrd_path"
  # }}}
}

get_linux_kernal() { # {{{1
  list=
  case "$(uname -m)" in
  i?86 | x86_64)
    for i in /boot/vmlinuz-* /vmlinuz-* /boot/kernel-*; do
      if grub_file_is_not_garbage "$i"; then list="$list $i"; fi
    done
    ;;
  *)
    for i in /boot/vmlinuz-* /boot/vmlinux-* /vmlinuz-* /vmlinux-* /boot/kernel-*; do
      if grub_file_is_not_garbage "$i"; then list="$list $i"; fi
    done
    ;;
  esac
  _linux=$(printf '%s' "$list" | tr ' ' '\n' | version_sort | tail -n1)
  if [ -z "$_linux" ]; then abort "Could not find linux image"; fi
  log "Found linux image: $_linux"
  printf '%s' "$_linux"
  # }}}
}

linux=$(get_linux_kernal)
basename=$(basename "$linux")
dirname=$(dirname "$linux")
rel_dirname=$(make_system_path_relative_to_its_root "$dirname")
initrd=$(get_init_rd_path "$linux")

# Remove splash and quiet args from GRUB_CMDLINE_LINUX_DEFAULT
GRUB_CMDLINE_ARGS=$(printf '%s' "$GRUB_CMDLINE_LINUX_DEFAULT" | sed -e 's/\bsplash\b//g' -e 's/\bquiet\b//g' -e 's/^ \+//g')

CLASS="--class gnu-linux --class gnu --class os"

OS=GNU/Linux
if [ -n "$GRUB_DISTRIBUTOR" ]; then
  case $GRUB_DISTRIBUTOR in
  Ubuntu | Kubuntu) OS="$GRUB_DISTRIBUTOR" ;;
  *) OS="$GRUB_DISTRIBUTOR GNU/Linux" ;;
  esac
  CLASS="--class $(echo "$GRUB_DISTRIBUTOR" | tr '[:upper:]' '[:lower:]' | cut -d' ' -f1 | LC_ALL=C sed 's,[^[:alnum:]_],_,g') $CLASS"
fi
TITLE="$(gettext_printf "%s (Text mode)" "$OS")"

# DO NOT output anything to stdout BEFORE THIS!
# At any point before this cat, you should assume
# that the program can end at any time, and that
# if it does, the user's computer *will not* boot
# This is likely exaggerated, as grub would likely save it
# but that's not a risk that should be unnecessarily taken.

cat <<-EOF
menuentry '$(printf "%s" "$TITLE" | grub_quote)' $CLASS {
EOF
save_default_entry | grub_add_tab
# taken from 10_linux
if [ -z "$GRUB_GFXPAYLOAD_LINUX" ] || [ "$GRUB_GFXPAYLOAD_LINUX" != text ]; then
  echo "load_video" | grub_add_tab
fi
echo "set gfxpayload=$GRUB_GFXPAYLOAD_LINUX" | grub_add_tab

cat <<-EOF
  insmod gzio
  if [ x\$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
EOF
if [ "$dirname" = '/' ]; then
  prepare_grub_to_access_device "$GRUB_DEVICE" | grub_add_tab
else
  prepare_grub_to_access_device "$GRUB_DEVICE_BOOT" | grub_add_tab
fi
cat <<-EOF
  linux	$rel_dirname/$basename "root=$LINUX_ROOT_DEVICE" ro $GRUB_CMDLINE_ARGS init 3
  initrd	$initrd
}
EOF
