#!/usr/bin/env bash
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"
USE_COLOR=1
shopt -u dotglob # It's paramount that dotglob is *off*. Dot files are not considered todos and shouldn't be shown.

todo_dir="$XDG_DATA_HOME/todo"
function usage() {
  cat <<EOF || true
Usage: $THIS [OPTS]... [action]
manage todos.

Valid actions:
List [name]: List the current todos (default)
Count [name]: Count the number of todos
Add <name>: Add a new todo (opens \$EDITOR)
Show <name>: Show the description of todo (opens a pager)
Edit <name>: Edit todo in \$EDITOR (Creates todo if not exist)
Remove/rm <name>: Remove todo
Done <name>: Synonoym for Remove
Path [name]: Print the path of the todo (directory if no name specified)

Options:
  -h, --help         Show this help message.
  -d, --dir DIR      Set a different todo dir (default: \$XDG_DATA_HOME/todo)
EOF
}

mkdirname() { local d && for d in "$@"; do mkdir -p -- "$(dirname -- "$d")"; done; }
# usage: show_directory DIR
show_directory() {
  local dir="${1%/}" # remove trailing slash
  [ -d "$dir" ] || { err "No directory: $dir" && return 1; }
  files=("${dir%/}/"*)
  for f in "${files[@]}"; do # Ensure no double slashes
    ! [ -d "$f" ] || f+=/    # trailing slash on directories
    log "${f#"$dir/"}"       # remove the leading directory
  done
  [ "${#files[@]}" -gt 0 ] || log "No todos!"
}

LONGOPTS="help,handle-completion-options,dir:" SHORTOPTS="h,d:"
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --dir | -d) todo_dir=$2 && shift 2 ;;
  --handle-completion-options)
    long=() short=()
    split long "," "$LONGOPTS" && split short "," "$SHORTOPTS"
    for opt in "${long[@]%:}"; do      # Strip trailing colons
      [ "--$opt" != "$1" ] || continue # skip --handle-completion-options
      [ -n "$opt" ] || continue        # skip empty
      printf -- '--%s ' "$opt"
    done
    for opt in "${short[@]%:}"; do # Strip trailing colons
      [ -n "$opt" ] || continue    # skip empty
      printf -- '-%s ' "$opt"
    done
    printf '\n'
    exit 0
    ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

mkdir -p -- "$todo_dir" || abort "Couldn't create the todo dir: $todo_dir"
cd "$todo_dir" || abort "Couldn't move into the todo dir: $todo_dir"

action=${1:-list} action=${action,,} # lowercase
name="${2:-}"

case "$name" in
.*) abort "Name can't start with a dot (hidden files)!" 2 ;;
esac

case "$action" in
list | ls) show_directory "$todo_dir/$name" ;;
count | wc)
  dir="$todo_dir/$name"
  [ -d "$dir" ] || abort "No directory: $dir"
  count "$dir"/*
  ;;
add | edit)
  [ -n "$name" ] || abort "usage: $THIS $action <name>" 2
  # Add and edit are the same, EXCEPT add can not double create a todo
  if [ "$action" == add ] && [ -e "$name" ]; then abort "Todo already exists: $name"; fi
  mkdirname "$name" || abort "Could not create directory for todo file"
  edit "$name"
  ;;
show | cat)
  [ -n "$name" ] || abort "usage: $THIS $action <name>" 2
  [ -e "$name" ] || abort "Todo doesn't exist: $name"
  if [ -d "$name" ]; then
    show_directory "$name"
  else
    page "$name"
  fi
  ;;
rm | remove | done)
  [ -n "$name" ] || abort "usage: $THIS $action <name>" 2
  [ -e "$name" ] || abort "Todo doesn't exist: $name"
  rm -ri -- "$name"
  ;;
path | dir)
  [ -z "$name" ] || [ -e "$name" ] || abort "Todo doesn't exist: $name"
  ret=${todo_dir}/${name}
  ret=${ret//\/\//\/} ret="${ret%/}" # remove double slashes and trailing slash
  log "$ret"
  ;;
*) abort "Unrecognized action: $action" 2 ;;
esac
