#!/usr/bin/env sh
# This is copied from ubuntu, and should shadow it.
set -euC
# prefix "$@" with grub-mkconfig command
set -- grub-mkconfig -o /boot/grub/grub.cfg "$@"
# prefix *that* with $SUDO if not root
[ "$(id -u)" -ne 0 ] || exec "$@" || exit
exec ${SUDO:-sudo} "$@" || exit
