#!/usr/bin/env bash
set -euC
optional() { "$@" || true; }
old=()
read -ar old < <(xset q | grep DPMS -A 1 | awk '/Standby/{print $2 " " $4 " " $6}')
revert() {
  optional xset dpms force on
  optional xset dpms "${old[@]}"
}
trap revert HUP INT TERM EXIT
# every 5 seconds
optional xset +dpms dpms 5 5 5
# force off the first time
optional sleep .5 && optional xset dpms force off &
i3lock -n -f -e -c 000000
revert
