#!/bin/bash
# this is a hack to make desktop files with Terminal=true open in the right application

[ "$1" = "--" ] || {
  exec /usr/bin/gnome-terminal "$@"
  exit 0
}

shift

TITLE="$(basename "$1")"
if [ -n "$TITLE" ]; then
  x-terminal-emulator "$@"
else
  x-terminal-emulator "$@"
fi
