#!/usr/bin/env bash
set -euC -o pipefail
shopt -s nullglob globstar extglob
. script_utils.sh || exit

function usage() {
  cat <<EOF
Usage: $THIS [PATTERN]...
Lists executables present in \$PATH
If PATTERN is specified, it will be passed to grep to filter the executables (OR)

OPTIONS:
  -h, --help      display this help message
  -p, --path      <path> use <path> instead of \$PATH
EOF
  return 0
}
LONGOPTS=help,path: SHORTOPTS=h,p:
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

path="${PATH:-}"
while true; do
  case "$1" in
  -h | --help) usage && exit 0 ;;
  -p | --path) path="$2" && shift 2 ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

function get_execs() {
  local d f dirs=()
  local path="${1:-$PATH}"
  path="${path#:}:" # ensure trailing colon
  readarray -d ':' -t dirs < <(printf '%s' "$path") || true
  for d in "${dirs[@]}"; do
    [ -n "$d" ] || d=.
    for f in "$d"/.[!.]* "$d"/..?* "$d"/*; do
      if [ -f "$f" ] && [ -x "$f" ]; then
        printf '%s\n' "${f##*/}"
      fi
    done
  done
}

function filter() {
  # if patterns given, pass them to grep, else output stdin exactly.
  [ "$#" -gt 0 ] || { cat || return && return; }
  args=()
  for pat; do args+=(-e "$pat"); done
  grep "${args[@]}"
}

get_execs "$path" | sort -u | filter "$@"
