#!/usr/bin/env bash
set -euC -o pipefail

THIS=sort-files
function usage() {
  cat <<EOF
$THIS [options] [--] [DIR...]
Outputs the files in the current (or specified) directory in order of smallest to largest.

Options:
-h, --help              show this message
-r, --reverse           output from largest to smallest
EOF
  return 0
}

function log() { printf '%s\n' "$@"; }
function err() { printf "$THIS: %s\n" "$@" >&2; }
function abort() { err "$1" && exit "${2:-1}"; }

sort_args=(-hs)
args=()
for arg; do
  case "$arg" in
  --) args+=("$@") && break ;;
  -h | --help) usage && exit 0 ;;
  -hr | -rh) usage && exit 0 ;; # handle manually for now
  -r | --reverse) sort_args+=(-r) ;;
  *) args+=("$arg") ;;
  esac
done

du -h --max-depth=1 -a --one-file-system -- "${args[@]}" | sort "${sort_args[@]}" | awk '
  # shell_quote --- quote an argument for passing to the shell
  function shell_quote(s, SINGLE, QSINGLE, i, X, n, ret){
    if (s == "") return "\"\""
    SINGLE = "\x27"  # single quote
    QSINGLE = "\"\x27\""
    n = split(s, X, SINGLE)
    ret = SINGLE X[1] SINGLE
    for (i = 2; i <= n; i++)
        ret = ret QSINGLE SINGLE X[i] SINGLE
    return ret
  }

  {
    printf("%4s ", $1);
    s="";
    for (i = 2; i <= NF; i++) s = s $i " ";
    s = substr(s, 1, length(s)-1);
    sub( /^.\//, "", s)
    system("ls -F --color=always -d -- " shell_quote(s))
  }'
