#!/usr/bin/env bash

# ~/.local/bin/assert-newlines
#
# searches all text files
# and appends a newline '\n' if it doesn't already
# end in a newline.
#
set -euC -o pipefail
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }

THIS=assert-newlines
usage() {
  cat <<-EOF
  $THIS DIR...

  searches all text files and appends a newline if it doesn't already end in a one.
EOF
}

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  local parsed
  local code=0 && getopt --test &>/dev/null || code=$?
  if [ "$code" -ne 4 ]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
  parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@") ||
    exit 2                     # getopt has already complained about wrong arguments to stdout - Exit script
  printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
}

LONGOPTS=help SHORTOPTS=h
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING"

while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

found=false
for arg in "$@"; do
  if [ -n "$arg" ] && ! [ -e "$arg" ]; then
    abort "file '$arg' does not exist" 2
  fi

  IFS= readarray -d '' files < <(find "${arg:-.}" -not -path '*/.*' -type f -exec grep -Iq . {} \; -print0)
  for file in "${files[@]}"; do
    # Check if ends in new line
    if ! [[ "$(tail -c1 "$file" | wc -l)" -gt 0 ]]; then
      log "adding newline to $file"
      found=true
      printf '\n' >>"$file"
    fi
  done
done
if [ $found = false ]; then log "No files without a ending newline were found"; fi
