#!/usr/bin/env bash

# ~/.local/bin/contents
#
# Read the contents of a file or executable
# *Follows Symlinks*
#
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils" || exit

save_file="$HOME/.config/emacs/games/dunnet.save"
function usage() {
  cat <<EOF
Usage: $THIS [options] [--] [emacs-options]
Opens dunnet automatically loading the save file
Depends on emacs being installed.

Options:
  -n, --nosave       Don't use a save file
  -h, --help         show this message
  -s, --save=save    use save instead of $save_file
  -e, --emacs=path   use path instead of searching \$PATH
EOF
  return 0
}
LONGOPTS=help,nosave,emacs:,save: SHORTOPTS=h,n,e:,s:
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

emacs=
while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --) shift && break ;;
  -n | --nosave) save_file='' && shift ;;
  -e | --emacs) emacs="$2" && shift 2 ;;
  -s | --save) save_file="$2" && shift 2 ;;
  *) abort "This is a bug" 3 ;;
  esac
done

[ -n "$emacs" ] || emacs="$(cmdpath emacs 2>/dev/null)" || true
[ -x "$emacs" ] || abort 'Emacs is required to run dunnet' 2

dunnet="$(printf '%s\n' /usr/share/emacs/*/lisp/play/dunnet.elc | head -n1)"
# no-site go-to-save-location no-init load-dunnet anything-else-passed
emacs_args=(-Q -batch -l "$dunnet")

# Output to tty and setup chdir
if [ -n "$save_file" ]; then
  log "Run 'restore $(basename -- "$save_file")' to (re)load" "run 'save $(basename -- "$save_file")' to overwrite save data"
  emacs_args+=(-chdir "$(dirname "$save_file")")
else
  log "run 'save /path/to/dunnet.save' to overwrite save data (relative to CWD)"
fi
emacs_args+=("$@")

# No save file exists, just run it
[ -f "$save_file" ] || exec emacs "${emacs_args[@]}"
# save file exists, auto restore
cat <(printf '%s\n' "restore $(basename "$save_file")") - | exec emacs "${emacs_args[@]}"
