#!/usr/bin/env bash
# This starts gdm through systemd graphical.target
set -euC -o pipefail

THIS=$(basename -- "${BASH_SOURCE[0]}")
case "$THIS" in
stop-*) target=multi-user.target does=stops ;;
*) target=graphical.target does=starts ;; # default to start-gdm
esac

function usage() {
  cat <<EOF || true
Usage: $THIS 
$does gdm through systemd target $target

Options:
  -h, --help  Show this message
EOF
}
function log() { printf '%s\n' "$@" || true; }
function err() { printf "$THIS: %s\n" "$@" >&2 || true; }
function abort() { err "$1" && exit "${2:-1}"; }
function verbose() { log "> ${*@Q}" && "$@"; }
# use like `"${sudo[@]}" do_something`
# shellcheck disable=SC2206 # Splitting is intentional.
sudo=(${SUDO:-sudo})
[ "$(id -u)" -eq 0 ] && sudo=()

# Basic arg handling
for arg; do
  case "$arg" in
  --help | -h) usage && exit 0 ;;
  -*) abort "unrecognized option '$arg'" 2 ;;
  esac
done

# start the graphical system
verbose exec "${sudo[@]}" systemctl isolate "$target"
