#!/usr/bin/env bash
set -eu

THIS=manual-installs

release=$(lsb_release -ds | awk '{printf tolower($1) "-" $2}')
codename=$(lsb_release -cs)
desktop=$(dpkg -l ubuntu-desktop &>/dev/null && echo "desktop" || echo "live-server")
manifestURL="http://releases.ubuntu.com/$codename/$release-$desktop-amd64.manifest"

usage() {
  cat <<EOF
$THIS [options]
                  
uses apt-mark to fetch a list of manually installed packages and compares against the
ubuntu manifest (or a given list of packages) to find the packages that were manually
installed by the user.

Options:
-h, --help           show this message
-m, --manifest=url   use the url given to download the manifest (default: $manifestURL)
EOF
  return 0
}

log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  # -allow a command to fail with !’s side effect on errexit
  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
  # shellcheck disable=SC2251
  ! getopt --test >/dev/null
  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi

  local parsed
  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
    # output getopt’s output this way to handle the quoting right:
    printf '%s' "set -- $parsed"
    return 0
  fi
  # getopt has already complained about wrong arguments to stdout - Exit script
  exit 2
}

# option --long/-l requires 1 argument
LONGOPTS=help,manifest:
SHORTOPTS=h,m:
ARGSTRING="$(parse_args "$@")"
eval "$ARGSTRING"

while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --) shift && break ;;
  -m | --manifest) manifestURL="$2" && shift 2 ;;
  *) abort "This is a bug" 3 ;;
  esac
done

if [ -z "$manifestURL" ]; then abort "No manifest URL was provided" 2; fi

showmanual=$(apt-mark showmanual | sort)

set -o pipefail
declare -i curl_exit=0
manifest_content=$(curl -SsLf "$manifestURL" | cut -f1 | sort) || curl_exit="${PIPESTATUS[0]}"
set +o pipefail

if [ "$curl_exit" -eq 0 ]; then
  comm -23 <(printf "%s" "$showmanual") <(printf "%s" "$manifest_content")
else
  abort "downloading the manifest from '$manifestURL' failed" 1
fi
