#!/usr/bin/env bash
# usage: fullscreen [Search-Term]
set -ue
THIS=fullscreen
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }
usage() {
  command cat <<EOF
$THIS [opttions...] [--] [SEARCH] [xdotool-args...]

if run without arguments, uses selectwindow to request a window,
else searches window class, name, and classname for SEARCH. When
A window is found, it is maximized and moved to the top left corner.
Use DISPLAY=:dsp fullscreen to control other screens

xdotool-args are commands for xdotool that are prepended to the
windowsize command. Use {id} to mean the specified window id.

Options:
-h, --help              Show this help message
-d, --display=display   Set the display to use (default $DISPLAY)
EOF
  return 0
}

# Sets the variable $args to an array of positional arguments
# Usage: parse_args "$@"
function parse_args() {
  # If awaiting an argument
  next='' next_arg='' end=false args=()
  for arg in "$@"; do
    if [ $end = true ]; then
      args+=("$arg") && continue
    elif [ -n "$next" ]; then
      declare -x "$next"="$arg" next=''
    else
      case "$arg" in
      --help | -h) usage && exit 0 ;;
      --) end=true ;;
      -d | --display) next=display next_arg="$arg" ;;
      --display=*) display="${arg#--display=}" ;;
      --*) abort "Invalid option -- ${arg#--}" 2 ;;
      -*) abort "Invalid option -- ${arg#-}" 2 ;;
      *) args+=("$arg") ;;
      esac
    fi
  done
  # If awaiting an argument, but end of args
  if [ -n "$next" ]; then abort "$next_arg requires an argument" 2; fi
  unset end next next_arg
}

display="${DISPLAY:-}"
parse_args "$@"

classname="${args[0]:-}"
if [ -z "$classname" ]; then
  find=(selectwindow)
else
  find=(search --name --class --classname -- "$classname")
fi
id=$(DISPLAY="$display" xdotool "${find[@]}") || abort "Could not find window on display: '${display:-NONE}'"

userargs=()
# Replace {id} with the id in the user string
for arg in "${args[@]:1}"; do userargs+=("${arg//\{id\}/$id}"); done

DISPLAY="$display" xdotool "${userargs[@]}" windowsize "$id" 100% 100% windowmove "$id" 0 0
