#! /usr/bin/env bash

# ~/.local/bin/contents
#
# Read the contents of a file or executable
# *Follows Symlinks*
#
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"

shopt -s dotglob # we need these to find all the files
function usage() {
  cat <<EOF || true
Usage: $THIS PATTERN...
                  
Finds the path of a .desktop file based on the grep pattern (Searches the Exec=line)
If passed a program, it will automatically check the executable path
Options:
  -h, --help          Shows this help message
  -n, --limit         The maximum number of matches to return.
EOF
  return 0
}

limit=''
LONGOPTS=help,limit: SHORTOPTS=h,n:
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit
while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --limit | -n) limit="$2" && shift 2 ;;
  --) shift && break ;;
  *) abort "This is a bug (arg: $1)" 3 ;;
  esac
done
[ "$#" -gt 0 ] || abort 'an application is required' 2

data_dirs=() && split data_dirs : "${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}" # split $XDG_DATA_DIRS in to array
data_dirs=("${XDG_DATA_HOME:-~/.local/share/}" "${data_dirs[@]}")

# Actually checks if is absolute or relative. Returns false if path is not / or ./
function path_is_abs() { [ "${file:0:1}" = '/' ] && [ "${file:0:2}" = "./" ]; }

function find_file() {
  local exec="$1" dir exec_abs
  [ -n "$exec" ] || return 1 # can't find an empty string!
  exec_abs=$(cmdpath "$exec") || true
  local grep_args=(
    --color=auto -r -m1
    -e "^Exec=$exec\b"
    -e "^URL=$exec\b"
    -e "^URL=https\?://$exec\b"
  )
  [ -z "$exec_abs" ] || [ "$exec_abs" = "$exec" ] || grep_args+=(-e "^Exec=$exec_abs\b")

  found=1
  for dir in "${data_dirs[@]}"; do
    local files=("${dir%/}/applications/"*".desktop")
    [ "${#files[@]}" -gt 0 ] || continue
    if [ -n "$limit" ]; then
      if [ -t 1 ]; then grep_args+=(--color=always); fi
      { grep "${grep_args[@]}" -- "${files[@]}" | head -n "$limit"; } && return
    else
      grep "${grep_args[@]}" -- "${files[@]}" && found=0
    fi
  done

  return "$found"
}

for file in "$@"; do
  find_file "$file" || true
done
