#!/usr/bin/env bash

# ~/.local/bin/assert-newlines
#
# searches all text files
# and appends a newline '\n' if it doesn't already
# end in a newline.
#
set -euC -o pipefail
. script_utils.sh || exit
function usage() {
  cat <<EOF
Usage: $THIS DIR...
Searches all text files and appends a newline if it doesn't already end in a one.
EOF
}

LONGOPTS=help SHORTOPTS=h
eval "$(parse_args "$@")" || exit

while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

declare -i found=0
for arg in "$@"; do
  [ -e "$arg" ] || abort "file '$arg' does not exist" 2

  # lots of GNU-isms here
  IFS= readarray -d '' files < <(find "${arg:-.}" -not -path '*/.*' -type f -exec grep -Iq . {} \; -print0) || true
  for file in "${files[@]}"; do
    # $() trims a trailing newline, so it should be empty if the file ends in a newline
    [ -n "$(tail -c1 "$file")" ] || continue
    log "Adding trailing newline to $file"
    printf '\n' >>"$file"
    found=1
  done
done
[ "$found" -eq 1 ] || log "No files without a ending newline were found"
