#!/usr/bin/env bash

# ~/.local/bin/internet
#
# tests internet connection by pinging google.com
set -eu -o pipefail

test_url=google.com

THIS=internet
usage() {
  cat <<EOF
$THIS [options] [--] [arguments]
                  
Returns 0 if internet connection is present, else 1

Options:
-h, --help       show this message
-t, --test=url   use url instead of $test_url to test internet connection
-q, --quiet      don't print a message at end of test
EOF
  return 0
}

log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  # -allow a command to fail with !’s side effect on errexit
  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
  # shellcheck disable=SC2251
  ! getopt --test >/dev/null
  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi

  local parsed
  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
    # output getopt’s output this way to handle the quoting right:
    printf '%s' "set -- $parsed"
    return 0
  fi
  # getopt has already complained about wrong arguments to stdout - Exit script
  exit 2
}

# option --long/-l requires 1 argument
LONGOPTS=help,test:,quiet
SHORTOPTS=h,t:,q
ARGSTRING="$(parse_args "$@")"
eval "$ARGSTRING"
quiet=false
while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  -q | --quiet) quiet=true && shift ;;
  -t | --test) test_url=$2 && shift 2 ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

exit=0
if [ $quiet = true ]; then
  ping -q -c 3 "$test_url" &>/dev/null || exit="$?"
else
  ping -c 3 "$test_url" || exit="$?"
fi

if [ "$quiet" != true ]; then
  log ''
  if [ "$exit" -eq 0 ]; then
    log "You have internet!"
  else
    log "Your internet connection is not functional"
  fi
fi
exit "$exit"
