#!/usr/bin/env bash
set -euC -o pipefail
shopt -s nullglob # *not-exists* = ""
shopt -s globstar # **

log() { printf '%s\n' "$@"; }

# Check the size of `dir` before and after running `cmd`
# Usage: size_diff dir cmd [args...]
size_diff() {
  local dir oldsize newsize saving
  dir=$1
  oldsize=$(du -s -- "$dir" | awk '{ print $1 }')

  shift  # remove dir
  "${@}" # run $2 $3 $4 ...

  newsize=$(du -s -- "$dir" | awk '{ print $1 }')
  saving=$((oldsize - newsize))

  # After this point, don't use any of these variables for math!!
  if command -v numfmt &>/dev/null; then
    oldsize=$(numfmt --to=si -- "$oldsize")
    newsize=$(numfmt --to=si -- "$newsize")
    saving=$(numfmt --to=si -- "$saving")
  fi

  log "Old size: $oldsize"
  log "New size: $newsize"
  log "Total saving: $saving"
}

clean_config_dir() {
  local dir=$1 file

  # causes issues?
  for d in "$dir/OnDeviceHeadSuggestModel" \
    "$dir/Default/optimization_guide_prediction_model_downloads" \
    "$dir/Default/optimization_guide_model_metadata_store" \
    "$dir/Default/optimization_guide_hint_cache_store" \
    "$dir/pnacl" "$dir/BrowserMetrics"; do
    if [ -d "$d" ]; then
      rm -rf -- "$d"
      touch -- "$d"
    fi
  done

  for file in "$dir/Safe Browsing" "$dir/Crash Reports" "$dir/"**/*Cache "$dir"/**/Cache* "$dir"/**/LOG "$dir"/**/LOG.old "$dir/Default/IndexedDB/"*; do
    if [ -e "$file" ]; then rm -rf -- "$file"; fi
  done
}

clean_cache_dir() {
  local dir=$1
  local file="$dir/Default"
  if [ -e "$file" ]; then rm -rf -- "$file"; fi
}

clean_browser_conf_and_cache() {
  local config_dir=${1%/}/ cache_dir=${2%/}/ # ensure trailing slash (to dereference symlinks)
  log "Cleaning config directory $config_dir"
  size_diff "$config_dir" clean_config_dir "$config_dir"
  log "Cleaning cache directory $cache_dir"
  size_diff "$cache_dir" clean_cache_dir "$cache_dir"
}

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}"
case "$BROWSER" in
"" | vivaldi*)
  log "Cleaning browser configuration for vivaldi"
  clean_browser_conf_and_cache "$config_dir/vivaldi" "$cache_dir/vivaldi"
  ;;
google-chrome*)
  log "Cleaning browser configuration for google-chrome"
  config_dir="${CHROME_CONFIG_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}}"
  clean_browser_conf_and_cache "$config_dir/google-chrome" "$cache_dir/google-chrome"
  ;;
esac
