#!/usr/bin/env bash
#
# This file echoes a bunch of color codes to the
# terminal to demonstrate what's available.  Each
# line is the color code of one forground color,
# out of 17 (default + 16 escapes), followed by a
# test use of that color on all nine background
# colors (default + 8 escapes).
#
set -euC -o pipefail

## UTILS ##################################
THIS='logind-run'
usage() {

  cat <<EOF
$THIS [-h] TTY -- COMMAND [ARGUMENTS]...
Runs a COMMAND on TTY with a new logind session

OPTIONS:
  -h, --help      display this help message
EOF
  return 0
}
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() {
  err "$1"
  exit "${2:-1}"
}

for arg; do
  case "$arg" in
  --help | -h) usage && exit 0 ;;
  --) break ;;
  esac
done

if [ "$#" -lt 1 ]; then
  printf 'tty must be specified'
  exit 2
elif [ -z "${2:-}" ]; then
  printf 'command must be specified'
  exit 2
fi
ttynum=${1-34}
SUDO=${SUDO:-sudo}
if [ "$EUID" -eq 0 ]; then SUDO=; fi
exec $SUDO env "PATH=$PATH" systemd-run \
  --property PAMName=login \
  --property User="$USER" \
  --property StandardInput=tty \
  --property TTYPath=/dev/tty"$ttynum" \
  "${@:2}"
