#!/usr/bin/env bash
set -euC -o pipefail
function log() { printf '%s\n' "$@"; }
function err() { printf '%s\n' "$@" 1>&2; }
function abort() {
  err "$1"
  exit "${2:-1}"
}
function has() { [ -x "$(command -v -- "$1")" ]; }
# shellcheck disable=SC2206 # split intentionally
SUDO=(${SUDO:-sudo})
function sudo_cmd() { "${SUDO[@]}" "$@"; }
function get_fs_root() { stat --format '%m' -- "$1"; }
# usage: human_readable [number] [precision]
function human_readable() {
  local p=${2:-2} # default two places
  local args=()
  if [ -n "${1:-}" ]; then args+=("$1"); fi # optional number
  numfmt --to=si --format="%.${p}f" -- "${args[@]}"
}
function get_used_bytes() {
  [ -n "$1" ] || return 2 # Empty string
  [ -e "$1" ] || return 1 # ENOENT
  # -P for posix output, -k for 1024 bytes output(depends on POSIXLY_CORRECT otherwise)
  # Tail to just get line desired
  # Multiply by 1024 to convert from KiB to B
  # NOTE: the call to awk could break if the dev file has a space in it...
  df -Pk -- "$1" | tail -n +2 | awk '{print $3 * 1024}'
}

# Get size before starting

oldsize_root=$(get_used_bytes /) # Convert from KiB to B
if [ "$(get_fs_root /)" = "$(get_fs_root ~)" ]; then
  oldsize="$oldsize_root"
else
  oldsize_home=$(get_used_bytes ~) # Convert from KiB to B
  oldsize=$((oldsize_root + oldsize_home))
fi

# Start doing things

if has pnpm; then
  log "Cleaning pnpm store"
  pnpm store prune
fi

log "Cleaning browser cache"
clean-google-cache

if has snap; then
  log "Cleaning up snap packages"
  snap-cleanup -y
fi

log "Cleaning package manager cache"
if has nala; then
  sudo_cmd nala clean
elif has apt; then
  sudo_cmd apt-get clean
  sudo_cmd apt-get autoclean
elif has yay; then
  yay -Sc
elif has pacman; then
  sudo_cmd pacman -Sc
else
  err "Could not find a package manager to clean up"
fi

if has flatpak; then
  log "Repairing flatpak repo"
  sudo_cmd flatpak repair
fi

log "Cleaning up cache files"
rm -rf -- ~/.cache/node/corepack/
rmdir --ignore-fail-on-non-empty -- ~/.cache/node/
rm -rf -- ~/.cache/npm/
rm -rf -- ~/.cache/yarn/
rm -rf -- ~/.cache/gnome-desktop-thumbnailer/
rm -rf -- ~/.cache/mesa_shader_cache/

log "Cleaning the trash"
if has trash-empty; then
  trash-empty
elif has gio; then
  gio trash --empty
else
  abort "Could not find a command to clean the trash"
fi

log "Running TRIM on mounted partitions"
sudo_cmd fstrim -av || true # this may fail (ex: in container or unsupported fs)

# Size stats
log "Cleaning old logs >1G"
sudo journalctl --vacuum-size=1G

newsize_root=$(get_used_bytes /)
if [ "$(get_fs_root /)" = "$(get_fs_root ~)" ]; then
  newsize="$newsize_root"
else
  newsize_home=$(get_used_bytes ~)
  newsize=$((newsize_root + newsize_home))
fi
saving=$((oldsize - newsize))

log "Old size: $(human_readable "$oldsize")"
log "New size: $(human_readable "$newsize")"
log "Total saving: $(human_readable "$saving")"
