#!/usr/bin/env bash
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"

default_sink='@DEFAULT_SINK@' default_source='@DEFAULT_SOURCE@'
function usage() {
  cat <<EOF || true
Usage: $THIS [OPTS]... [PERCENT|'mute']
Sets the volume to the specified PERCENT. Use n{+,-} to incremenet the volume.
Call with no positional arguments to output the current volume.

Options:
  -h, --help           Show this help message.
  -m, --mute           Toggle mute on the device (PERCENT is ignored).
  -d, --device=dev     pactl sink/source to set the volume on (default: $default_sink)
  -s, --source         Treat device as a source instead. (default: $default_source)
EOF
}

LONGOPTS="help,device:,mute,source" SHORTOPTS="h,d:,m,s"
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

device="$default_sink" device_type=sink
mute=0
while true; do
  case "$1" in
  -h | --help) usage && exit 0 ;;
  -d | --device) device="$2" && shift 2 ;;
  -m | --mute) mute=1 && shift ;;
  -s | --source)
    device_type=source
    # Don't change if the user specified a source
    if [ "$device" = "$default_sink" ]; then
      device="$default_source"
    fi
    shift
    ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

case "${1:-}" in
mute | m) mute=1 ;;
esac

if [ "$mute" -eq 1 ]; then
  pactl "set-$device_type-mute" "$device" toggle
elif [ "$#" -eq 0 ]; then
  pactl "get-$device_type-volume" "$device"
else
  suf='' vol=${1}
  case "$vol" in
  +* | *+) suf=+ ;;
  -* | *-) suf=- ;;
  esac
  # all valid: 20-, -20, 20+, +20, +20%, 20%+, 20%
  vol=${vol%-} vol=${vol#-} vol=${vol%+} vol=${vol#+} vol=${vol%\%}
  pactl "set-$device_type-volume" "$device" "$suf$vol%"
  pactl "set-$device_type-mute" "$device" false # user experience! :)
fi
