#!/usr/bin/env bash
# this is a hack to make desktop files with Terminal=true open in the right application

if [ "$1" != "--" ]; then
  exec /usr/bin/gnome-terminal "$@"
else
  exec x-terminal-emulator -e "${@:2}"
fi
