#!/usr/bin/env bash

# ~/.local/bin/post-temp
#
# Hosts a temporary file on the internet for 60 mins and echos the url.
#
#
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"

temp_source=https://tmpfiles.org/api/v1/upload

function usage() {
  cat <<EOF || true
Usage: $THIS [OPTION...] [--] FILE...
Hosts a temporary file on the internet for 60 mins and outputs the url.

OPTIONS:
  -h, --help         display this help message
  -v, --verbose      display verbose messages
  -q, --quiet        be quieter
  -t, --temp=url     use url to upload files (POST) (default: $temp_source)
  -p, --python=path  use path as python interpreter to parse json instead of searching PATH.
EOF
}
LONGOPTS=help,verbose,quiet,python:,temp: SHORTOPTS=h,v,q,p:,t:
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

verbose=0 quiet=0 python=
while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --) shift && break ;;
  -v | --verbose) verbose=1 && shift ;; # Verbose option
  -q | --quiet) quiet=1 && shift ;;     # Quiet option
  -t | --temp) temp_source="$2" && shift 2 ;;
  -p | --python) python="$2" && shift 2 ;;
  *) abort "This is a bug" 3 ;;
  esac
done

[ "$#" -gt 0 ] || abort "FILE is required!" 2 # Error if no files given

[ -n "$python" ] || python=$(cmdpath python3 || cmdpath python) || true

declare -i exitcode=0
for file in "$@"; do
  [ -f "$file" ] || abort "'$file' is not a file" 1

  result="$(curl -L -F "file=@$file" "$temp_source")" || abort 'Something went wrong during curl command.' 1
  # Example outputs:
  # {"message": "server error"}
  # {"status":"success","data":{"url":"https://tmpfiles.org/######/file"}}

  # If verbose, or python not installed, print entire json
  if [ "$verbose" = 1 ] || [ -z "$python" ]; then
    log "$result"
    [ -n "$python" ] || continue # Stops loop here because python is not installed
  fi

  # Print the result thru python to get the data
  status=$(python3 -c "import sys, json; j=json.load(sys.stdin); 'status' in j and print(j['status'])" <<<"$result")
  url=$(python3 -c "import sys, json; j=json.load(sys.stdin); 'data' in j and 'url' in j['data'] and print(j['data']['url'])" <<<"$result")

  if [ -z "$status" ] || [ -z "$url" ]; then
    message=$(python3 -c "import sys, json; j=json.load(sys.stdin); 'message' in j and print(j['message'])" <<<"$result")
    if [ -n "$message" ]; then err "$message"; else err "An unknown error occured"; fi
    exitcode=1
  else
    [ "$quiet" == 1 ] || err "$status"
    log "${url/tmpfiles.org\//tmpfiles.org\/dl\/}"
  fi
done

exit "$exitcode"
