#!/usr/bin/env bash
set -eu

THIS=rmgit
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }

declare -i VERBOSE=0 YES=0 FORCE=0

function usage() {
  cat <<-EOF
	Usage: $THIS [OPTS] REPO...

	Options:
		-v, --verbose  verbose output
		-h, --help     show this help message
		-y, --yes      don't confirm deletion of REPO
		-f, --force    force deletion of REPO. REPO/.git is always force deleted.
EOF
  return 0
}
# Sets the variable $args to an array of positional arguments
# Usage: parse_args "$@"
function parse_args() {
  # If awaiting an argument
  next='' next_arg='' end=false args=()
  for arg in "$@"; do
    if [ $end = true ]; then
      args+=("$arg") && continue
    elif [ -n "$next" ]; then
      # -x to expose outside function
      declare -g "$next"="$arg"
      next=""
    else
      case "$arg" in
      --help | -h) usage && exit 0 ;;
      --) end=true ;;
      -v | --verbose) VERBOSE=1 ;;
      -y | --yes) YES=1 ;;
      -f | --force) FORCE=1 YES=1 ;;
      --*) abort "Invalid option -- ${arg#--}" 2 ;;
      -*) abort "Invalid option -- ${arg#-}" 2 ;;
      *) args+=("$arg") ;;
      esac
    fi
  done
  # If awaiting an argument, but end of args
  if [ -n "$next" ]; then abort "$next_arg requires an argument" 2; fi
  unset end next next_arg
}

parse_args "$@"

for REPO; do
  if [ -z "$REPO" ]; then
    err "Refusing to remove empty string. (REPO is required)"
    exit 2
  fi

  if ! [ -d "$REPO" ] || ! [ -d "$REPO"/.git ]; then
    err "$REPO is not a git repository"
    exit 2
  fi

  if [ "$YES" -ne 1 ]; then
    read -rep "$THIS: remove git repository '$REPO'? " confirmation
    if ! [[ "${confirmation,,}" =~ ^\s*y(es)?\s*$ ]]; then exit 1; fi
  fi

  base_args=(--recursive)
  if [ "$FORCE" -eq 1 ]; then base_args+=(--force); fi
  if [ "$VERBOSE" -eq 1 ]; then base_args+=(--verbose); fi

  # Force rm .git
  args=(--force "${base_args[@]}" -- "$REPO/.git")
  if [ "$VERBOSE" -eq 1 ]; then log "rm ${args[*]}"; fi
  rm "${args[@]}"

  args=("${base_args[@]}" -- "$REPO/")
  if [ "$VERBOSE" -eq 1 ]; then log "rm ${args[*]}"; fi
  rm "${args[@]}"
done
