#!/usr/bin/env bash
# This starts gdm through systemd graphical.target
set -euC -o pipefail

THIS=start-gdm

function usage() {
  cat <<-EOF
usage: $THIS 

starts gdm through systemd graphical.target
No options or arguments are accepted except --help

the environment variable \`SUDO\` can be set to use a different
program for root elevation. It will be split by the shell, so
spaces in the program name will likely be mutilited.

EOF
}
function log() { printf '%s\n' "$@"; }
function err() { printf "$THIS: %s\n" "$@" >&2; }
function abort() { err "$1" && exit "${2:-1}"; }
# use like `"${sudo[@]}" do_something`
# shellcheck disable=SC2206 # Splitting is intentional.
sudo=(${SUDO:-sudo})
[ "$(id -u)" -eq 0 ] && sudo=()

# Basic arg handling
invalid=false
for arg; do
  case "$arg" in
  --help | -help | -h) usage && exit 0 ;;
  -*) err "unrecognized option '$arg'" && invalid=true ;;
  esac
done
if [ "$invalid" = true ]; then exit 2; fi
# start the graphical system
exec "${sudo[@]}" systemctl isolate graphical.target
