#!/usr/bin/env bash
set -euC -o pipefail

THIS=sort-files
function usage() {
  cat <<EOF
$THIS [options] [--] [DIR...]
Outputs the files in the current (or specified) directory in order of largest to smallest.

Arguments are passed to du. See 'du --help' or 'man du' for more information.
Default options are: '-h --max-depth=1 -a --one-file-system'

Options:
-h, --help              show this message
EOF
  return 0
}

function log() { printf '%s\n' "$@"; }
function err() { printf "$THIS: %s\n" "$@" >&2; }
function abort() { err "$1" && exit "${2:-1}"; }

for arg; do
  case "$arg" in
  --) break ;;
  -h | --help) usage && exit 0 ;;
  esac
done

dir=${1:-.}
du -h --max-depth=1 -a --one-file-system "${dir%/}" "${@:2}" | sort -hs | awk '{
    printf("%4s ", $1);
    s="";
    for (i = 2; i <= NF; i++) s = s $i " ";
    s = substr(s, 1, length(s)-1);
    sub( /^.\//, "", s)
    system("ls -F --color=always -d -- \"" s "\"")
    }'
