#!/usr/bin/env bash

set -euC -o pipefail

THIS="brightness"

function usage() {
  cat || true <<-EOF
usage: $THIS [OPTS]... [percent]
Sets the brightness to the specified integer percentage. Use n{+,-} to increment the brightness.
Without a percentage, outputs the current brightness percentage
NOTE: 1 is the minimum brightness, while 100 is the maximum brightness

the environment variable \`SUDO\` can be set to use a different
program for root elevation. It will be split by the shell, so
spaces in the program name will likely be mutilited.

Options:
  -h, --help         Show this help message.
  -d, --device=dev   the /sys style device to set the brightness on. \$device/brightness will be writen to!
EOF
}

function log() { printf '%s\n' "$@" || true; }
function err() { printf "$THIS: %s\n" "$@" >&2 || true; }
function abort() { err "$1" && exit "${2:-1}"; }
number_re='^[0-9]+$'
function is_integer() { [[ "$1" =~ $number_re ]]; }

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  local parsed
  local code=0 && getopt --test &>/dev/null || code=$?
  if [ "$code" -ne 4 ]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
  parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@") ||
    exit 2                     # getopt has already complained about wrong arguments to stdout - Exit script
  printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
}

LONGOPTS="help,device:" SHORTOPTS="h,d:"
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

device=''
while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  -d | --device) device="$2" && shift 2 ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done
show=false
if [ "$#" -eq 0 ]; then show="true"; fi

BrPath="$device"
if [ -z "$BrPath" ]; then
  BrPath="$(find /sys/class/backlight -maxdepth 1 -mindepth 1 -print0 | head -zn1 | tr -d '\0')"
fi

if [ -z "$BrPath" ]; then
  abort "Unable to find backlight device" 1
elif ! [ -d "$BrPath" ]; then
  abort "Found backlight device is not a directory" 1
elif ! [ -f "$BrPath/max_brightness" ]; then
  abort "Backlight device must support /max_brightness" 1
elif ! [ -f "$BrPath/brightness" ]; then
  abort "Backlight device must support /brightness" 1
fi

BrMax="$(<"$BrPath/max_brightness")"
if ! is_integer "$BrMax"; then abort "Invalid max brightness '$BrMax'" 2; fi
BrCur="$(<"$BrPath/brightness")"
if ! is_integer "$BrCur"; then abort "Invalid current brightness '$BrCur'" 2; fi
declare -i BrMax BrMax BrCur # Cast all to integers
# 100th max-brightness, rounded up to nearest integer
BrMin="$((0 + (BrMax + 100 - 1) / 100))"

if [ "$BrMax" -eq 0 ]; then abort "Backlight device reported maximum brightness of 0." 1; fi

BrCurRel="$(printf '%s ' "$BrCur" "$BrMax" | awk '{ print int( $1 / $2 * 100 ) }')"

if [ "$show" = true ]; then log "$BrCurRel" && exit 0; fi

BrNewRel="${1:-}" && if [ -z "$BrNewRel" ]; then abort "Brightness can't be empty" 2; fi
suf='' && case "$BrNewRel" in
+* | *+) suf=+ ;;
-* | *-) suf=- ;;
esac
BrNewRel=${BrNewRel%-} BrNewRel=${BrNewRel#-} BrNewRel=${BrNewRel%+} BrNewRel=${BrNewRel#+} BrNewRel=${BrNewRel%\%}
if ! is_integer "$BrNewRel"; then abort "Invalid brightness '$BrNewRel'" 2; fi
case "$suf" in
+) BrNewRel=$((BrCurRel + BrNewRel)) ;;
-) BrNewRel=$((BrCurRel - BrNewRel)) ;;
esac

BrNew="$(printf '%s ' "$BrNewRel" "$BrMax" | awk '{ print int( ( ($1/100) * $2) ) }')"
BrNew="$((BrNew < BrMin ? BrMin : BrNew))"
BrNew="$((BrNew > BrMax ? BrMax : BrNew))"

sudo=()
if ! [ -w "$BrPath"/brightness ]; then sudo=("${SUDO:-sudo}"); fi

printf '%s' "$BrNew" | "${sudo[@]}" tee "$BrPath/brightness" >/dev/null
