#! /usr/bin/env bash

# ~/.local/bin/contents
#
# Read the contents of a file or executable
# *Follows Symlinks*
#
set -euC -o pipefail
shopt -s nullglob dotglob globstar
THIS=contents
function usage() {
  cat <<EOF
$THIS PATTERN...
                  
Finds the path of a .desktop file based on the grep pattern (Searches the Exec=line)
If passed a program, it will automatically check the executable path
options:
-h, --help          Shows this help message
-n, --limit         The maximum number of matches to return.
EOF
  return 0
}
function log() { printf '%s\n' "$@" || true; }
function err() { printf "$THIS: %s\n" "$@" >&2 || true; }
function abort() { err "$1" && exit "${2:-1}"; }
function has() { [ -x "$(command -v -- "$1")" ]; }

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  local parsed
  local code=0 && getopt --test &>/dev/null || code=$?
  if [ "$code" -ne 4 ]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
  parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@") ||
    exit 2                     # getopt has already complained about wrong arguments to stdout - Exit script
  printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
}

limit=''
LONGOPTS=help,limit: SHORTOPTS=h,n:
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit
while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --limit | -n) limit="$2" && shift 2 ;;
  --) shift && break ;;
  *) abort "This is a bug (arg: $1)" 3 ;;
  esac
done

if [ "$#" -eq 0 ]; then
  abort 'an application is required' 2
fi

readarray -d: -t data_dirs < <(printf '%s' "${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}") # split $XDG_DATA_DIRS in to array
data_dirs=("${XDG_DATA_HOME:-~/.local/share/}" "${data_dirs[@]}")

# Actually checks if is absolute or relative. Returns false if path is not / or ./
function path_is_abs() { [ "${file:0:1}" = '/' ] && [ "${file:0:2}" = "./" ]; }

function find_file() {
  local exec="$1" dir
  [ -n "$exec" ] || return 1 # can't find an empty string!
  local exec_abs=$(command -v -- "$exec")
  local grep_args=(
    --color=auto -r -m1
    -e "^Exec=$exec\b"
    -e "^URL=$exec\b"
    -e "^URL=https\?://$exec\b"
  )
  [ -z "$exec_abs" ] || [ "$exec_abs" = "$exec" ] || grep_args+=(-e "^Exec=$exec_abs\b")

  found=1
  for dir in "${data_dirs[@]}"; do
    local files=("${dir%/}/applications/"*".desktop")
    [ "${#files[@]}" -gt 0 ] || continue
    if [ -n "$limit" ]; then
      if [ -t 1 ]; then grep_args+=(--color=always); fi
      { grep "${grep_args[@]}" -- "${files[@]}" | head -n "$limit"; } && return
    else
      grep "${grep_args[@]}" -- "${files[@]}" && found=0
    fi
  done

  return "$found"
}

for file in "$@"; do
  find_file "$file" || true
done
