#!/usr/bin/env bash

# ~/.local/bin/sync-java
#
# usage: sync-java <dest> <src>
# Sync my ~/code/java/ folder to a usb drive
#
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"

USE_COLOR=1 # Enable color
deps=(rsync diff) exclude=('*.class' 'System Volume Information')
default_dest="/media/$USER/AARONDILL" default_src="${java:-$HOME/code/java}"

function usage() {
  cat <<EOF || true
Usage: $THIS [options] [--] [dest] [src]
Syncs src to dest. Note: this is a destructive operation. Any files in dest will be overwritten or deleted.

Options:
  -e, --exclude=exclude    A colon separated list of file globs to exclude (defualt: $(join ":" "${exclude[@]}"))
  -h, --help               Show this message
  -k, --keep               Keep files present in dest, but not in src. This can be used to later run \`$THIS src dest\`.
  -d, --diff               Only show the diff between src and dest.
  -y, --yes                Don't ask for confirmation

Defaults: 
  dest=$default_dest
  src=$default_src

Dependencies: $(join ', ' "${deps[@]}")
EOF
  return 0
}

LONGOPTS=diff,exclude:,help,keep,yes SHORTOPTS=d,e:,h,k,y
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

yes=0 keep=0 diff_only=0
while true; do
  case "$1" in
  -d | --diff) diff_only=1 && shift ;;
  -h | --help) usage && exit 0 ;;
  -k | --keep) keep=1 && shift ;;
  -q | --quiet) USE_VERBOSE=0 && shift ;; # make the verbose function not output
  -y | --yes) yes=1 && shift ;;
  -e | --exclude) exclude_add=() && split exclude_add : "$2" && exclude+=("${exclude_add[@]}") ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

dest="${1:-$default_dest}"
src="${2:-$default_src}"

[ -d "$dest" ] || abort "dest: $dest is not a directory!" 1
[ -d "$src" ] || abort "src: $src is not a directory!" 1

diff_args=(-r) # recursive
# diff supports exclude patterns, add them
if diff --help 2>&1 | grep -q -- '--exclude'; then
  for e in "${exclude[@]}"; do diff_args+=(--exclude "$e"); done
fi

if [ "$diff_only" -eq 1 ]; then
  check_dependencies diff || exit
  verbose diff "${diff_args[@]}" -- "$dest" "$src"
  exit 0 # Stop here. they don't want to sync.
fi

check_dependencies "${deps[@]}" || exit
# note: diff dest src to show what copying *will do*
[ "$yes" -eq 1 ] || verbose diff "${diff_args[@]}" -- "$dest" "$src" || confirm "source and destination differ. Do you want to override destination?" || abort 'aborting' 1

# verbose, archive, recursive, update, progress
rsync_args=(-varuP)
[ "$keep" -eq 1 ] || rsync_args+=(--delete) # if not keep, then delete files not present in src
for e in "${exclude[@]}"; do rsync_args+=(--exclude "$e"); done
verbose rsync "${rsync_args[@]}" -- "$src/" "$dest/"

verbose diff "${diff_args[@]}" -- "$dest" "$src" || err "warning: source and destination differ!"

sysvol="$dest/System Volume Information"
if [ -d "$sysvol" ]; then verbose rm -rf -- "$sysvol"; fi
