#!/usr/bin/env bash
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"

# Outputs the most $2 recently modified files in directory $1
# Relies on GNU find!
get_latest() {
  local dir="${1:-.}" num=${2:-1}
  find "$dir" -mindepth 1 -maxdepth 1 -printf "%T@ %p\n" | sort -n | cut -d' ' -f 2- | tail -n "$num"
}

usage() {
  cat <<-EOF || true
usage: $THIS [opts]... [--] [DEST]
Manipulate the most recently downloaded (modified) file

Options:
  -h, --help         Show this help message.
  -n, --num=n        Operate on the nth most recent file, instead of the first
Operations (Only use one at a time):
  -r, --remove       Remove the file
  -c, --copy         Copy the file to DEST
  -m, --move         Move the file to DEST
  -e, --edit         Edit the file (using \$VISUAL or \$EDITOR)
  -p, --print        Print the file path
EOF
}

# NOTE: When updating this, update the usage and the case at the bottom!
declare -A operations=([r]=remove [c]=copy [m]=move [p]=print [e]=edit)

LONGOPTS="help,num:,$(join ',' "${operations[@]}")" SHORTOPTS="h,n:,$(join ',' "${!operations[@]}")"
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

op=print num=1 # 1=most recent
while true; do
  key="${1#--}" key="${key#-}" # remove --/- from the start
  if [ -n "$key" ]; then
    if [ -n "${operations["$key"]:-}" ]; then # check if operations' keys contain the short option
      op="${operations["$key"]}" && shift && continue
    fi
    for i in "${operations[@]}"; do # check if operations' values contain the long option
      [ "$i" == "$key" ] || continue
      op="$i" && shift && continue 2 # continue the outer while loop
    done
  fi
  case "$1" in
  -h | --help) usage && exit 0 ;;
  -n | --num)
    num="$2" && shift 2
    case "$num" in *[!0-9]* | '') abort "Invalid number: $num" 2 ;; esac
    ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done
dest=${1:-.}
downloads=$(get_xdg_dir "DOWNLOAD") || true
downloads="${downloads:-$HOME/Downloads/}" # We still haven't found something? use ~/Downloads/

file="$(get_latest "$downloads" "$num" | head -n 1)"
[ -n "$file" ] || abort "No file found!" 1
case "$op" in
remove)
  log "Removing '$file'"
  confirm "remove '$file'?" || abort "aborting" 1
  rm -rf -- "$file"
  ;;
# cp -Pp -R is posix for cp --archive
copy) log "Copying '$file' to '$dest'" && cp -pP -R -i -- "$file" "$dest" ;;
move) log "Moving '$file' to '$dest'" && mv -i -- "$file" "$dest" ;;
edit) "${VISUAL:-${EDITOR:-editor}}" -- "$file" ;;
print) printf '%s\n' "$file" ;;
esac
