#!/usr/bin/env bash
# vim: set ft=sh:
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"
USE_COLOR=1
shopt -u dotglob # It's paramount that dotglob is *off*. Dot files are not considered todos and shouldn't be shown.

todo_dir="$XDG_DATA_HOME/todo"
function usage() {
  cat <<EOF || true
Usage: $THIS [OPTS]... [action]
manage todos.

Valid actions:
Show/List [name]: Show the description of todo or list contents of directory (default)
Count [name]: Count the number of todos
Add <name>: Add a new todo (opens \$EDITOR)
Edit <name>: Edit todo in \$EDITOR (Creates todo if not exist)
Remove/rm <name>: Remove todo
Done <name>: Synonoym for Remove
Path [name]: Print the path of the todo (directory if no name specified)
Cd [name]: Open a shell in the todo's directory (main directory if no name specified)

Options:
  -h, --help         Show this help message.
  -d, --dir DIR      Set a different todo dir (default: \$XDG_DATA_HOME/todo)
EOF
}

mkdirname() { local d && for d in "$@"; do mkdir -p -- "$(dirname -- "$d")"; done; }
# usage: show_directory DIR
show_directory() {
  local dir="${1%/}" # remove trailing slash
  [ -d "$dir" ] || { err "No directory: $dir" && return 1; }
  files=("${dir%/}/"*)
  for f in "${files[@]}"; do # Ensure no double slashes
    ! [ -d "$f" ] || f+=/    # trailing slash on directories
    log "${f#"$dir/"}"       # remove the leading directory
  done
  [ "${#files[@]}" -gt 0 ] || log "No todos!"
}

LONGOPTS=(help handle-completion-{option,action}s dir:) SHORTOPTS=(h d:)
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit
COMPLETION_ACTIONS=(list ls add show edit remove rm 'done' count path cd)

while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --dir | -d) todo_dir=$2 && shift 2 ;;
  --handle-completion-actions)
    join " " "${COMPLETION_ACTIONS[@]}"
    exit 0
    ;;
  --handle-completion-options) handle_completion_flags ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

mkdir -p -- "$todo_dir" || abort "Couldn't create the todo dir: $todo_dir"
cd "$todo_dir" || abort "Couldn't move into the todo dir: $todo_dir"

action=${1:-list} action=${action,,} # lowercase
name="${2:-}"

case "$name" in
.*) abort "Name can't start with a dot (hidden files)!" 2 ;;
esac

main="$name" # The "main" todo file
# If the name is a directory, or doesn't exist and ends in a slash, then use it as a directory
if [ -d "$name" ] || { ! [ -e "$name" ] && [ -n "${name##*[^/]}" ]; }; then
  bname=$(basename -- "$name")
  main="${name%/}/$bname"
fi

case "$action" in
count | wc)
  dir="$todo_dir/$name"
  [ -d "$dir" ] || abort "No directory: $dir"
  count "$dir"/*
  ;;
add | edit | new)
  [ -n "$name" ] || abort "usage: $THIS $action <name>" 2
  # Add and edit are the same, EXCEPT add can not double create a todo
  if [ "$action" == add ] && [ -e "$name" ]; then abort "Todo already exists: $name"; fi
  mkdirname "$name" || abort "Could not create directory for todo file"
  edit "$main"
  ;;
list | ls) ;&
show | cat)
  [ -z "$name" ] || [ -e "$name" ] || abort "Todo doesn't exist: $name"
  # If empty, or directory, list
  if [ -z "$name" ] || [ -d "$name" ]; then
    show_directory "$todo_dir/$name"
  fi
  if [ -e "$main" ]; then
    page "$main"
  fi
  ;;
rm | remove | done)
  [ -n "$name" ] || abort "usage: $THIS $action <name>" 2
  [ -e "$name" ] || abort "Todo doesn't exist: $name"
  rm -ri -- "$name"
  ;;
path | dir)
  [ -z "$name" ] || [ -e "$name" ] || abort "Todo doesn't exist: $name"
  ret=${todo_dir}/${name}
  ret=${ret//\/\//\/} ret="${ret%/}" # remove double slashes and trailing slash
  if [ -d "$ret" ]; then ret+="/"; fi
  log "$ret"
  ;;
cd | chdir)
  [ -z "$name" ] || [ -e "$name" ] || abort "Todo doesn't exist: $name"
  dir="${todo_dir}/${name}"
  [ -d "$dir" ] || abort "Todo is not a directory: $dir"
  cd -- "$dir" || abort "Couldn't change to directory: $dir"
  shell=$(cmdpath "$SHELL" || getent passwd "$USER" | cut -d : -f 7)
  exec "$shell"
  ;;
*) abort "Unrecognized action: $action" 2 ;;
esac
