#!/usr/bin/env bash
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"

## UTILS ##################################
function usage() {
  cat <<EOF || true
Usage: $THIS [-h] TTY -- COMMAND [ARGUMENTS]...
Runs a COMMAND on TTY with a new logind session

OPTIONS:
  -h, --help      display this help message
EOF
}
for arg; do
  case "$arg" in
  --help | -h) usage && exit 0 ;;
  --) break ;;
  esac
done

[ "$#" -gt 0 ] || abort 'tty must be specified' 2
[ -n "${2:-}" ] || abort 'command must be specified' 2

ttynum=${1:-34}
ttynum=${ttynum#/dev/tty} # allow /dev/tty2 to work

re='^[0-9]+$'
[ -n "$ttynum" ] || abort "tty can't be empty" 2
[[ "$ttynum" =~ $re ]] || abort 'tty must be a number' 2
[ -c "/dev/tty$ttynum" ] || abort "tty must be a file in /dev/tty*" 2
if pgrep 'tty' -t "tty$ttynum" &>/dev/null; then
  abort "It seems like this tty is in use. Please try a different tty" 1
fi

set_sudo_cmd && exec "${sudo[@]}" env "PATH=$PATH" systemd-run \
  --property PAMName=login \
  --property User="$USER" \
  --property StandardInput=tty \
  --property TTYPath=/dev/tty"$ttynum" \
  "${@:2}"
