#!/usr/bin/env bash
set -eu
function verbose() {
  local tmp
  tmp="$(mktemp)" || return 1
  sudo kill -s SIGRTMIN+20 1 || {
    rm -f "$tmp"
    return 1
  }
  # make plymouth hidden
  sed /proc/cmdline -e 's/\bsplash\b//g' \
    -e 's/\(\s\)\+/\1/g' >|"$tmp" || {
    rm -f "$tmp"
    return 1
  }

  sudo umount /proc/cmdline -q || true
  sudo mount -n --bind -o ro "$tmp" /proc/cmdline || {
    rm -f "$tmp"
    return 1
  }
  rm -f "$tmp"
  return 0
}

systemctl isolate multi-user.target
