#!/usr/bin/env bash
set -eu

THIS='executables'

usage() {
  cat <<EOF
Usage: $THIS
Lists executables present in \$PATH

OPTIONS:
  -h, --help      display this help message
  -p, --path      <path> use <path> instead of \$PATH
EOF
  return 0
}
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() {
  err "$1"
  exit "${2:-1}"
}
# Sets the variable $args to an array of positional arguments
# Usage: parse_args "$@"
function parse_args() {
  # If awaiting an argument
  next='' next_arg='' end=false args=()
  for arg in "$@"; do
    if [ $end = true ]; then
      args+=("$arg") && continue
    elif [ -n "$next" ]; then
      declare "$next"="$arg" next=''
    else
      case "$arg" in
      --help | -h) usage && exit 0 ;;
      --) end=true ;;
      -p | --path) next=path next_arg="$arg" ;;
      --path=*) path="${arg#--path=}" ;;
      --*) abort "Invalid option -- ${arg#--}" 2 ;;
      -*) abort "Invalid option -- ${arg#-}" 2 ;;
      *) args+=("$arg") ;;
      esac
    fi
  done
  # If awaiting an argument, but end of args
  if [ -n "$next" ]; then abort "$next_arg requires an argument" 2; fi
  unset end next next_arg
}

path=$PATH
parse_args "$@"

get_execs() {
  local d f path dirs=()
  path="$1"
  if ! [[ $path = *: ]]; then path="$path:"; fi
  readarray -d ':' -t dirs <<<"$path"
  for d in "${dirs[@]}"; do
    [ -z "$d" ] && d=.
    for f in "$d"/.[!.]* "$d"/..?* "$d"/*; do
      if [ -f "$f" ] && [ -x "$f" ]; then
        log "${f##*/}"
      fi
    done
  done
}

get_execs "$path" | sort | uniq
