#!/usr/bin/env bash
set -euC -o pipefail
# usage: visual awesome :2 || visual :3 || visual || visual awesome args -- :3

THIS=visual
usage() {
  cat <<EOF || return 0
$THIS [client] [client-args --] [:display] 

if run without arguments, x-window-manager will be used
server will be found in the \$PATH. 
if \$2 is not a valid server and a client is provided,
the arguments will be passed directly to the startx script
EOF
}

log() { printf '%s\n' "$@"; }
err() { printf "${THIS:-}: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }
cmd() { command -v "$@" &>/dev/null; }

if ! cmd which; then abort "which is required for this script" 1; fi
if ! cmd startx; then abort "startx is required for this script" 1; fi

for arg in "$@"; do
  case "$arg" in
  -h | --help) usage && exit 0 ;;
  esac
done

wm=${1:-}
server=${2-}
rest=("${@:3}")

disp_regex="^:[[:digit:]]+$"

# visual :3
if [ -z "$server" ] && [[ "$wm" =~ $disp_regex ]]; then server="$wm" wm=''; fi

# visual :3 OR visual awesome
if [ -z "$wm" ]; then wm="x-window-manager"; fi

if ! wmpath=$(which "$wm" 2>/dev/null); then
  printf '%s\n' "Unable to find $wm in \$PATH" >&2
  exit 2
fi

cmd=(startx "$wmpath")
# if server is defined
if [[ "$server" =~ $disp_regex ]]; then
  cmd=("${cmd[@]}" --)
fi
# $"" # <-- fix highlighting
cmd=("${cmd[@]}" "$server" "${rest[@]}")

if command -v dbus-launch &>/dev/null; then
  cmd=(dbus-launch --exit-with-session -- "${cmd[@]}")
fi

printf '%s ' exec "${cmd[@]}"
export XDG_SESSION_TYPE=x11
exec "${cmd[@]}"
