#!/usr/bin/env sh
# Literally count the number of files in the current directory
THIS=file-count
usage() {
  cat <<EOF
$THIS [opts]... [DIR]

Output the number of files in DIR or the current directory on standard output.

Options:
 --help, -h   show this message
EOF
}
for arg; do
  if [ "$arg" = "--help" ] || [ "$arg" = "-h" ]; then
    usage
    exit 0
  fi
done
# First arg, or current directory
dir="${1:-.}"

find "$dir" -mindepth 1 -maxdepth 1 -printf '.' | wc -c
