#!/usr/bin/env bash
# TODO: less "/home/aaron" more "$HOME" -- need to investigate interactions with existing backups
set -euC -o pipefail

# Calls duplicity to run a backup. Passes user arguments to first arguments of duplicity.
# Requires duplicity to be installed

# ----------------------------------------------------------------
# ----------------------------------------------------------------
# ------------------------ CONFIGURATION -------------------------
# ----------------------------------------------------------------
# ----------------------------------------------------------------

# Set the symbolic name of the backup being operated on. The intent is to use a separate name for each logically distinct backup. For example, someone
# may use "home_daily_s3" for the daily backup of a home directory to Amazon S3. The structure of the name is up to the user, it is only important that
# the names be distinct. The symbolic name is currently only used to affect the expansion of --archive-dir , but may be used for additional features in
# the future. Users running more than one distinct backup are encouraged to use this option. If not specified, the default value is a hash of the backend URL.
os=$(. /etc/os-release 2>/dev/null && printf '%s\n' "${ID:-${NAME:-}}") || true
host=$(uname -n 2>/dev/null) || true
hostid=$(hostid 2>/dev/null) || true # added differential
NAME="full-system-$host-$os-$hostid"

# The source directory *to* backup (usually / or "$HOME")
SOURCE_DIR="$HOME"

# use '-path' to exclude
# use '+path' or just 'path' to include
# spaces are also permitted after the '+/-' (ie '+ path')
# to use a path starting with '-' or '+', simply pass two of them (ie '--path' and '++path')
# NOTE: order is important. the first matching pattern will be applied. (see man duplicity)

# from man:duplicity:
# The include and exclude options accept some extended shell globbing patterns. These patterns can contain '*', '**', '?', and '[...]'.
# As in a normal shell, '*' can be expanded to any string of characters not containing "/", '?' expands to any character except "/",
# and '[...]' expands to a single character of those characters specified (ranges are acceptable).
# The new special pattern, '**', expands to any string of characters whether or not it contains "/".
# Furthermore, if the pattern starts with "ignorecase:" (case insensitive), then this prefix will be removed and
# any character in the string can be replaced with an upper- or lowercase version of itself.
files=(
  "-$HOME/.cache"
  "-$HOME/.cache/deja-dup"
  "-$HOME/.config/Code"
  "-$HOME/.config/TabNine"
  "-$HOME/.config/google-chrome"
  "-$HOME/.config/google-chrome-static"
  "-$HOME/.config/vivaldi"
  "-$HOME/.config/vivaldi-static"
  "-$HOME/.local/share"
  "-$HOME/.local/share/Trash"
  "-$HOME/.local/state"
  "-$HOME/.luckyBackup/logs"
  "-$HOME/.luckyBackup/snaps"
  "-$HOME/.thunderbird"
  "-$HOME/.var"
  "-$HOME/.vscode"
  "-$HOME/.xsession-errors"
  "-$HOME/.Xauthority"
  "-$HOME/Documents/.soh"
  "-$HOME/Downloads"
  "-$HOME/snap/*/*/.cache"
  "-$HOME/code/repos"
)
# Duplicity complains if an ignore pattern is not a subdirectory of the source directory
if [ "$SOURCE_DIR" = / ]; then
  files+=("+$HOME"
    '-/sys' '-/run' '-/proc'
    '-/dev' '-/dev/shm' '-/var/tmp'
    '-/tmp' '-/media' '-/run/media' # don't backup the backup :)
    '-/mnt' '-/**/lost+found' '-**'
  )
fi

# Exclude directories if filename is present. Allows the user to specify folders
# that they do not wish to backup by adding a specified file (e.g. ".nobackup")
# instead of maintaining a comprehensive exclude/include list.
exclude_if_present=(
  'CACHEDIR.TAG'
  '.deja-dup-ignore'
  '.nobackup'
)

# Change the volume size to number MB. Default is 200MB.
VOLSIZE=200

# Searching for usb drive
external=

# maj:min, LABEL=label, UUID=uuid, PARTLABEL=label, PARTUUID=uuid
usbdevice=UUID=86eb0e3c-c03a-4414-9bfc-f20bef42f2ba
usbname=Backup # The directory name it is automounted under

# Search for a mountpoint - uuid, label, or partition label
if [ -z "$external" ] && [ -n "$usbdevice" ] && command -v findmnt &>/dev/null; then
  external=$(findmnt -nr -o target -S "$usbdevice") || true
fi
# Search by name - automounted (label)
if [ -z "$external" ] && [ -n "$usbname" ]; then
  for dir in "/media/$USER" "/run/media/$USER"; do
    [ -d "$dir/$usbname" ] || continue
    external="$dir/$usbname" && break
  done
fi

if [ -z "$external" ]; then
  printf '%s\n' "Could not find usb drive for backup. Please check that it's mounted." >&2
  exit 1
fi

# The destination directory to backup *to* (usually a remote location or external storage)
DESTINATION_URI=file://$external/duplicity_backup/$host-$os

# Currently only 'no' is fully supported.
ENCRYPTION_TYPE=no

# Perform a full backup if an incremental backup is requested, but the latest full backup in the collection is older than the given time.
FULL_IF_OLDER=15D

# Use seconds as the socket timeout value if duplicity begins to timeout during network operations. The default is 30 seconds.
TIMEOUT=120
# Specify output verbosity level (log level).
# Named levels and corresponding values are 0 Error, 2 Warning, 4 Notice (default), 8 Info, 9 Debug (noisiest).
#          level may also be a character: e, w, n, i, d
#          or a word: error, warning, notice, info, debug
VERBOSITY=4
# Write specially-formatted versions of output messages to the specified file.  The format used is designed to be easily consumable by other programs.
LOGFILE=

# Delete incremental sets of all backups sets that are older than the count:th last full backup (in other words, keep only old full backups and not their increments).
# count must be larger than zero. A value of 1 means that only the single most recent backup chain will be kept intact.
REMOVE_ALL_INC_OF_BUT_N_FULL=3
# Delete all backup sets older than the given time.  Old backup sets will not be deleted if backup sets newer than time depend on them.
# See the TIME FORMATS section for more information.
REMOVE_OLDER_THAN=3M

# When backing up or restoring, this option specifies that the local archive directory is to be created in path.
# If the archive directory is not specified, the default will be to create the archive directory in ~/.cache/duplicity/.
# ARCHIVE_DIR=~/.cache/duplicity/

# Use this existing directory for duplicity temporary files instead of the system default, which is usually the /tmp directory.
# TEMP_DIR=/tmp

# ----------------------------------------------------------------
# ----------------------------------------------------------------
# -------------------------- PROCESSING --------------------------
# ----------------------------------------------------------------
# ----------------------------------------------------------------

THIS="$(basename -- "${BASH_SOURCE[0]}")"
function usage() {
  cat <<EOF || true
Usage: $THIS [opts]...
Run a system backup using duplicity.
Pass --full to specify full backup or --incr to specify incremental backup
If neither argument is passed, a full will be made if the most recent full backup is $FULL_IF_OLDER old

Options:
  --incr           Force a incremental backup
  --full           Force a full backup
  -h, --help       Show this message
  -c, --cleanup    Cleanup old backups
  -i, --info       A synonym for --status
  -n, --dry-run    Do not run any duplicity commands, just show them
  -p, --print      Print information about the backup without querying it
  -s, --status     Get the collection-status
  -v, --verbose    Show all duplicity commands before running them

Environment Variables:
  BACKUP_VERBOSE: causes the script to act as if --verbose was passed
  BACKUP_DRY_RUN: causes the script to act as if --dry-run was passed
  DUPLICITY: The path to the duplicity executable
EOF
}
function log() { printf '%s\n' "$@" || true; }
function err() { printf '%s\n' "$@" >&2 || true; }
function abort() { err "$1" && exit "${2:-1}"; }

# Array of arguments to pass to duplicity
args=()

mode=backup
command=() # an array for the sake of empty strings (allows to skip the command and dynamically create full backups)
for arg in "$@"; do
  case "$arg" in
  --full | --incr) command=("${arg#--}") ;;
  --help | -h) usage && exit 0 ;;
  --print | -p) mode=print ;;
  --cleanup | -c) mode=cleanup ;;
  --info | -i) ;& # fallthrough
  --status | -s) mode=status ;;
  --dry-run | -n) BACKUP_DRY_RUN=1 ;; # overrides environment variables
  --verbose | -v) BACKUP_VERBOSE=1 ;; # overrides environment variables
  --*) abort "Unknown option: '$arg'" ;;
  -*) abort "Unknown option: '$arg'" ;;
  *) abort "this script does not support positional arguments" ;;
  esac
done

DUPLICITY="${DUPLICITY:-"$(command -v duplicity 2>/dev/null || true)"}"
# Ensure duplicity can be accessed
if [ "$mode" != "print" ]; then # This is a special case. We don't want to error out!
  if [ -z "$DUPLICITY" ]; then
    abort "Could not find duplicity. Please ensure it is installed" 1
  elif ! [ -x "$DUPLICITY" ]; then
    abort "Could not run '$DUPLICITY'. Please ensure it is executable." 3
  fi
fi

# include/exclude
for pat in "${files[@]}"; do
  case "$pat" in
  '- '*) args+=("--exclude=${pat#- }") ;; # '- path' -> '--exclude=path'
  -*) args+=("--exclude=${pat#-}") ;;     # '-path' -> '--exclude=path'

  '+ '*) args+=("--include=${pat#+ }") ;; # '+ path' -> '--include=path'
  +*) args+=("--include=${pat#+}") ;;     # '+path' -> '--include=path'

  *) args+=("--include=$pat") ;; # 'path' -> 'include=path'
  esac
done

# exclude-if-present
# check is set and not empty
# note: "${!var[@]}" returns the indicies (ie 0 1 2 3) for the full array
if [ -n "${!exclude_if_present[*]}" ]; then
  for file in "${exclude_if_present[@]}"; do
    args+=("--exclude-if-present=$file")
  done
fi

# volsize
if [ -n "${VOLSIZE:-}" ]; then
  args+=("--volsize=$VOLSIZE")
fi

# Encryption
if [ "${ENCRYPTION_TYPE:-}" = 'no' ]; then
  args+=("--no-encryption")
elif [ -n "${ENCRYPTION_TYPE:-}" ]; then
  # Don't abort here. Try it, but it probably won't work
  err "Warning: Encryption type '${ENCRYPTION_TYPE}' is not supported"
fi

# verbosity
if [ -n "${VERBOSITY:-}" ]; then
  args+=("--verbosity=$VERBOSITY")
fi

# timeout
if [ -n "${TIMEOUT:-}" ]; then
  args+=("--timeout=$TIMEOUT")
fi

# archive-dir
if [ -n "${ARCHIVE_DIR:-}" ]; then
  args+=("--archive-dir=$ARCHIVE_DIR")
fi

# tempdir
if [ -n "${TEMP_DIR:-}" ]; then
  args+=("--tempdir=$TEMP_DIR")
fi

# log-file
if [ -n "${LOGFILE:-}" ]; then
  args+=("--log-file=$LOGFILE")
fi

# name
if [ -n "${NAME:-}" ]; then
  args+=("--name=$NAME")
fi

# ----------------------------------------------------------------
# ----------------------------------------------------------------
# -------------------------- EXECUTION ---------------------------
# ----------------------------------------------------------------
# ----------------------------------------------------------------

function verbose() {
  local verbose=${BACKUP_VERBOSE:-}             # if BACKUP_VERBOSE, be verbose
  [ -z "${BACKUP_DRY_RUN:-}" ] || verbose=1     # if dry-run, be verbose
  [ -z "$verbose" ] || printf "%s\n" "> ${*@Q}" # print it

  [ -z "${BACKUP_DRY_RUN:-}" ] || return 0
  "$@" # run it
}
did_something=0
# Sets did_something and verbosely runs "$@"
function run() {
  did_something=1
  verbose "$@"
}

[ "${#args[@]}" -gt 0 ] || abort "No arguments were specified. Something went wrong" 3

case "$mode" in
backup)
  log ''
  log "--- Backup at $(date) ---"
  log ''

  log "Backing up to $DESTINATION_URI"
  run "$DUPLICITY" --full-if-older-than="${FULL_IF_OLDER:-1M}" "${command[@]}" "${args[@]}" "$SOURCE_DIR" "$DESTINATION_URI"
  ;;
cleanup)
  log "Cleaning up $DESTINATION_URI"
  if [ -n "${REMOVE_OLDER_THAN:-}" ]; then # only if defined
    log "Removing backups older than $REMOVE_OLDER_THAN"
    command=(remove-older-than "$REMOVE_OLDER_THAN" --force)
    run "$DUPLICITY" "${command[@]}" "${args[@]}" "$DESTINATION_URI"
  fi
  if [ -n "${REMOVE_ALL_INC_OF_BUT_N_FULL:-}" ]; then # only if defined
    log
    log "Removing all incremental backups except for $REMOVE_ALL_INC_OF_BUT_N_FULL of full at $DESTINATION_URI"
    command=(remove-all-inc-of-but-n-full "$REMOVE_ALL_INC_OF_BUT_N_FULL" --force)
    run "$DUPLICITY" "${command[@]}" "${args[@]}" "$DESTINATION_URI"
  fi
  ;;
status)
  command=(collection-status)
  run "$DUPLICITY" "${command[@]}" "${args[@]}" "$DESTINATION_URI"
  exit 0 # Don't verify the backup
  ;;
print)
  # Note: Don't change these headers!
  # Note: The format should always be '%s: %s'
  # Note: This should be human readable, but also should be script compatible
  # Note: Parse these with `grep '^Name: ' | sed 's/^Name: \(.*\)/\1/'`
  log "Name: ${NAME:-}"
  log "Backup location: ${DESTINATION_URI:-}"
  log "Source location: ${SOURCE_DIR:-}"
  log "Archive location: ${ARCHIVE_DIR:-}"
  log "Tmp location: ${TEMP_DIR:-}"
  log "Log file: ${LOGFILE:-}"
  log "Duplicity executable: ${DUPLICITY:-}"
  log "Verbosity: ${VERBOSITY:-}"
  log "Encryption type: ${ENCRYPTION_TYPE:-}"
  log "Volume size: ${VOLSIZE:-}"
  log "Full if older than: ${FULL_IF_OLDER:-}"
  log "Timeout: ${TIMEOUT:-}"
  # One option per line
  # This *must* be last beause the number of lines is unknown
  log "Duplicity Options:" "${args[@]}"
  exit 0
  ;;
*) abort "Unknown mode '$mode'. This is most likely a bug." 3 ;;
esac
[ "$did_something" -eq 1 ] || abort "Didn't do anything. Please check your configuration and try again." 2

log
log "Verifying $DESTINATION_URI"
verbose "$DUPLICITY" verify "${args[@]}" "$DESTINATION_URI" "$SOURCE_DIR"
