#!/usr/bin/env bash
set -euC -o pipefail && shopt -s nullglob globstar

BUILD_GRADLE=(build.gradle build.gradle.kts)

function err() { printf '%s\n' "$@" >&2 || true; }
function log() { printf '%s\n' "$@" || true; }
function abort() { err "$1" && exit "${2:-1}"; }

command -v dirname >/dev/null 2>&1 || abort "dirname is not installed." 127
search_upwards() {
  local dir="$1" names=("${@:2}")
  local name
  while [ "$dir" != "/" ]; do
    for name in "${names[@]}"; do
      [ -e "${dir}/$name" ] || continue
      printf '%s\n' "$dir/$name"
      return 0
    done
    dir=$(dirname -- "$dir")
  done
  return 1
}

dir=$(pwd)
if [ -x "$dir/gradlew" ]; then
  log "Found a gradlew wrapper script in the current directory."
  gradlew="$dir/gradlew"
  cd -- "$(dirname -- "$gradlew")"
  exec -- "$gradlew" "$@"
fi

build_gradle=$(search_upwards "$dir" "${BUILD_GRADLE[@]}") || abort "Unable to find a ${BUILD_GRADLE[0]} in any parent directory."
dir=$(dirname -- "$build_gradle") # search from build.gradle's location
{ gradlew=$(search_upwards "$dir" "gradlew") && [ -x "$gradlew" ]; } || abort "Unable to find an executable gradlew in any parent directory."

gradle_type="wrapper"
# Select the right gradle or error out if no good options exist.
if [ -z "$gradlew" ]; then
  gradle_type="executable"
  # Find the system gradle executable to fall back on.
  gradlew=$(command -v gradle 2>/dev/null) || abort "Unable to find a gradlew or gradle."
  log "There is no gradlew set up for this project. You may want to consider setting one up."
  log "See: http://gradle.org/docs/current/userguide/gradle_wrapper.html"
fi

# Say what we are gonna do, then do it.
log "Using gradle ${gradle_type} at ${gradlew@Q} to run ${build_gradle@Q}:"
log ''
cd -- "$(dirname -- "$build_gradle")"
exec -- "$gradlew" "$@"
