#!/usr/bin/env bash
set -eu

THIS='executables'

usage() {
  cat <<EOF
Usage: $THIS
Lists executables present in \$PATH

OPTIONS:
  -h, --help      display this help message
  -p, --path      <path> use <path> instead of \$PATH
EOF
  return 0
}
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() {
  err "$1"
  exit "${2:-1}"
}
# Returns a string that should be 'eval'ed to set the positional arguments
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  # -allow a command to fail with !’s side effect on errexit
  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
  # shellcheck disable=SC2251
  ! getopt --test >/dev/null
  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi

  local parsed
  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
    # output getopt’s output this way to handle the quoting right:
    printf '%s' "set -- $parsed"
    return 0
  fi
  # getopt has already complained about wrong arguments to stdout - Exit script
  exit 2
}

path=$PATH
LONGOPTS=help,path: SHORTOPTS=h,p:
ARGSTRING="$(parse_args "$@")"
eval "$ARGSTRING"

while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  -p | --path) path="$2" && shift 2 ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

get_execs() {
  local d f path dirs=()
  path="${1:-$PATH}"
  if ! [[ $path = *: ]]; then path="$path:"; fi
  readarray -d ':' -t dirs <<<"$path"
  for d in "${dirs[@]}"; do
    [ -z "$d" ] && d=.
    for f in "$d"/.[!.]* "$d"/..?* "$d"/*; do
      if [ -f "$f" ] && [ -x "$f" ]; then
        log "${f##*/}"
      fi
    done
  done
}

get_execs "$path" | sort | uniq
