#!/usr/bin/env bash
#
# This file echoes a bunch of color codes to the
# terminal to demonstrate what's available.  Each
# line is the color code of one forground color,
# out of 17 (default + 16 escapes), followed by a
# test use of that color on all nine background
# colors (default + 8 escapes).
#
set -euC -o pipefail

## UTILS ##################################
THIS='logind-run'
usage() {

  cat <<EOF
$THIS [-h] TTY -- COMMAND [ARGUMENTS]...
Runs a COMMAND on TTY with a new logind session

OPTIONS:
  -h, --help      display this help message
EOF
  return 0
}
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() {
  err "$1"
  exit "${2:-1}"
}
# use like '$sudo do_something' - could break with SUDO="something with spaces"
sudo=
if [ "$(id -u)" -ne 0 ]; then
  sudo="${SUDO:-sudo}"
fi

for arg; do
  case "$arg" in
  --help | -h) usage && exit 0 ;;
  --) break ;;
  esac
done

if [ "$#" -lt 1 ]; then
  abort 'tty must be specified' 2
elif [ -z "${2:-}" ]; then
  abort 'command must be specified' 2
fi

ttynum=${1-34}
# permit /dev/tty2 to work
case "$ttynum" in
/dev/tty*) ttynum=${ttynum#/dev/tty} ;;
esac

re='^[0-9]+$'
if [ -z "$ttynum" ]; then
  abort "tty can't be empty" 2
elif ! [[ "$ttynum" =~ $re ]]; then
  abort 'tty must be a number' 2
elif ! [ -c "/dev/tty$ttynum" ]; then # Character special file
  abort "tty must be a file in /dev/tty*" 2
fi

if pgrep 'tty' -t "tty$ttynum" &>/dev/null; then
  abort "It seems like this tty is in use. Please try a different tty" 1
fi

exec $sudo env "PATH=$PATH" systemd-run \
  --property PAMName=login \
  --property User="$USER" \
  --property StandardInput=tty \
  --property TTYPath=/dev/tty"$ttynum" \
  "${@:2}"
