#!/usr/bin/env bash
set -euC -o pipefail
source_path=~/code/repos/neovim
nvim="$source_path/build/bin/nvim"

if [ -x "$nvim" ]; then
  # echo "Running git version!"
  export VIMRUNTIME="$source_path/runtime/"
  exec -- "$nvim" "$@"
fi

tar_path=~/.local/neovim
nvim="$tar_path/bin/nvim"

if [ -x "$nvim" ]; then
  # echo "Running tar version!"
  exec -- "$nvim" "$@"
fi

function find_in_path() {
  local path cmd exclude="${2:-${BASH_SOURCE[0]}}"
  cmd=${1%/} cmd="${1##*/}" # remove trailing slash -- then get basename
  while read -r -d: path; do
    path=${path:-$PWD}                         # empty path means pwd
    [ "$path/$cmd" != "$exclude" ] || continue # skip this_file
    [ -x "$path/$cmd" ] || continue
    printf '%s' "$path/$cmd" || true
    return 0
  done < <(printf '%s' "$PATH:")
  printf '%s\n' "$cmd: command not found" >&2 || true
  return 127
}

nvim="$(find_in_path nvim)" || exit
exec -- "$nvim" "$@" || exit
