#! /usr/bin/env bash

# ~/.local/bin/contents
#
# Read the contents of a file or executable
# *Follows Symlinks*
#
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils" || exit

function usage() {
  cat <<EOF
Usage: $THIS [file|executable...]
Outputs the contents of a file using \$PAGER, calls \`command -v\` if file is not found

Options:
  -P, --no-pager      Don't attempt to open the files using a pager (\$PAGER)
  -p, --pager=PAGER   Use <PAGER> instead of \$PAGER
  -e, --edit          Open the file in \$EDITOR instead of outputting the contents
EOF
  return 0
}
LONGOPTS=help,no-pager,pager:,edit SHORTOPTS=h,P,p:,e
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit
pager=true edit=0
while true; do
  case "$1" in
  -h | --help) usage && exit 0 ;;
  -P | --no-pager) pager=false && shift ;;
  -p | --pager) pager=$2 && shift 2 ;;
  -e | --edit) edit=1 && shift ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done
[ "$#" -gt 0 ] || abort 'FILE is required' 2

files=()
declare -i exit_code=0
for file in "$@"; do
  if [ -f "$file" ]; then files+=("$file") && continue; fi # Given a path
  whichfile=$(cmdpath "$file" 2>/dev/null) || true
  if [ -f "$whichfile" ]; then files+=("$whichfile") && continue; fi # given a name

  err "$file is not a file" # couldn't find
  exit_code=1
done
[ "${#files[@]}" -gt 0 ] || exit "$exit_code" # we couldn't find any of them

open=
case "$edit" in
0)
  # Use pager if can, else use cat
  if [ "$pager" = false ] || ! [ -t 1 ]; then
    PAGER=$(first_cmd cat /bin/cat) || abort "Could not find pager" 1
  elif [ "$pager" = true ]; then
    PAGER=${PAGER:-$(first_cmd pager bat less cat /bin/cat)} || abort "Could not find pager" 1
  elif [ "$pager" != true ]; then
    PAGER="$pager"
  fi
  open="${PAGER:-cat}"
  ;;
1) open=${EDITOR:-$(first_cmd editor sensible-editor vim emacs /bin/cat)} || abort "Could not find editor" 1 ;;
esac

# output them all -- open is expanded to allow flags
$open -- "${files[@]}" || exit
exit "$exit_code"
