#!/usr/bin/env bash

# An additional factor (on intel chips) which can improve performance/battery life is the EPB.
# This progam doesn't set it (as it is exclusive to intel), but you may consider setting it
# if you are looking to squeeze the last bit of performance or battery life from your intel cpu.
#
# From the Arch Wiki: https://wiki.archlinux.org/title/CPU_frequency_scaling#Intel_performance_and_energy_bias_hint
#
# The Intel performance and energy bias hint (EPB) is an interface provided by Intel CPUs
# to allow for user space to specify the desired power-performance tradeoff, on a scale
# of 0 (highest performance) to 15 (highest energy savings). The EPB register is another
# layer of performance management functioning independently from frequency scaling. It
# influences how aggressive P-state and C-state selection will be, and informs internal
# model-specific decision making that affects energy consumption.
#
# Common values and their aliases, as recognized by sysfs and x86_energy_perf_policy are:
#
# EPB = String
#
# 0   = performance
# 4   = balance-performance
# 6   = normal, default
# 8   = balance-power
# 15  = power

# echo epb | tee /sys/devices/system/cpu/cpu*/power/energy_perf_bias

set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"

function usage() {
  cat <<EOF || true
Usage: $THIS [OPTS]... [newmode]
Sets the kernal power saving/performance mode
Call without arguments to show the current and available modes
in a human-readable format.

Options:
  -h, --help         Show this help message.
  -a, --available    Show only the available modes. (incompatible with -c)
  -c, --current      Show only the current selected mode. (incompatible with -a)
  -q, --quiet        Don't output non-esential information on stdout.

Exit code:
  0 on success
  1 on miscellaneous errors
  2 on usage error
  3 on unsupported kernal
  4 on setting nonexistent mode.
EOF
}

quiet=0
function is_quiet() { [ "$quiet" -eq 1 ]; }
LONGOPTS=help,available,current,handle-completion-options,quiet SHORTOPTS=h,a,c,q
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

print_only=''
while true; do
  case "$1" in
  -h | --help) usage && exit 0 ;;
  -q | --quiet) quiet=1 && shift ;;
  -a | --available)
    [ -z "$print_only" ] || abort "--available and --current are mutually exclusive" 2
    print_only=available && shift
    ;;
  -c | --current)
    [ -z "$print_only" ] || abort "--available and --current are mutually exclusive" 2
    print_only=current && shift
    ;;
  --handle-completion-options) # note: no short option!
    # Remove the current option (the completion handling)
    # Remove double commas, remove trailing commas, remove leading commas
    LONGOPTS=${LONGOPTS/${1#--}/} LONGOPTS=${LONGOPTS/,,/} LONGOPTS=${LONGOPTS%,} LONGOPTS=${LONGOPTS#,}
    printf '%s\n' "--${LONGOPTS//,/ --} -${SHORTOPTS//,/ -}"
    exit 0
    ;;
  --) shift && break ;;
  *) abort "This is a bug" 1 ;;
  esac
done

# Hard coded to cpu0, it should be fine.
AVAIL_PATH=/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
PATHS=(/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor)
CURRENT_PATH=${PATHS[0]:-}
if ! [ -f "$AVAIL_PATH" ] || ! [ -f "$CURRENT_PATH" ]; then
  abort 'Please make sure your kernal supports scaling governors' 3
fi

function show_output() {
  local current
  current="$(cat "$CURRENT_PATH")"
  case "$print_only" in
  '')
    if is_quiet; then
      printf '%s\n' "$current" || true
    else
      log "available options: $avail_options"
      log "currently selected: $current"
    fi
    ;;
  'available') printf '%s\n' "$avail_options" || true ;;
  'current') printf '%s\n' "$current" || true ;;
  esac
}

function set_mode() {
  mode=$1
  case " $avail_options " in
  *" $mode "*) is_quiet || log "Setting mode: $mode" ;; # no log on quiet
  *) abort "'$mode' is not an available mode." 4 ;;     # call without args to check available
  esac
  printf '%s' "$mode" | sudo_cmd tee "${PATHS[@]}" >/dev/null
}

avail_options=$(cat "$AVAIL_PATH")
case "$#" in
0) show_output ;;
1) set_mode "$1" ;;
*) abort 'Too many arguments.' 2 ;;
esac
