#!/usr/bin/env bash

set -euC -o pipefail

THIS="brightness"

usage() {
  cat <<-EOF
usage: $THIS [OPTS]... [percent]
       $THIS [OPTS]... [-s | show]
Sets the brightness to the specified integer percentage.

In the first form, sets the brightness to the given percentage.
In the second form, outputs the current brightness percentage to stdout.

Options:
  -h, --help         Show this help message.
  -s, --show         output the current brightness percentage.
  -d, --device=dev   the /sys style device to set the brightness on. \$device/brightness will be writen to!
EOF
}

log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  # -allow a command to fail with !’s side effect on errexit
  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
  # shellcheck disable=SC2251
  ! getopt --test >/dev/null
  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi

  local parsed
  if parsed="$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@")"; then
    # output getopt’s output this way to handle the quoting right:
    printf '%s' "set -- $parsed"
    return 0
  fi
  # getopt has already complained about wrong arguments to stdout - Exit script
  exit 2
}

show="false"
LONGOPTS="help,show,device:" SHORTOPTS="h,s,d:"
ARGSTRING="$(parse_args "$@")"
eval "$ARGSTRING"

device=''
while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  -s | --show) show="true" && shift ;;
  -d | --device) device="$2" && shift 2 ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done
if [ "${1:-}" = "show" ] || [ "$#" -eq 0 ]; then show="true"; fi

BrPath="$device"
if [ -z "$BrPath" ]; then
  BrPath="$(find /sys/class/backlight -maxdepth 1 -mindepth 1 -print0 | head -zn1 | tr -d '\0')"
fi

if [ -z "$BrPath" ]; then
  abort "Unable to find backlight device" 1
elif ! [ -d "$BrPath" ]; then
  abort "Found backlight device is not a directory" 1
elif ! [ -f "$BrPath/max_brightness" ]; then
  abort "Backlight device must support /max_brightness" 1
elif ! [ -f "$BrPath/brightness" ]; then
  abort "Backlight device must support /brightness" 1
fi

declare -i BrMax BrMin BrCur
BrMax="$(<"$BrPath/max_brightness")"
# 100th max-brightness, rounded up to nearest integer
BrMin="$((0 + (BrMax + 100 - 1) / 100))"
BrCur="$(<"$BrPath/brightness")"
if [ "$BrMax" -eq 0 ]; then abort "Backlight device reported maximum brightness of 0." 1; fi

BrCurRel="$(printf '%s ' "$BrCur" "$BrMax" | awk '{ print int( $1 / $2 * 100 ) }')"

if [ "$show" = true ]; then
  log "$BrCurRel"
  exit 0
fi

BrNewRel="${1:-}"
number_re='^[0-9]+$'
if [ -z "$BrNewRel" ]; then abort "Brightness can't be empty"; fi
if ! [[ "$BrNewRel" =~ $number_re ]]; then
  abort "Invalid brightness '$BrNewRel', brightness must be an integer between 0 and 100" 2
fi

BrNew="$(printf '%s ' "$BrNewRel" "$BrMax" | awk '{ print int( ( ($1/100) * $2) ) }')"
BrNew="$((BrNew < BrMin ? BrMin : BrNew))"
BrNew="$((BrNew > BrMax ? BrMax : BrNew))"

sudo=""
if ! [ -w "$BrPath"/brightness ]; then sudo="sudo"; fi

printf '%s' "$BrNew" | $sudo tee "$BrPath/brightness" >/dev/null
