#!/usr/bin/env bash
set -euC -o pipefail

THIS=rmgit
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }

declare -i VERBOSE=0 YES=0 FORCE=0

function usage() {
  cat <<-EOF
	Usage: $THIS [OPTS] REPO...

	Options:
		-v, --verbose  verbose output
		-h, --help     show this help message
		-y, --yes      don't confirm deletion of REPO
		-f, --force    force deletion of REPO. REPO/.git is always force deleted.
  The following options are ignored for rm compatibility:
    -r, --recursive
    -i, --interactive
EOF
  return 0
}

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  # -allow a command to fail with !’s side effect on errexit
  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
  # shellcheck disable=SC2251
  ! getopt --test >/dev/null
  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi

  local parsed
  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@"); then
    # output getopt’s output this way to handle the quoting right:
    printf '%s' "set -- $parsed"
    return 0
  fi
  # getopt has already complained about wrong arguments to stdout - Exit script
  exit 2
}

LONGOPTS=help,verbose,yes,force,interactive,recursive
SHORTOPTS=h,v,y,f,i,r
ARGSTRING="$(parse_args "$@")"
eval "$ARGSTRING"

for arg in "$@"; do
  case "$arg" in
  -h | --help) usage && exit 0 ;;
  -v | --verbose) VERBOSE=1 && shift ;;
  -y | --yes) YES=1 && shift ;;
  -f | --force) FORCE=1 YES=1 && shift ;;
  -i | --interactive) ;& -r | --recursive) shift ;;
  --) shift && break ;;
  *) abort 'This is a bug' 3 ;;
  esac
done

if [ "$#" -eq 0 ]; then abort "missing operand" 2; fi

# usage: check_status repo
# returns success if the repo is clean
function check_status() (
  if [ -n "$(git -C "$1" status --porcelain)" ]; then
    return 1
  fi
  return 0
)

exit=0
for repo in "$@"; do
  if [ -z "$repo" ]; then
    err "Refusing to remove empty string. (repo is required)"
    exit=2 && continue
  fi

  if ! [ -d "$repo" ] || ! [ -d "$repo"/.git ]; then
    err "$repo is not a git repository"
    exit=1 && continue
  fi

  if [ "$YES" -ne 1 ]; then
    read -rep "$THIS: remove git repository '$repo'? " confirmation
    if ! [[ "${confirmation,,}" =~ ^\s*y(es)?\s*$ ]]; then exit 1; fi
  fi

  if ! check_status "$repo"; then
    err "Refusing to remove dirty repo $repo"
    exit=1 && continue
  fi

  base_args=(--recursive)
  if [ "$FORCE" -eq 1 ]; then base_args+=(--force); fi
  if [ "$VERBOSE" -eq 1 ]; then base_args+=(--verbose); fi

  # Force rm .git
  args=(--force "${base_args[@]}" -- "$repo/.git")
  if [ "$VERBOSE" -eq 1 ]; then log "rm ${args[*]}"; fi
  rm "${args[@]}"

  args=("${base_args[@]}" -- "$repo/")
  if [ "$VERBOSE" -eq 1 ]; then log "rm ${args[*]}"; fi
  rm "${args[@]}"
done

exit "$exit"
