#!/usr/bin/env bash

# ~/.local/bin/post-temp
#
# Hosts a temporary file on the internet for 60 mins and echos the url.
#
#
set -euC -o pipefail

THIS='post-temp'
temp_source=https://tmpfiles.org/api/v1/upload

usage() {

  cat <<EOF
Usage: $THIS [OPTION...] [--] FILE...
Hosts a temporary file on the internet for 60 mins and outputs the url.

OPTIONS:
  -h, --help       display this help message
  -v, --verbose    display verbose messages
  -q, --quiet      be quieter
  -t, --temp=url   use url to upload files (POST) (default: $temp_source)
EOF
  return 0
}
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  # -allow a command to fail with !’s side effect on errexit
  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
  # shellcheck disable=SC2251
  ! getopt --test >/dev/null
  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi

  local parsed
  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
    # output getopt’s output this way to handle the quoting right:
    printf '%s' "set -- $parsed"
    return 0
  fi
  # getopt has already complained about wrong arguments to stdout - Exit script
  exit 2
}

# Usage if no args are passed
if [ "$#" -eq 0 ]; then usage && exit 0; fi

verbose=false quiet=false
LONGOPTS=help,short,long:
SHORTOPTS=h,s,l:
ARGSTRING="$(parse_args "$@")"
eval "$ARGSTRING"

while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --) shift && break ;;
  -v | --verbose) verbose=true && shift ;; # Verbose option
  -q | --quiet) quiet=true && shift ;;     # Quiet option
  -t | --temp) temp_source="$2" && shift 2 ;;
  *) abort "This is a bug" 3 ;;
  esac
done

# Error if args given, but no files given
if [ "$#" -eq 0 ]; then abort "FILE is required!" 2; fi

fx=$(which fx 2>/dev/null || printf '')
if [ -z "$fx" ] && [ "$quiet" != "true" ]; then err "This script works much better with 'fx' installed."; fi

declare -i exitcode=0

for file in "$@"; do
  if ! [[ -f "$file" ]]; then
    err "'$file' is not a file"
    exitcode=2 && continue
  fi

  result="$(curl -sSfL -F "file=@$file" "$temp_source")" ||
    abort 'Something went wrong during curl command. Aborting.' 1 # exits program
  # Example outputs:
  # {"message": "server error"}
  # {"status":"success","data":{"url":"https://tmpfiles.org/######/file"}}

  # If verbose, or fx not installed, print entire json
  if [ "$verbose" = true ] || [ -z "$fx" ]; then
    log "$result"
    [ -z "$fx" ] && continue # Stops loop here because fx is not installed
  fi

  # Print the result thru fx to get the data
  # Already strings, if present, but trying to error
  status="$("$fx" '.status.toString()' <<<"$result" 2>/dev/null)"
  url="$("$fx" '.data.url.toString()' <<<"$result" 2>/dev/null)"

  if [ -z "$status" ] || [ -z "$url" ]; then
    message="$("$fx" '.message.toString()' <<<"$result" 2>/dev/null)"
    if [ -n "$message" ]; then err "$message"; else err "An unknown error occured"; fi
    exitcode=1
  else
    [ "$quiet" != true ] && log "$status"
    log "${url/tmpfiles.org\//tmpfiles.org\/dl\/}"
  fi
done

exit "$exitcode"
