#!/usr/bin/env bash
set -euC -o pipefail
# Find the current file and it's directory
# Source: https://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]:-}" DIR=''
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$(builtin cd -P -- "$(command dirname -- "$SOURCE")" &>/dev/null && builtin pwd)" || true
  SOURCE="$(command readlink -- "$SOURCE")" || true
  [[ "$SOURCE" == /* ]] || SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$(builtin cd -P -- "$(command dirname -- "$SOURCE")" &>/dev/null && builtin pwd)" || true
DIR="${DIR:-"$PWD"}"
utils="$DIR/script_utils.sh"
[ -f "$utils" ] || utils="$(basename -- "$utils")" || true # If utils is not a file, search for it in "$PATH" instead.
# shellcheck source=./script_utils.sh
. "$utils"             # Note: this may error. I can't use it in a conditional or bashls fails.
[ "$?" -eq 0 ] || exit # set -e means that this line should be irrelevant, but just in case.

# Outputs the most $2 recently modified files in directory $1
# Relies on GNU find!
get_latest() {
  local dir="${1:-.}" num=${2:-1}
  find "$dir" -mindepth 1 -maxdepth 1 -printf "%T@ %p\n" | sort -n | cut -d' ' -f 2- | tail -n "$num"
}

THIS="${BASH_SOURCE[0]##*/}"
usage() {
  cat <<-EOF || true
usage: $THIS [opts]... [--] [DEST]
Manipulate the most recently downloaded (modified) file

Options:
  -h, --help         Show this help message.
  -r, --remove       Remove the most recently downloaded file (incompatable with -c or -p)
  -c, --copy         Copy the most recently downloaded file to DEST (incompatable with -r or -p)
  -p, --print        Print the most recently downloaded file (incompatable with -r or -p)
  -n, --num=n        Operate on the nth most recent file, instead of the first
EOF
}

LONGOPTS="help,remove,copy,print,num:" SHORTOPTS="h,r,c,p,n:"
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

do=copy num=1 # 1=most recent
while true; do
  case "$1" in
  -h | --help) usage && exit 0 ;;
  -r | --remove) do=remove && shift ;;
  -c | --copy) do=copy && shift ;; # default
  -p | --print) do=print && shift ;;
  -n | --num)
    num="$2" && shift 2
    case "$num" in *[!0-9]* | '') abort "Invalid number: $num" 2 ;; esac
    ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done
dest=${1:-.}
downloads=$(get_xdg_dir "DOWNLOAD") || true
downloads="${downloads:-~/Downloads/}" # We still haven't found something? use ~/Downloads/

file="$(get_latest "$downloads" "$num" | head -n 1)"
case "$do" in
remove)
  log "Removing '$file'"
  rm -i -r -- "$file"
  ;;
copy)
  log "Copying '$file' to '$dest'"
  # cp -Pp -R is posix for cp --archive
  cp -pP -R -i -- "$file" "$dest"
  ;;
print) printf '%s\n' "$file" ;;
esac
