#! /usr/bin/env bash

# ~/.local/bin/contents
#
# Read the contents of a file or executable
# *Follows Symlinks*
#
set -euC -o pipefail
THIS=contents
usage() {
  cat <<EOF
$THIS [file|executable...]
                  
outputs the contents of a file using \$PAGER, calls which if file is not found
options:
-P, --no-pager      Don't attempt to open the files using a pager (\$PAGER)
-p, --pager=PAGER   Use <PAGER> instead of \$PAGER
-e, --edit          Open the file in \$EDITOR instead of outputting the contents
EOF
  return 0
}
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  # -allow a command to fail with !’s side effect on errexit
  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
  # shellcheck disable=SC2251
  ! getopt --test >/dev/null
  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi

  local parsed
  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@"); then
    # output getopt’s output this way to handle the quoting right:
    printf '%s' "set -- $parsed"
    return 0
  fi
  # getopt has already complained about wrong arguments to stdout - Exit script
  exit 2
}

pager=true edit=0
LONGOPTS=help,no-pager,pager:,edit SHORTOPTS=h,P,p:,e
ARGSTRING="$(parse_args "$@")"
eval "$ARGSTRING"
while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --no-pager | -P) pager=false && shift ;;
  -p | --pager) pager=$2 && shift 2 ;;
  -e | --edit) edit=1 && shift ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

if [ "$#" -eq 0 ]; then
  abort 'FILE is required' 2
fi

files=()
for file in "$@"; do
  # Given a path
  if [ -f "$file" ]; then
    files+=("$file")
    continue
  fi

  if ! command -v which &>/dev/null; then
    abort 'Which is required to search PATH for files' 2
  fi
  # given a name
  whichfile=$(which "$file" 2>/dev/null)
  if [ -f "$whichfile" ]; then
    files+=("$whichfile")
    continue
  fi

  # couldn't find
  err "$file is not a file"
  continue
done

find_prog() {
  for p in "$@"; do
    if { [ -f "$p" ] && [ -x "$p" ]; } || [ -x "$(which -- "$1" 2>/dev/null)" ]; then
      printf '%s' "$p"
      return 0
    fi
  done
  return 1
}

open=
case "$edit" in
0)
  # Use pager if can, else use cat
  if [ "$pager" = true ] && [ -t 1 ]; then
    PAGER=${PAGER:-$(find_prog pager cat /bin/cat)}
  elif [ "$pager" = false ]; then
    PAGER=$(find_prog cat /bin/cat)
  elif [ "$pager" != true ]; then
    PAGER="$pager"
  fi
  open="${PAGER:-cat}"
  ;;
1) open=${EDITOR:-$(find_prog editor sensible-editor vim emacs /bin/cat)} ;;
esac

# output them all -- open is expanded to allow flags
exec $open -- "${files[@]}"
