#!/usr/bin/env bash
# Literally count the number of files in the current directory

set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"

# by default, show all types
declare -A show_types=([dotfile]=1)
for key in "${!FILE_TYPES[@]}"; do show_types[$key]=1; done

usage() {
  cat <<EOF || true
Usage: $THIS [opts] [--] [DIR]
Output the number of files in DIR or the current directory on standard output.

Options:
  -h, --help            show this message
  -v, --verbose         output verbose messages
  -e, --exclude=types   exclude colon seperated types from the count (incompatible with -i)
  -i, --include=types   include only colon seperated  types in the count (incompatible with -e)

valid types are: $(join ', ' "${!show_types[@]}")
note: if using --include, and you expect dotfiles to be shown, you must specify dotfile
EOF
}

LONGOPTS="help,include:,exclude:,verbose" SHORTOPTS="h,i:,e:,v"
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

verbose=0 # by default show only number of files
while true; do
  case "$1" in
  -h | --help) usage && exit 0 ;;
  -e | --exclude)
    types=() && split types : "$2" && shift 2
    for t in "${types[@]}"; do
      [ -n "$t" ] || continue # ignore empty elements
      [ -n "${show_types["$t"]:-}" ] || abort "Unknown type: $t" 2
      show_types["$t"]=0
    done
    ;;
  -i | --include)
    for key in "${!show_types[@]}"; do show_types[$key]=0; done # set all others to not count
    types=() && split types : "$2" && shift 2
    for t in "${types[@]}"; do
      [ -n "$t" ] || continue # ignore empty elements
      [ -n "${show_types["$t"]:-}" ] || abort "Unknown type: $t" 2
      show_types["$t"]=1
    done
    ;;
  -v | --verbose) verbose=1 && shift ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done
# First arg, or current directory
[ $# -gt 0 ] || set -- .

shopt -s dotglob
[ "${show_types[dotfile]}" -eq 1 ] || shopt -u dotglob # user has specified not to show dotfiles

unset "show_types[dotfile]" # we already handled dotfile
# PERF: Calculate these once, since they can't change
show_all=1 show_any=0 &&
  for val in "${show_types[@]}"; do
    case "$val" in
    1) show_any=1 ;; 0) show_all=0 ;;
    esac
  done
_file_count() {
  # PERF: No need to calculate, since nothing will be returned
  if [ "$show_any" -eq 0 ]; then
    printf '%s\n' 0 || true
    return 0
  fi

  local files=("$1"/*)
  # PERF: if all files are counted, don't fetch the file type
  if [ "$show_all" -eq 1 ]; then
    printf '%s\n' "${#files[@]}" || true
    return 0
  fi

  count=0
  for file in "${files[@]}"; do
    type=$(file_type "$file" -s) || continue
    [ "${show_types["$type"]}" -ne 1 ] || count=$((count + 1))
  done
  printf '%s\n' "$count" || true
}

for dir in "$@"; do
  [ -d "$dir" ] || abort "$dir is not a directory" 1
  declare -i count=0
  count=$(_file_count "$dir")
  case "$verbose" in
  0) log "$count" ;;
  *) log "$dir: $count" ;;
  esac
done
