#!/usr/bin/env bash
set -euC -o pipefail
log() { printf '%s\n' "$@"; }
err() { printf '%s\n' "$@" 1>&2; }
abort() {
  err "$1"
  exit "${2:-1}"
}
has() { command -v -- "$1" &>/dev/null; }
# shellcheck disable=SC2206 # split intentionally
SUDO=(${SUDO:-sudo})
sudo_cmd() { "${SUDO[@]}" "$@"; }

# Get size before starting

oldsize_root=$(df / | tail -n +2 | awk '{print $3}')
if [ "$(findmnt /)" = "$(findmnt ~)" ]; then
  oldsize="$oldsize_root"
else
  oldsize_home=$(df ~ | tail -n +2 | awk '{print $3}')
  oldsize=$((oldsize_root + oldsize_home))
fi

# Start doing things

if has pnpm; then
  log "Cleaning pnpm store"
  pnpm store prune
fi

log "Cleaning browser cache"
clean-google-cache

if has snap; then
  log "Cleaning up snap packages"
  snap-cleanup
fi

log "Cleaning package manager cache"
if has nala; then
  sudo_cmd nala clean
elif has apt; then
  sudo_cmd apt-get clean
  sudo_cmd apt-get autoclean
elif has yay; then
  yay -Sc
elif has pacman; then
  sudo_cmd pacman -Sc
else
  err "Could not find a package manager to clean up"
fi

if has flatpak; then
  log "Repairing flatpak repo"
  sudo_cmd flatpak repair
fi

log "Cleaning up cache files"
rm -rf -- ~/.cache/node/corepack/
rmdir --ignore-fail-on-non-empty -- ~/.cache/node/
rm -rf -- ~/.cache/npm/
rm -rf -- ~/.cache/yarn
rm -rf -- ~/.cache/gnome-desktop-thumbnailer/
rm -rf -- ~/.cache/mesa_shader_cache/

log "Cleaning the trash"
if has trash-empty; then
  trash-empty
elif has gio; then
  gio trash --empty
else
  abort "Could not find a command to clean the trash"
fi

log "Running TRIM on mounted partitions"
sudo_cmd fstrim -av

# Size stats
log "Cleaning old logs >1G"
sudo journalctl --vacuum-size=1G

newsize_root=$(df / | tail -n +2 | awk '{print $3}')
if [ "$(findmnt /)" = "$(findmnt ~)" ]; then
  newsize="$newsize_root"
else
  newsize_home=$(df ~ | tail -n +2 | awk '{print $3}')
  newsize=$((newsize_root + newsize_home))
fi

saving=$((oldsize - newsize))
if command -v numfmt &>/dev/null; then # After this point, don't use any of these variables for math!!
  oldsize=$(numfmt --to=si -- "$oldsize")
  newsize=$(numfmt --to=si -- "$newsize")
  saving=$(numfmt --to=si -- "$saving")
fi

log "Old size: $oldsize"
log "New size: $newsize"
log "Total saving: $saving"
