#!/usr/bin/env bash
# usage: fullscreen [Search-Term]
THIS=fullscreen
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }
usage() {
  command cat <<EOF
$THIS [SEARCH] [xdotool-args]

if run without arguments, uses selectwindow to request a window,
else searches window class, name, and classname for SEARCH. When
A window is found, it is maximized and moved to the top left corner.
Use DISPLAY=:dsp fullscreen to control other screens

xdotool-args are commands for xdotool that are prepended to the
windowsize command. Use {id} to mean the specified window id.

Options:
-h, --help              Show this help message
-d, --display=display   Set the display to use (default $DISPLAY)
EOF
  return 0
}
set -ue
nextdisplay=false end=false
args=() display=${DISPLAY:-}
for arg; do
  if [ "$end" = true ]; then
    args+=("$arg")
  elif [ "$nextdisplay" = true ]; then
    display="$arg"
    nextdisplay=false
  else
    case "$arg" in
    --help | -h) usage && return 0 ;;
    -d | --display) nextdisplay=true ;;
    --display=*) display="${arg#--display=}" ;;
    --) end=true ;;
    *) args+=("$arg") ;;
    esac
  fi
done

classname="${args[0]:-}"
if [ -z "$classname" ]; then
  find=(selectwindow)
else
  find=(search --name --class --classname -- "$classname")
fi
id=$(DISPLAY="$display" xdotool "${find[@]}") || abort "Could not find window on display: '${display:-NONE}'"

userargs=()
# Replace {id} with the id in the user string
for arg in "${args[@]:2}"; do userargs+=("${arg//\{id\}/$id}"); done

DISPLAY="$display" xdotool "${userargs[@]}" windowsize "$id" 100% 100% windowmove "$id" 0 0
