#!/usr/bin/env sh
# Literally count the number of files in the current directory
THIS=$(basename -- "${0:-}")
usage() {
  cat || true <<EOF
Usage: $THIS [opts]... [DIR]
Output the number of files in DIR or the current directory on standard output.

Options:
  --help, -h   show this message
EOF
}
for arg; do
  case "$arg" in
  --help | -h) usage && exit 0 ;;
  esac
done
# First arg, or current directory
dir="${1:-.}"
find "$dir" -mindepth 1 -maxdepth 1 -printf '.' | exec wc -c
