#!/usr/bin/env bash
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"

export LANG=en_US.UTF-8 # Set English language
USE_COLOR=1             # Output color when using `log`, `err`, etc

if [ "$(id -u)" -ne 0 ]; then abort "This program must be run as root" 1; fi

function usage() {
  cat <<EOF || true
Usage: $THIS [options] [--] [arguments]
Cleans up the excess snap revisions and files. 

Options:
  -h, --help        show this message
  -y, --yes         Don't ask for confirmation
EOF
}

LONGOPTS=help,yes SHORTOPTS=h,y
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

yes=0
while true; do
  case "$1" in
  -h | --help) usage && exit 0 ;;
  -y | --yes) yes=1 && shift ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

# Current status
used_before="$(df -k / | awk 'NR>1 {print $3}')"

has_cmd snap || abort "snap command not found" 1

[ "$yes" -eq 1 ] || confirm "Do you want to remove unused snapd revisions?" || abort "aborting" 1

# remove unused snapd revisions
log "Removing unused snapd revisions..."
snap set system refresh.retain=2
snap list --all | awk '/disabled/ {print $1, $3}' |
  while read -r SNAP_NAME SNAP_REV; do
    snap remove "${SNAP_NAME}" --revision="${SNAP_REV}"
  done
for file in /var/lib/snapd/cache/*; do rm "$file"; done

# Current status
used_after="$(df -k / | awk 'NR>1 {print $3}')"

# Summary
log "Freed up space: $(((used_before - used_after) / 1024)) MB"
