#!/usr/bin/env bash
# don't match -> empty string. Include dotfiles. Allow double star
shopt -s nullglob dotglob extglob
set -euC -o pipefail

template_parent_dir="$HOME/code"
usage() {

  cat <<EOF
Usage: $THIS [LANG] [--] <DIR>...
Creates a new project in the given language, based on the template found at $template_parent_dir/LANG/template

OPTIONS:
  -h, --help     display this help message
  -l, --lang     the language of the project
EOF
  return 0
}
function err() { printf '%s\n' "$@" >&2; }
function log() { printf '%s\n' "$@"; }
function abort() {
  err "$1"
  exit "${2:-1}"
}
# Return the path of each command passed
function cmdpath() {
  local c && for c in "$@"; do
    command -v -- "$c" 2>/dev/null || printf '\n'
  done
}
function joinByChar() {
  local IFS="$1" && shift
  printf '%s' "$*"
}
function _cleanup() { [ -n "$tmp" ] && rm -rf "$tmp" && trap '' EXIT; }

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  local parsed
  local code=0 && getopt --test &>/dev/null || code=$?
  if [ "$code" -ne 4 ]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
  parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@") ||
    exit 2                     # getopt has already complained about wrong arguments to stdout - Exit script
  printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
}

LONGOPTS=help,lang: SHORTOPTS=h,l:
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING"

if [ -d "$PWD/template" ]; then
  # Allow calling new from a template dir
  # ie: ~/code/c means use c as a language
  lang=$(basename "$PWD")
  log "Note: Using '$lang' as the template language. To change this behavior, pass -- as the first argument"
else
  lang="${1:-}"
  if [ -z "$lang" ]; then abort "usage: new <lang> [dest]" 2; fi
  shift # remove lang from arguments
fi

cmd=$(cmdpath "new-$lang")
if [ -x "$cmd" ]; then exec -- "$cmd" "$@"; fi # new-$lang command

tmp="$(mktemp)" && trap _cleanup EXIT              # use one file for all loops
template_dir="$template_parent_dir/$lang/template" # find the template directory
if ! [ -d "$template_dir" ]; then abort "Could not find $template_dir" 1; fi

if [ "$#" -eq 0 ]; then set -- new; fi # default to 'new' if no arguments given
for dest in "$@"; do
  if [ -z "$dest" ]; then err "refusing to create empty named directory!" && continue; fi
  # Don't overwrite existing files
  if [ -d "$dest" ]; then err "$dest already exists! Please move it or choose a new name" && continue; fi

  # Copy the template directory
  cp -ri -- "$template_dir/" "$dest"

  # shellcheck disable=SC2034 # These are dynamically used later
  DATE=$(date '+%m/%d/%Y') TIME=$(date '+%H:%M')

  # usage: substitute file <file >file.new && mv file.new file
  # This evaluates shell expansion patterns (ie. $ENV/${ENV} -> value_of_ENV)
  # Use \$ENV or \${ENV} to escape them
  # Supported vars include FILEPATH,REALPATH,FILENAME,DIRNAME,DATE,TIME,EXTENSION,BASENAME,ROOT
  function substitute() {
    local path="$1" env_pattern envs
    if [ -z "$path" ]; then abort "substitute requires a filepath!" 2; fi
    local envs=(DATE TIME FILEPATH DIRNAME REALPATH FILENAME EXTENSION BASENAME ROOT)
    # shellcheck disable=SC2034 # These are dynamically used later
    {
      declare -I -- "${envs[@]}"                               # these are local, but keep predefined values
      export -- "${envs[@]}"                                   # these should be exported to the perl command
      FILEPATH=$(realpath --relative-to="$dest" -s -- "$path") # filepath relative to root -- root/dir/file.ext -> dir/file.ext
      REALPATH=$(realpath -s -- "$path")                       # full realpath             -- root/dir/file.ext -> /home/aaron/root/dir/file.ext
      FILENAME=$(basename -- "$path")                          # basename of file          -- root/dir/file.ext -> file.ext
      DIRNAME=$(basename -- "$(dirname -- "$path")")           # name of parent directory  -- root/dir/file.ext -> root/dir
      EXTENSION="${FILENAME##*.}"                              # file extension (last!)    -- root/dir/file.ext -> .ext
      BASENAME="${FILENAME%.*}"                                # name without extension    -- root/dir/file.ext -> file
      ROOT="$dest"                                             # name of root (project)    -- root/dir/file -> root
      if [ "$EXTENSION" = "$FILENAME" ]; then EXTENSION=''; fi # Ensure extension is not the filename
    }

    # env_pattern='([A-Z][A-Z_0-9]*)' # only match capital variables!
    env_pattern="($(joinByChar '|' "${envs[@]}"))" # only match the given variables!

    perl -pe 's;(\\*)(\$'"$env_pattern"'|\$\{'"$env_pattern"'\});substr($1,0,int(length($1)/2)).(length($1)%2?$2:$ENV{$3||$4});eg' # Source: https://stackoverflow.com/a/25019138
  }

  # Note: FILEPATH,REALPATH,FILENAME,EXTENSION,BASENAME are relatively useless here
  for f in "$dest"/**; do # handle filename replacements
    filename=$(basename -- "$f") dir=$(dirname -- "$f")
    newname=$(substitute "$f" <<<"$filename")
    case "$newname" in
    "$filename") ;; # ignore if same
    */../* | ../* | */..) err "Disallowed directory traversal: $newname. Skipping." ;;
    */*) mkdir -p "$dir/$(dirname -- "$newname")" ;& # make the directory and fallthrough
    *) mv "$f" "$dir/$newname" ;;                    # move to new location
    esac
  done

  for f in "$dest"/**; do               # handle string replacements
    if ! [ -f "$f" ]; then continue; fi # ignore directories
    # shellcheck disable=SC2094 # substitute doesn't output to a file
    substitute "$f" <"$f" >|"$tmp"                             # Write to tmp file to avoid loosing data (https://www.shellcheck.net/wiki/SC2094)
    cp -p --attributes-only -- "$f" "$tmp" 2>/dev/null || true # save the attributes from the original file (if possible)
    mv -f -- "$tmp" "$f"                                       # overwrite existing file
  done
done

_cleanup # Explicitly cleanup if this is reached
