#!/usr/bin/env bash

# ~/.local/bin/update
#
# Updates the system, including as many possible sources as possible
#
set -euC -o pipefail

THIS=update
usage() {
  cat <<EOF
$THIS [OPTIONS]... -- [METHOD]...
Update system packages and third party packages
If no method is specified, all packages will be updated
This is meant to help avoid forgetting a method,
not to force yes, or any other convience

the environment variable \`SUDO\` can be set to use a different
program for root elevation. It will be split by the shell, so
spaces in the program name will likely be mutilited.

METHOD_ARGS to pass additional options to each command. (IE, NATIVE_ARGS)
Currently supported methods are: native, snap, flatpak, pnpm, npm, cargo
use 'native' to enable or '+native' to disable. ORDER MATTERS!
Options:
--as-root: allow running as root (Discouraged!)
EOF
  return 0
}

# COLOR vars to keep from branching to tput repeatedly
RED_COLOR="$(tput setaf 1 2>/dev/null || printf '')"
YELLOW_COLOR="$(tput setaf 11 2>/dev/null || printf '')"
GREEN_COLOR="$(tput setaf 2 2>/dev/null || printf '')"
BOLD_COLOR="$(tput bold 2>/dev/null || printf '')"
RESET_COLOR="$(tput sgr0 2>/dev/null || printf '')"

log() { printf "$YELLOW_COLOR$BOLD_COLOR%s\n$RESET_COLOR" "$@"; }
show_run() {
  log "running: $*"
  "$@"
}
err() { printf "${THIS:+$THIS:}$RED_COLOR$BOLD_COLOR%s\n$RESET_COLOR" "$@" >&2; }
success() { printf "$GREEN_COLOR$BOLD_COLOR%s$RESET_COLOR\n" "Success!" && printf '\n'; }
abort() { err "$1" && exit "${2:-1}"; }

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  local parsed
  local code=0 && getopt --test &>/dev/null || code=$?
  if [ "$code" -ne 4 ]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
  parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@") ||
    exit 2                     # getopt has already complained about wrong arguments to stdout - Exit script
  printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
}

LONGOPTS=help,as-root,list SHORTOPTS=h,l
ARGSTRING="$(parse_args "$@")"
eval "$ARGSTRING"

allow_root=0
while true; do
  case "$1" in
  -h | --help) usage && exit 0 ;;
  --as-root) allow_root=1 && shift 1 ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

if [ "$(id -u)" -eq 0 ] && [ "$allow_root" -eq 0 ]; then
  err 'This script should not be run as root (due to flatpak).'
  err 'Use SUDO environment variable to override sudo program.'
  err 'Use update --as-root to force the script to run as root'
  exit 2
fi

all_exclude=1 # If all are exclude, enable all by default
for arg; do
  case "$arg" in
  +*) true ;;         # Nothing
  *) all_exclude=0 ;; # Not an exlude.
  esac
done

native=0 flatpak=0 snap=0 pnpm=0 npm=0 cargo=0
if [ "$#" -eq 0 ] || [ "$all_exclude" -eq 1 ]; then
  native=1 flatpak=1 snap=1 pnpm=1 npm=1 cargo=1
fi

for arg; do          # Doesn't do anything if $# is zero
  case "${arg,,}" in # Allow `native` to enable or `native-` to disable. ORDER MATTERS!
  apt | nala | pacman | native) native=1 ;;
  +apt | +nala | +pacman | +native) native=0 ;;
  flatpak) flatpak=1 ;; +flatpak) flatpak=0 ;;
  snap) snap=1 ;; +snap) snap=0 ;;
  pnpm) pnpm=1 ;; +pnpm) pnpm=0 ;;
  npm) npm=1 ;; +npm) npm=0 ;;
  cargo) cargo=1 ;; +cargo) cargo=0 ;;
  all) native=1 flatpak=1 snap=1 pnpm=1 npm=1 ;;
  +all) native=0 flatpak=0 snap=0 pnpm=0 npm=0 ;;
  esac
done

# Environment variables
# shellcheck disable=SC2206 # Splitting is intentional.
sudo=(${SUDO:-sudo})
[ "$(id -u)" -eq 0 ] && sudo=()
# shellcheck disable=SC2206 # Splitting would otherwise happen on the command line, so this is not *my* problem.
{
  NATIVE_ARGS=(${NATIVE_ARGS:-})
  FLATPAK_ARGS=(${FLATPAK_ARGS:-})
  SNAP_ARGS=(${SNAP_ARGS:-})
  PNPM_ARGS=(${PNPM_ARGS:-})
  NPM_ARGS=(${NPM_ARGS:-})
  CARGO_ARGS=(${CARGO_ARGS:-})
}

cmd_available() { command -v "$@" &>/dev/null; }
cmd_path() { command -v "$@"; }

is_something_to_do=0
for i in "$native" "$flatpak" "$snap" "$pnpm" "$npm" "$cargo"; do
  [ "$i" -eq 1 ] || continue # only if something is activated
  is_something_to_do=1
  break
done

if [ "$is_something_to_do" -eq 0 ]; then
  log "Nothing to do"
  exit 0
fi

if [ "$native" -eq 1 ]; then
  log "Updating native packages!"
  if cmd_available nala; then
    log "Using nala"
    show_run "${sudo[@]}" "$(cmd_path nala)" upgrade "${NATIVE_ARGS[@]}"
  elif cmd_available apt; then
    log "Using apt"
    show_run "${sudo[@]}" "$(cmd_path apt)" update "${NATIVE_ARGS[@]}" && "${sudo[@]}" apt upgrade "${NATIVE_ARGS[@]}"
  elif cmd_available yay; then
    log "Using yay"
    show_run "$(cmd_path yay)" -Syu "${NATIVE_ARGS[@]}" # READ THIS!
  elif cmd_available pacman; then
    log "Using pacman"
    show_run "${sudo[@]}" "$(cmd_path pacman)" -Syu "${NATIVE_ARGS[@]}" # READ THIS!
  elif cmd_available dnf; then
    log "Using dnf"
    show_run "${sudo[@]}" "$(cmd_path dnf)" upgrade "${NATIVE_ARGS[@]}"
  fi
  success
fi

if [ "$snap" -eq 1 ] && cmd_available snap; then
  log "Updating snap packages!"
  log
  show_run "${sudo[@]}" "$(cmd_path snap)" refresh "${SNAP_ARGS[@]}"
  success
fi

if [ "$snap" -eq 1 ] && cmd_available snap && cmd_available snap-cleanup; then
  log "Cleaning up snap packages"
  log
  show_run "${sudo[@]}" "$(cmd_path snap-cleanup)" -y
  success
fi

if [ "$flatpak" -eq 1 ] && cmd_available flatpak; then
  log "Updating flatpak packages!"
  log
  show_run "$(cmd_path flatpak)" update "${FLATPAK_ARGS[@]}" # NOT as root!
  success
fi

if [ "$npm" -eq 1 ] && cmd_available n; then
  log "Updating npm!"
  log
  show_run "${sudo[@]}" "$(cmd_path n)" -d lts       # download
  show_run "${sudo[@]}" "$(cmd_path n)" -d latest    # download
  node_latest=$(n ls-remote latest)                  # 1.1.1
  node_current=$(node --version 2>/dev/null || true) # v1.1.1
  if [ "v$node_latest" != "$node_current" ]; then    # only if not already active
    show_run "${sudo[@]}" "$(cmd_path n)" latest     # activate latest
  fi
  success
fi

if [ "$npm" -eq 1 ] && cmd_available npm; then
  log "Updating npm packages!"
  log
  if cmd_available ncu; then
    show_run "$(cmd_path ncu)" -p npm -g # get them to latest
  else
    log "install 'ncu' to improve this experience"
  fi
  show_run "$(cmd_path npm)" upgrade -g "${NPM_ARGS[@]}" # NOT as root!
  success
fi

# NOTE: nodejs < 20.x.x is broken on my machine, as this corepack can't access npm.org
#This is fixed by updating to latest before updating pnpm - see above.
if [ "$pnpm" -eq 1 ] && cmd_available corepack; then
  log "Updating pnpm!"
  log
  show_run "$(cmd_path corepack)" prepare pnpm@latest --activate
  success
fi

if [ "$pnpm" -eq 1 ] && cmd_available pnpm; then
  log "Updating pnpm packages!"
  log
  show_run "$(cmd_path pnpm)" upgrade -g --latest # NOT as root!
  pnpm_root=0
  for f in /root/.local/share/pnpm/global/*/package.json; do
    if [ -f "$f" ]; then pnpm_root=true && break; fi
  done
  [ "$pnpm_root" -eq 1 ] && show_run "${sudo[@]}" "$(cmd_path pnpm)" update -g --latest "${PNPM_ARGS[@]}"
  success
fi

if [ "$cargo" -eq 1 ] && cmd_available rustup; then
  log "Updating cargo and rustc!"
  log
  show_run "$(cmd_path rustup)" update
  success
fi

if [ "$cargo" -eq 1 ] && cmd_available cargo && cmd_available cargo-install-update; then
  log "Updating cargo installed packages!"
  log
  show_run "$(cmd_path cargo)" install-update --all --git "${CARGO_ARGS[@]}"
  success
fi
