#!/usr/bin/env bash

set -euC -o pipefail

log() { printf '%s\n' "$@"; }
err() { printf '%s\n' "$@" >&2; }
if [ "$EUID" -eq 0 ]; then
  err 'This script should not be run as root (due to flatpak).'
  err 'Use SUDO environment variable to override sudo program.'
  err 'Use update --as-root to force the script to run as root'
fi

if command -v nala; then
  nala upgrade
elif command -v apt; then
  apt update && apt upgrade
fi

if command -v snap; then
  snap refresh
fi
