#! /usr/bin/env bash

# ~/.local/bin/contents
#
# Read the contents of a file or executable
# *Follows Symlinks*
#
THIS=contents
usage() {
  cat <<EOF
$THIS [file|executable...]
                  
outputs the contents of a file using \$PAGER, calls which if file is not found
options:
-P, --no-pager      Don't attempt to open the files using a pager (\$PAGER)
-p, --pager=PAGER   Use <PAGER> instead of \$PAGER
EOF
  return 0
}
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }

set -eu # subshell
args=() end=false pager=true
# If awaiting an argument
next='' next_arg=''
for arg; do
  if [ $end = true ]; then
    args+=("$arg")
    continue
  elif [ -n "$next" ]; then
    declare "$next"="$arg" next=''
  else
    case "$arg" in
    --help | -h) usage && exit 0 ;;
    --) end=true ;;
    --no-pager | -P) pager=false ;;
    -p | --pager) next=pager next_arg="$arg" ;;
    --pager=*) pager="${arg#--pager=}" ;;
    --*) abort "Invalid option -- ${arg#--}" 2 ;;
    -*) abort "Invalid option -- ${arg#-}" 2 ;;
    *) args+=("$arg") ;;
    esac
  fi
done
# If awaiting an argument, but end of args
if [ -n "$next" ]; then abort "$next_arg requires an argument" 2; fi
unset end next next_arg

if [ "${#args[@]}" -eq 0 ]; then
  abort 'FILE is required' 2
fi

files=()
for file in "${args[@]}"; do
  # Given a path
  if [ -f "$file" ]; then
    files+=("$file")
    continue
  fi

  # given a name
  whichfile=$(which "$file" 2>/dev/null)
  if [ -f "$whichfile" ]; then
    files+=("$whichfile")
    continue
  fi

  # couldn't find
  err "$file is not a file"
  continue
done

# Use pager if can, else use cat
if [ "$pager" = true ] && [ -t 1 ]; then
  PAGER=${PAGER:-$(which pager 2>/dev/null || which cat 2>/dev/null || printf '/bin/cat')}
elif [ "$pager" = false ]; then
  PAGER=$(which cat 2>/dev/null || printf '/bin/cat')
elif [ "$pager" != true ]; then
  PAGER="$pager"
fi
# output them all -- PAGER is expanded to allow flags
exec ${PAGER:-cat} -- "${files[@]}"
