#!/usr/bin/env bash
export BASH_TPL_TAG_DELIMS='{{ }}'
export BASH_TPL_TAG_STMT_DELIM=
export BASH_TPL_STMT_DELIM="#@"
export BASH_TPL_STMT_BLOCK_DELIMS=
export BASH_TPL_TEXT_DELIM=
export BASH_TPL_DIR_DELIM=":"
export BASH_TPL_CMT_DELIM="%#"

# don't match -> empty string. Include dotfiles. Allow double star
shopt -s nullglob dotglob globstar
set -euC -o pipefail
# Find the current file and it's directory
# Source: https://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]:-}" DIR=''
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$(builtin cd -P -- "$(command dirname -- "$SOURCE")" &>/dev/null && builtin pwd)" || true
  SOURCE="$(command readlink -- "$SOURCE")" || true
  [[ "$SOURCE" == /* ]] || SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$(builtin cd -P -- "$(command dirname -- "$SOURCE")" &>/dev/null && builtin pwd)" || true
DIR="${DIR:-"$PWD"}"
utils="$DIR/script_utils.sh"
[ -f "$utils" ] || utils="$(basename -- "$utils")" || true # If utils is not a file, search for it in "$PATH" instead.
# shellcheck source=./script_utils.sh
. "$utils"             # Note: this may error. I can't use it in a conditional or bashls fails.
[ "$?" -eq 0 ] || exit # set -e means that this line should be irrelevant, but just in case.

template_parent_dir=("$HOME/code" "$HOME/Templates")

BASH_TPL=$(cmdpath bash-tpl 2>/dev/null) || true
function get_bash_tpl() {
  ! [ -x "$BASH_TPL" ] || return 0
  err "could not find bash-tpl!"
  # outputs to stderr
  select choice in "install" "use perl" "install to temp file" "abort"; do
    case "$choice" in
    "install")
      dest=/usr/local/bin/bash-tpl
      sudo_cmd true
      download 'https://github.com/TekWizely/bash-tpl/releases/latest/download/bash-tpl' | sudo_cmd tee "$dest" >/dev/null
      sudo_cmd chmod +x "$dest"
      BASH_TPL="$dest"
      return 0
      ;;
    "use perl")
      err "Using perl to do substitutions. Note that this does *not* support most shell expansions and will almost definitely result in incorrect output."
      sleep 1
      BASH_TPL=''
      return 1
      ;;
    "install to temp file")
      dest=$(mktemp)
      add_tmpfile "$dest"
      err "Downloading bash-tpl to '$dest'..."
      download 'https://github.com/TekWizely/bash-tpl/releases/latest/download/bash-tpl' >"$dest"
      chmod +x "$dest"
      BASH_TPL="$dest"
      return 0
      ;;
    abort) abort "Aborting" 1 ;;
    '') ;; # ignore the empty string
    *) abort "Unknown choice: $choice. This is a bug!" 3 ;;
    esac
    [ -z "$choice" ] || break
  done </dev/tty 2>/dev/tty
  return 1
} && get_bash_tpl

THIS=${SOURCE:-$(basename -- "$0")}
function usage() {
  cat <<EOF
Usage: $THIS [LANG] [--] <DIR>...
Creates a new project in the given language. 

First checks for new-LANG command ('/' replaced with '_'), if found, pass DIRs and exit
Second checks each of the following directories for a file at /LANG/template:
$(join ', ' "${template_parent_dir[@]}") 
if it finds a file, it will pass DIRs and exit
if it finds a directory, it will copy it to each DIR and continue with the below process
else, outputs an error message and exits

For each DIR, a series of variable expansions are applied to the filenames and contents of all files and directories contained
Variables:
Note: list may be incomplete
Note: For each \$VAR, there is a \$var which has the same value but lowercase
    DATE:        The date of creation (mm/dd/yyyy)                             -- 09/19/2023
    TIME:        The time of creation (hh:mm)                                  -- 16:25
    FILEPATH:    The filepath relative to ROOT                                 -- root/dir/file.ext -> dir/file.ext
    REALPATH:    The absolute path to the file                                 -- root/dir/file.ext -> /home/aaron/root/dir/file.ext
    FILENAME:    The basename of the file                                      -- root/dir/file.ext -> file.ext
    DIRNAME:     The name of the parent directory                              -- root/dir/file.ext -> root/dir
    EXTENSION:   The LAST file extension. Empty if none                        -- root/dir/file.ext -> .ext
    BASENAME:    The filename without extension (if present)                   -- root/dir/file.ext -> file
    ROOT:        The name of the root (DIR on cmdline)                         -- root/dir/file -> root

OPTIONS:
  -l, --lang LANG          the language of the project (language argument is treated as a DIR)
  -t, --template TEMPLATE  the template to use (Note, this skips the new-LANG check)
  -h, --help               display this help message
  -d, --debug              enable debugging output
EOF
  return 0
}

# usage: substitute file "$dest" <file >file.new && mv file.new file
# This evaluates shell expansion patterns (ie. $ENV/${ENV} -> value_of_ENV)
# Use \$ENV or \${ENV} to escape them
# Supported vars include FILEPATH,REALPATH,FILENAME,DIRNAME,DATE,TIME,EXTENSION,BASENAME,ROOT
# uses the second argument as the root directory
function substitute() {
  local path="$1" dest="$2"
  local env_pattern
  if [ -z "$path" ]; then abort "${FUNCNAME[0]} requires a filepath!" 2; fi
  local envs=(
    DATE TIME FILEPATH DIRNAME REALPATH FILENAME EXTENSION BASENAME ROOT
    date time filepath dirname realpath filename extension basename root
  )
  # shellcheck disable=SC2034 # These are dynamically used later
  {
    declare -I -- "${envs[@]}"                               # these are local, but keep predefined values
    export -- "${envs[@]}"                                   # these should be exported to the perl command
    FILEPATH=$(realpath --relative-to="$dest" -s -- "$path") # filepath relative to root -- root/dir/file.ext -> dir/file.ext
    REALPATH=$(realpath -s -- "$path")                       # full realpath             -- root/dir/file.ext -> /home/aaron/root/dir/file.ext
    FILENAME=$(basename -- "$path")                          # basename of file          -- root/dir/file.ext -> file.ext
    DIRNAME=$(basename -- "$(dirname -- "$path")")           # name of parent directory  -- root/dir/file.ext -> root/dir
    EXTENSION="${FILENAME##*.}"                              # file extension (last!)    -- root/dir/file.ext -> .ext
    BASENAME="${FILENAME%.*}"                                # name without extension    -- root/dir/file.ext -> file
    ROOT="$(basename -- "$dest")"                            # name of root (passed val) -- root/dir/file -> root
    if [ "$EXTENSION" = "$FILENAME" ]; then EXTENSION=''; fi # Ensure extension is not the filename

    filepath=${FILEPATH,,} realpath=${REALPATH,,}
    filename=${FILENAME,,} dirname=${DIRNAME,,}
    extension=${EXTENSION,,} basename=${BASENAME,,}
    root=${ROOT,,} date=${DATE,,} time=${TIME,,}
  }

  if [ -x "${BASH_TPL:-}" ]; then
    debug "Using bash-tpl ($BASH_TPL) to substitute values in $path"
    "$BASH_TPL" | bash
  else
    debug "Using perl to substitute variables in $path"
    # env_pattern='([A-Z][A-Z_0-9]*)' # only match capital variables!
    env_pattern="($(join '|' "${envs[@]}"))"                                                                                       # only match the given variables!
    perl -pe 's;(\\*)(\$'"$env_pattern"'|\$\{'"$env_pattern"'\});substr($1,0,int(length($1)/2)).(length($1)%2?$2:$ENV{$3||$4});eg' # Source: https://stackoverflow.com/a/25019138
  fi
}
# usage: for f in "$dest"/*; do handle_file_sub "$f"; done
# Handles substitutions in filenames and contents recursively
# This must be recursively to handle a changing file tree.
# Uses environment variable $tmp as a temporary file
function handle_file_sub() {
  local f="$1" dest="$2"
  local filename dir newname
  debug "handling $f"
  # handle filename replacements
  filename=$(basename -- "$f") dir=$(dirname -- "$f")
  # Note: FILEPATH,REALPATH,FILENAME,EXTENSION,BASENAME are relatively useless here
  newname=$(substitute "$f" "$dest" <<<"$filename") || abort "Error while handling file: $f" "$?"
  case "$newname" in
  "$filename") ;; # ignore if same
  */../* | ../* | */..) err "Disallowed directory traversal: '$newname'. Skipping." ;;
  */*) mkdir -p "$dir/$(dirname -- "$newname")" ;& # make the directory and fallthrough
  *)
    debug "move to $dir/$newname"
    mv "$f" "$dir/$newname" # move to new location
    f="$dir/$newname"       # ensure future references are correct
    ;;
  esac

  # handle string replacements
  if [ -d "$f" ]; then
    for d in "$f"/*; do handle_file_sub "$d" "$dest"; done
  elif ! [ -L "$f" ] && [ -f "$f" ]; then # Don't write to links
    debug "handle file $f"
    # shellcheck disable=SC2094 # substitute doesn't output to a file
    # Write to tmp file to avoid loosing data (https://www.shellcheck.net/wiki/SC2094)
    substitute "$f" "$dest" <"$f" >|"$tmp" || abort "Error while handling file: $f" "$?"
    cp -p --attributes-only -- "$f" "$tmp" 2>/dev/null || true # save the attributes from the original file (if possible)
    mv -f -- "$tmp" "$f"                                       # overwrite existing file
  fi
}

LONGOPTS=help,debug,lang:,template: SHORTOPTS=h,d,l:,t:
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit
lang='' template=''
while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --lang | -l) lang="$2" && shift 2 ;;
  --debug | -d) DEBUG=1 && shift 1 ;;
  --template | -t) template="$2" && shift 2 ;;
  --) shift && break ;;
  *) abort "This is a bug. \$*: $*" 3 ;;
  esac
done

if [ -z "$template" ] && [ -z "$lang" ]; then
  ## Disabled to encourage better habits!
  # case "$PWD" in
  # "$template_parent_dir"/*)              # Allow calling new from a template dir. ie: ~/code/c or ~/code/c/dir means use c as a language
  #   lang="${PWD#"$template_parent_dir"}" # ~/code/c/dir -> /c/dir
  #   lang=${lang#/}                       # /c/dir -> c/dir
  #   lang=${lang%%/*}                     # c/dir -> c
  #   log "Note: Using '$lang' as the template language. To change this behavior, use the -l flag"
  #   ;;
  # *)
  lang="${1:-}"
  shift &>/dev/null || true # remove lang from arguments
  # ;;
  # esac
fi
[ -n "$lang" ] || abort "Language is required. Please pass it using -l or the first argument" 2
lang=${lang%/} # remove trailing slash if present
lang=${lang#/} # remove leading slash if present
# find the template directory -- not given, and lang *was*
if [ -z "$template" ] && [ -n "$lang" ]; then
  for dir in "${template_parent_dir[@]}"; do
    template="$dir/$lang/template"
    # Note: this check may have false positives, but I don't care.
    ! [ -e "$template" ] || break
  done
fi

# if [ "$#" -eq 0 ]; then set -- new; fi # default to 'new' if no arguments given
if [ "$#" -eq 0 ]; then abort 'DIR is required' 2; fi

cmdpath=$(cmdpath "new-${lang//\//_}") || true         # replace slashes with underscores
if [ -x "$cmdpath" ]; then exec -- "$cmdpath" "$@"; fi # new-$lang command

# Doesn't exist. Warn the user! Empty string will be caught by `! -d`
if [ -f "$template" ]; then
  log "Using '$template' as the template file"
  [ -x "$template" ] || abort "'$template' is not executable! Aborting!" 1
  exec -- "$template" "$@"
elif ! [ -d "$template" ]; then
  abort "Could not find template '$template'. Aborting!" 1
fi
log "Using template directory '$template'"

template=${template%/}            # remove trailing slash
[ "$#" -eq 0 ] || tmp="$(mktemp)" # use one file for all loops
add_tmpfile "$tmp"
for dest in "$@"; do
  dest=${dest%/} # remove trailing slash
  if [ -z "$dest" ]; then err "refusing to create empty named directory!" && continue; fi
  # Don't overwrite existing files
  if [ -d "$dest" ]; then err "$dest already exists! Please move it or choose a new name" && continue; fi

  log "Creating '$dest'"
  mkdir -p -- "$(dirname -- "$dest")" # Ensure parent directory exists
  cp -ri -- "$template/" "$dest"      # Copy the template directory - Note: The trailing slash is important to copy the target if it's a symlink

  # These are dynamically used later
  DATE=$(date '+%m/%d/%Y') TIME=$(date '+%H:%M')

  for f in "$dest"/*; do handle_file_sub "$f" "$dest"; done
done
