#!/usr/bin/env bash

# ~/.local/bin/post-temp
#
# Hosts a temporary file on the internet for 60 mins and echos the url.
#
#
set -eu

THIS='post-temp'
temp_source=https://tmpfiles.org/api/v1/upload

usage() {

  cat <<EOF
Usage: $THIS [OPTION...] [--] FILE...
Hosts a temporary file on the internet for 60 mins and outputs the url.

OPTIONS:
  -h, --help       display this help message
  -v, --verbose    display verbose messages
  -q, --quiet      be quieter
  -t, --temp=url   use url to upload files (POST) (default: $temp_source)
EOF
  return 0
}
log() { printf '%s\n' "$@"; }
err() { printf "$THIS: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }

# Sets the variable $args to an array of positional arguments
# Usage: parse_args "$@"
function parse_args() {
  # If awaiting an argument
  local next='' next_arg='' end=false
  declare -g args=()
  for arg in "$@"; do
    if [ $end = true ]; then
      args+=("$arg") && continue
    elif [ -n "$next" ]; then
      # -x to expose outside function
      declare -g "$next"="$arg"
      next=''
    else
      case "$arg" in
      --help | -h) usage && exit 0 ;;
      --) end=true ;;
      -v | --verbose) verbose=true ;; # Verbose option
      -q | --quiet) quiet=true ;;     # Quiet option
      -t | --temp) next=temp_source next_arg="$arg" ;;
      --temp=*) temp_source="${arg#--temp=}" ;;
      --*) abort "Invalid option -- ${arg#--}" 2 ;;
      -*) abort "Invalid option -- ${arg#-}" 2 ;;
      *) args+=("$arg") ;;
      esac
    fi
  done
  # If awaiting an argument, but end of args
  if [ -n "$next" ]; then abort "$next_arg requires an argument" 2; fi
}

# Usage if no args are passed
if [ "$#" -eq 0 ]; then usage && exit 0; fi
# Parse the arguments and default values
verbose=false quiet=false
parse_args "$@"
# Error if args given, but no files given
if [ "${#args[@]}" -eq 0 ]; then abort "FILE is required!" 2; fi

fx=$(which fx 2>/dev/null || printf '')
if [ -z "$fx" ] && [ "$quiet" != "true" ]; then err "This script works much better with 'fx' installed."; fi

declare -i exitcode=0

for file in "${args[@]}"; do
  if ! [[ -f "$file" ]]; then
    err "'$file' is not a file"
    exitcode=2 && continue
  fi

  result="$(curl -sSfL -F "file=@$file" "$temp_source")" ||
    abort 'Something went wrong during curl command. Aborting.' 1 # exits program
  # Example outputs:
  # {"message": "server error"}
  # {"status":"success","data":{"url":"https://tmpfiles.org/######/file"}}

  # If verbose, or fx not installed, print entire json
  if [ "$verbose" = true ] || [ -z "$fx" ]; then
    log "$result"
    [ -z "$fx" ] && continue # Stops loop here because fx is not installed
  fi

  # Print the result thru fx to get the data
  # Already strings, if present, but trying to error
  status="$("$fx" '.status.toString()' <<<"$result" 2>/dev/null)"
  url="$("$fx" '.data.url.toString()' <<<"$result" 2>/dev/null)"

  if [ -z "$status" ] || [ -z "$url" ]; then
    message="$("$fx" '.message.toString()' <<<"$result" 2>/dev/null)"
    if [ -n "$message" ]; then err "$message"; else err "An unknown error occured"; fi
    exitcode=1
  else
    [ "$quiet" != true ] && log "$status"
    log "${url/tmpfiles.org\//tmpfiles.org\/dl\/}"
  fi
done

exit $exitcode
