#!/usr/bin/env bash
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"

default_sink='@DEFAULT_SINK@' default_source='@DEFAULT_SOURCE@' default_device="$default_sink"
function usage() {
  cat <<EOF || true
Usage: $THIS [OPTS]... PERCENT
Sets the volume to the specified PERCENT. Use n{+,-} to incremenet the volume.
Call with no positional arguments to output the current volume.

Options:
  -h, --help           Show this help message.
  -m, --mute           Toggle mute on the device.
  -d, --device=dev     pactl sink/source to set the volume on (default: $default_device)
  -s, --source         Treat device as a source instead. (default: $default_source)
EOF
}

LONGOPTS="help,device:,mute,source" SHORTOPTS="h,d:,m,s"
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

device_type=sink device=
mute=0
while true; do
  case "$1" in
  -h | --help) usage && exit 0 ;;
  -d | --device) device="$2" && shift 2 ;;
  -m | --mute) mute=1 && shift ;;
  -s | --source)
    device_type=source
    default_device="$default_source"
    shift
    ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done
device="${device:-$default_device}" # Don't change if the user specified a source

vol=${1:-} suf=''
if [ -n "$vol" ]; then
  case "$vol" in
  +* | *+) suf=+ ;;
  -* | *-) suf=- ;;
  esac
  # all valid: 20-, -20, 20+, +20, +20%, 20%+, 20%
  vol=${vol%-} vol=${vol#-} vol=${vol%+} vol=${vol#+} vol=${vol%\%}
fi

# If volume passed, set it and unmute (or mute if -m passed)
# else if -m passed, toggle mute
# This allows to call
#  - `volume mute` to toggle mute
#  - `volume 20` to set volume and unmute
#  - `volume 20 -m` to set volume and mute

if [ -n "${vol:-}" ]; then
  pactl "set-$device_type-volume" "$device" "$suf$vol%"
  case "$mute" in
  0) pactl "set-$device_type-mute" "$device" false ;; # user experience! :)
  1) pactl "set-$device_type-mute" "$device" true ;;
  esac
elif [ "$mute" -eq 1 ]; then
  pactl "set-$device_type-mute" "$device" toggle
fi

pactl "get-$device_type-volume" "$device"
