#!/usr/bin/env bash
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=./script_utils.sh
. "$utils"

USE_COLOR=1 # Output using color

# Used for default file output
resolution='640x480' videodev=/dev/video0
# First Char decides the type, rest is value
# Example: F1 = 1 frame, D2 = 2 seconds, C = continuous, I = Image (1 frame)
record_for=I
file_extension='' # detect based on frames/duration after processing
loglevel=warning

function usage() {
  cat <<EOF || true
Usage: $THIS [OPTS]... [OUTFILE]
Saves a capture of the webcam to the given file
The default behavior saves the file under the pictures directory if frames is 1, or else the videos directory

Options:
  -h, --help           Show this help message.
  -c, --continuous     Capture video until q is pressed.
  -d, --duration=dur   Capture given duration: seconds or hh:mm:ss[.xxx].
  -e, --extension=ext  Use given default extension (no '.') [default: jpg (image), else mp4]
  -f, --frames=frames  Capture given number of frames
  -i, --image          Take an image instead of a video. [default]
  -l, --loglevel=level Pass level to ffmpeg as the log level [default: $loglevel]
  -r, --resolution=res Use the given resolution [default: $resolution]
  -v, --video=dev      Use the video device [default: $videodev]


The last provided of --frames, --duration, --continuous, and --image will be used
Note: ultimately all arguments are processed by ffmpeg, so they must be acceptable combinations according to ffmpeg.
For example: this means that saving several frames as "file.jpg" may fail.
EOF
}

LONGOPTS=help,resolution:,frames:,duration:,extension:,video:,loglevel:,continuous,image
SHORTOPTS=h,r:,f:,d:,e:,v:,l:,c,i
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

while true; do
  case "$1" in
  -h | --help) usage && exit 0 ;;
  -c | --continuous) record_for="C" && shift 1 ;; # mutually exclusive
  -d | --duration) record_for="D$2" && shift 2 ;; # mutually exclusive
  -f | --frames) record_for="F$2" && shift 2 ;;   # mutually exclusive
  -i | --image) record_for="I" && shift 1 ;;      # mutually exclusive
  -e | --extension) file_extension=$2 && shift 2 ;;
  -l | --loglevel) loglevel=$2 && shift 2 ;;
  -r | --resolution) resolution=$2 && shift 2 ;;
  -v | --video) videodev=$2 && shift 2 ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done
output=${1:-}
check_dependencies "ffmpeg" # This script (obviously) requires ffmpeg

# don't override user's choice
[ -n "$file_extension" ] ||
  file_extension="mp4" && [ "$record_for" != "I" ] || file_extension="jpg" # only if image, default to jpg

[ -c "$videodev" ] || abort "$videodev is not a valid character device! Please check your video device and try again." 1

outputdir=''
if [ -n "$output" ]; then
  outputdir=$(dirname -- "$output")
  [ -d "$outputdir" ] || abort "$outputdir: No such directory" 1
else                             # create a default output file
  date=$(date '+%Y-%m-%d_%H-%M') # yyyy-mm-dd_hh-mm

  if has_cmd xdg-user-dir; then
    type=VIDEOS && [ "$record_for" != "I" ] || type=PICTURES
    outputdir="$(xdg-user-dir "$type" 2>/dev/null)" || true
  fi

  if [ -n "$outputdir" ]; then
    # Ensure our new output directory exists
    [ -d "$outputdir" ] || mkdir -p -- "$outputdir" || return 1
    if [ -d "$outputdir/Webcam" ]; then
      outputdir="$outputdir/Webcam" # default to /pictures/Webcam if folder exists
    fi
  fi

  # Output is output directory (or current) followed by date and format
  output="${outputdir:-.}/${date}.${file_extension}"
  get_unique_filename "$output" ".$file_extension" output # saves to output
fi

ffmpeg_args=(
  -hide_banner          # pls be quieter
  -loglevel "$loglevel" # pretty please
  -stats                # show statistics/progress
)

if [ "$record_for" != 'I' ]; then # not an image!
  ffmpeg_args+=(
    -f alsa    # use alsa to get audio
    -i default # Default audio source
    # -ac 2 # channel count - ffmpeg can guess
  )
fi

ffmpeg_args+=(
  -f video4linux2  # use the video4linux2 driver
  -s "$resolution" # set the resolution
  -i "$videodev"   # read from /dev/video0
)

# Log before case so the press q message appears after
log "Saving capture to $output at resolution $resolution"
case "$record_for" in
# Add -(video)frames to specify the number of frames
F*) ffmpeg_args+=(-vframes "${record_for#F}") ;;
# If taking image, only one frame is needed
I) ffmpeg_args+=(-vframes 1) ;;
# Restrict the transcoded/captured video sequence to the duration specified in seconds. hh:mm:ss[.xxx] syntax is also supported.
D*) ffmpeg_args+=(-t "${record_for#D}") ;;
# Default ffmpeg behavior is continuous capture
C) log "Press q to stop recording" ;; # ctrl-c also works, but exits weird.
*) abort "Unrecognized record_for prefix: $record_for. This is a bug!" 3 ;;
esac

ffmpeg "${ffmpeg_args[@]}" -- "$output" || abort "ffmpeg failed!" "$?"
