#!/usr/bin/env bash

set -euC -o pipefail
# Globs that don't match expand to empty strings
shopt -s nullglob

THIS="power-mode"

usage() {
  cat <<-EOF
usage: $THIS [OPTS]... [newmode]
Sets the kernal power saving/performance mode
Call without arguments to show the current and available modes

Options:
  -h, --help         Show this help message.
EOF
}

log() { printf '%s\n' "$@"; }
err() { printf "%s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }
# use like '$sudo do_something' - could break with SUDO="something with spaces"
sudo=
if [ "$(id -u)" -ne 0 ]; then
  sudo="${SUDO:-sudo}"
fi

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  # -allow a command to fail with !’s side effect on errexit
  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
  # shellcheck disable=SC2251
  ! getopt --test >/dev/null
  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi

  local parsed
  if parsed="$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@")"; then
    # output getopt’s output this way to handle the quoting right:
    printf '%s' "set -- $parsed"
    return 0
  fi
  # getopt has already complained about wrong arguments to stdout - Exit script
  exit 2
}

LONGOPTS=help SHORTOPTS=h
ARGSTRING="$(parse_args "$@")"
eval "$ARGSTRING"

while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

# Hard coded to cpu0, it should be fine.
AVAIL_PATH=/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
PATHS=(/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor)
CURRENT_PATH=${PATHS[0]:-}
if ! [ -f "$AVAIL_PATH" ] || ! [ -f "$CURRENT_PATH" ]; then
  abort 'Please make sure your kernal supports scaling governors' 3
fi

avail_options=$(cat "$AVAIL_PATH")
current=$(cat "$CURRENT_PATH")
case "$#" in
0)
  cat <<EOF
available options: $avail_options
currently selected: $current
EOF
  ;;
1)
  mode=$1
  case " $avail_options " in
  *" $mode "*) log "Setting mode: $mode" ;;
  *)
    err "$mode is not an available mode."
    abort "Available modes are: $avail_options" 2
    ;;
  esac
  printf '%s' "$mode" | $sudo tee "${PATHS[@]}" >/dev/null
  ;;
*) abort 'Too many arguments.' 2 ;;
esac
