#!/usr/bin/env bash
# don't match -> empty string. Include dotfiles. Allow double star
shopt -s nullglob dotglob globstar
set -euC -o pipefail

template_parent_dir="$HOME/code"
usage() {
  THIS=$(basename "$0")
  cat <<EOF
Usage: $THIS [LANG] [--] <DIR>...
Creates a new project in the given language. Note that slashes (/) in LANG will be replaced with underscores (_)

First checks for new-LANG command, if found, pass DIRs and exit
Second checks for a file $template_parent_dir/LANG/template, if found, pass DIRs and exit
Third checks for a directory $template_parent_dir/LANG/template, if found, copy to DIRs and continue

For each DIR, a series of variable expansions are applied to the filenames and contents of all files and directories contained
Variables (List may be incomplete):
    DATE:        The date of creation (mm/dd/yyyy)                             -- 09/19/2023
    TIME:        The time of creation (hh:mm)                                  -- 16:25
    FILEPATH:    The filepath relative to ROOT                                 -- root/dir/file.ext -> dir/file.ext
    REALPATH:    The absolute path to the file                                 -- root/dir/file.ext -> /home/aaron/root/dir/file.ext
    FILENAME:    The basename of the file                                      -- root/dir/file.ext -> file.ext
    DIRNAME:     The name of the parent directory                              -- root/dir/file.ext -> root/dir
    EXTENSION:   The LAST file extension. Empty if none                        -- root/dir/file.ext -> .ext
    BASENAME:    The filename without extension (if present)                   -- root/dir/file.ext -> file
    ROOT:        The name of the root (DIR on cmdline)                         -- root/dir/file -> root

OPTIONS:
  -l, --lang LANG          the language of the project (language argument is treated as a DIR)
  -t, --template TEMPLATE  the template to use (Note, this skips the new-LANG check)
  -h, --help               display this help message
  -d, --debug              enable debugging output
EOF
  return 0
}
function debug() { if [ -n "${DEBUG:-}" ]; then printf 'DEBUG: %s\n' "$@" >&2 || true; fi; }
function err() { printf '%s\n' "$@" >&2 || true; }
function log() { printf '%s\n' "$@" || true; }
function abort() {
  err "$1"
  exit "${2:-1}"
}
# Return the path of each command passed
function cmdpath() {
  local c && for c in "$@"; do
    command -v -- "$c" 2>/dev/null || printf '\n'
  done
}
function joinByChar() {
  local IFS="$1" && shift
  printf '%s' "$*"
}
function _cleanup() { [ -n "${tmp:-}" ] && rm -rf "$tmp" && trap '' EXIT; }
# usage: substitute file <file >file.new && mv file.new file
# This evaluates shell expansion patterns (ie. $ENV/${ENV} -> value_of_ENV)
# Use \$ENV or \${ENV} to escape them
# Supported vars include FILEPATH,REALPATH,FILENAME,DIRNAME,DATE,TIME,EXTENSION,BASENAME,ROOT
# NOTE: uses the environment variable `dest` as the root directory
function substitute() {
  local path="$1" env_pattern envs
  if [ -z "$path" ]; then abort "substitute requires a filepath!" 2; fi
  local envs=(DATE TIME FILEPATH DIRNAME REALPATH FILENAME EXTENSION BASENAME ROOT)
  # shellcheck disable=SC2034 # These are dynamically used later
  {
    declare -I -- "${envs[@]}"                               # these are local, but keep predefined values
    export -- "${envs[@]}"                                   # these should be exported to the perl command
    FILEPATH=$(realpath --relative-to="$dest" -s -- "$path") # filepath relative to root -- root/dir/file.ext -> dir/file.ext
    REALPATH=$(realpath -s -- "$path")                       # full realpath             -- root/dir/file.ext -> /home/aaron/root/dir/file.ext
    FILENAME=$(basename -- "$path")                          # basename of file          -- root/dir/file.ext -> file.ext
    DIRNAME=$(basename -- "$(dirname -- "$path")")           # name of parent directory  -- root/dir/file.ext -> root/dir
    EXTENSION="${FILENAME##*.}"                              # file extension (last!)    -- root/dir/file.ext -> .ext
    BASENAME="${FILENAME%.*}"                                # name without extension    -- root/dir/file.ext -> file
    ROOT="$dest"                                             # name of root (project)    -- root/dir/file -> root
    if [ "$EXTENSION" = "$FILENAME" ]; then EXTENSION=''; fi # Ensure extension is not the filename
  }

  # env_pattern='([A-Z][A-Z_0-9]*)' # only match capital variables!
  env_pattern="($(joinByChar '|' "${envs[@]}"))" # only match the given variables!

  perl -pe 's;(\\*)(\$'"$env_pattern"'|\$\{'"$env_pattern"'\});substr($1,0,int(length($1)/2)).(length($1)%2?$2:$ENV{$3||$4});eg' # Source: https://stackoverflow.com/a/25019138
}
# usage: for f in "$dest"/*; do handle_file_sub "$f"; done
# Handles substitutions in filenames and contents recursively
# This must be recursively to handle a changing file tree.
# Uses environment variable $tmp as a temporary file
function handle_file_sub() {
  local f="$1" filename dir newname
  debug "handling $f"
  # handle filename replacements
  filename=$(basename -- "$f") dir=$(dirname -- "$f")
  newname=$(substitute "$f" <<<"$filename") # Note: FILEPATH,REALPATH,FILENAME,EXTENSION,BASENAME are relatively useless here
  case "$newname" in
  "$filename") ;; # ignore if same
  */../* | ../* | */..) err "Disallowed directory traversal: '$newname'. Skipping." ;;
  */*) mkdir -p "$dir/$(dirname -- "$newname")" ;& # make the directory and fallthrough
  *)
    debug "move to $dir/$newname"
    mv "$f" "$dir/$newname" # move to new location
    f="$dir/$newname"       # ensure future references are correct
    ;;
  esac

  # handle string replacements
  if [ -d "$f" ]; then
    for d in "$f"/*; do handle_file_sub "$d"; done
  elif ! [ -L "$f" ] && [ -f "$f" ]; then # Don't write to links
    debug "handle file $f"
    # shellcheck disable=SC2094 # substitute doesn't output to a file
    substitute "$f" <"$f" >|"$tmp"                             # Write to tmp file to avoid loosing data (https://www.shellcheck.net/wiki/SC2094)
    cp -p --attributes-only -- "$f" "$tmp" 2>/dev/null || true # save the attributes from the original file (if possible)
    mv -f -- "$tmp" "$f"                                       # overwrite existing file
  fi
}

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  local parsed
  local code=0 && getopt --test &>/dev/null || code=$?
  if [ "$code" -ne 4 ]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
  parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@") ||
    exit 2                     # getopt has already complained about wrong arguments to stdout - Exit script
  printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
}

LONGOPTS=help,debug,lang:,template: SHORTOPTS=h,d,l:,t:
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit
lang='' template=''
while true; do
  case "$1" in
  --help | -h) usage && exit 0 ;;
  --lang | -l) lang="$2" && shift 2 ;;
  --debug | -d) DEBUG=1 && shift 1 ;;
  --template | -t) template="$2" && shift 2 ;;
  --) shift && break ;;
  *) abort "This is a bug. \$*: $*" 3 ;;
  esac
done

if [ -z "$template" ] && [ -z "$lang" ]; then
  ## Disabled to encourage better habits!
  # case "$PWD" in
  # "$template_parent_dir"/*)              # Allow calling new from a template dir. ie: ~/code/c or ~/code/c/dir means use c as a language
  #   lang="${PWD#"$template_parent_dir"}" # ~/code/c/dir -> /c/dir
  #   lang=${lang#/}                       # /c/dir -> c/dir
  #   lang=${lang%%/*}                     # c/dir -> c
  #   log "Note: Using '$lang' as the template language. To change this behavior, use the -l flag"
  #   ;;
  # *)
  lang="${1:-}"
  shift &>/dev/null || true # remove lang from arguments
  # ;;
  # esac
  [ -z "$lang" ] && abort "Language is required. Please pass it using -l or the first argument" 2
fi
# find the template directory -- not given, and lang *was*
if [ -z "$template" ] && [ -n "$lang" ]; then
  template="$template_parent_dir/${lang//\//_}/template" # replace slashes in lang with _
fi

# if [ "$#" -eq 0 ]; then set -- new; fi # default to 'new' if no arguments given
if [ "$#" -eq 0 ]; then abort 'DIR is required' 2; fi

cmd=$(cmdpath "new-$lang")
if [ -x "$cmd" ]; then exec -- "$cmd" "$@"; fi # new-$lang command

# Doesn't exist. Warn the user! Empty string will be caught by `! -d`
if [ -f "$template" ]; then
  log "Using '$template' as the template file"
  [ -x "$template" ] || abort "'$template' is not executable! Aborting!" 1
  exec -- "$template" "$@"
elif ! [ -d "$template" ]; then
  abort "Could not find template directory '$template'. Aborting!" 1
fi
log "Using template directory '$template'"

template=${template%/}                # remove trailing slash
tmp="$(mktemp)" && trap _cleanup EXIT # use one file for all loops
for dest in "$@"; do
  dest=${dest%/} # remove trailing slash
  if [ -z "$dest" ]; then err "refusing to create empty named directory!" && continue; fi
  # Don't overwrite existing files
  if [ -d "$dest" ]; then err "$dest already exists! Please move it or choose a new name" && continue; fi

  log "Creating '$dest'"
  mkdir -p -- "$(dirname -- "$dest")" # Ensure parent directory exists
  cp -ri -- "$template/" "$dest"      # Copy the template directory - Note: The trailing slash is important to copy the target if it's a symlink

  # shellcheck disable=SC2034 # These are dynamically used later
  DATE=$(date '+%m/%d/%Y') TIME=$(date '+%H:%M')

  for f in "$dest"/*; do handle_file_sub "$f"; done
done

_cleanup # Explicitly cleanup if this is reached
