#!/usr/bin/env bash

# ~/.local/bin/update-java
#
# Updates java symlinks to the path specified using update-alternatives
#
set -euC -o pipefail

THIS=update-java
usage() {
  cat <<EOF
$THIS [-y | --yes] <JAVADIR> [priority = 1112] [JVM_VERS_DIR]
Updates java symlinks to the path specified using update-alternatives.
Do not include /bin on JAVADIR.
JVM_VERS_DIR will be determined by JAVA_HOME if set, or else default to /usr/lib/jvm
EOF
  EOF
  return 0
}

log() { printf '%s\n' "$@"; }
err() { printf "${THIS:-$0}: %s\n" "$@" >&2; }
abort() { err "$1" && exit "${2:-1}"; }

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  # -allow a command to fail with !’s side effect on errexit
  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
  # shellcheck disable=SC2251
  ! getopt --test >/dev/null
  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi

  local parsed
  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
    # output getopt’s output this way to handle the quoting right:
    printf '%s' "set -- $parsed"
    return 0
  fi
  # getopt has already complained about wrong arguments to stdout - Exit script
  exit 2
}

LONGOPTS=help,yes
SHORTOPTS=h,y
ARGSTRING="$(parse_args "$@")"
eval "$ARGSTRING"

yes=0
while true; do
  case "$1" in
  -h | --help) usage && exit 0 ;;
  -y | --yes) yes=1 && shift ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done
if [ "$#" -eq 0 ]; then usage && exit 2; fi

JAVADIR=${1:-}
PRIORITY=${2:-1112}
BINDIR=/usr/bin
if [[ -n "${3:-}" ]]; then
  JVM_VERS_DIR=$3
elif [[ -n "${JAVA_HOME:-}" ]]; then
  JVM_VERS_DIR=$(dirname -- "$JAVA_HOME") # /usr/lib/jvm/jdk-version --> /usr/lib/jvm
else
  JVM_VERS_DIR=/usr/lib/jvm
fi

if ! [ -d "$JVM_VERS_DIR" ]; then
  err "'$JVM_VERS_DIR' is not a directory. It will be created on confirmation" "$JVM_VERS_DIR"
fi

if ! [ -d "$JAVADIR" ]; then abort "'$JAVADIR' is not a directory\n" 2; fi
JAVADIR=$(realpath -- "$JAVADIR")

if [[ "$JAVADIR" =~ ?(.*)/bin$ ]]; then
  if [ "$yes" -eq 1 ]; then confirmation=yes; else
    read -rep "$JAVADIR ends in /bin, would you like to use it's parent? (yes) " confirmation >&2
  fi
  if [[ -z "$confirmation" || "${confirmation,,}" =~ ^\s*y(es)?\s*$ ]]; then
    JAVADIR=$(dirname -- "$(realpath -- "$JAVADIR")")
  fi
fi

if ! [ "$yes" -eq 1 ]; then
  read -rep "Are you sure you would like to link all binaries in $JAVADIR? (yes) " confirmation
  if [[ -n "$confirmation" && ! "${confirmation,,}" =~ ^\s*y(es)?\s*$ ]]; then
    abort "Aborting" 1
  fi
fi

# Update sudo timestamp
sudo --validate

sudo mkdir -p "$JVM_VERS_DIR"
JVM_VERS_DIR=$(realpath -- "$JVM_VERS_DIR")

if [[ $(dirname -- "$JAVADIR") != "$JVM_VERS_DIR" ]]; then
  printf 'Copying files to "%s"\n' "$JVM_VERS_DIR" >&2
  sudo -E -H -- cp --archive --interactive "$JAVADIR" "$JVM_VERS_DIR"
  JAVADIR="$JVM_VERS_DIR/$(basename -- "$JAVADIR")"
fi

while read -d $'\0' -sr FP; do
  FN=$(basename -- "$FP")
  printf '%s\n' "update-alternatives --install \"$BINDIR/$FN\" \"$FN\" \"$FP\" \"$PRIORITY\""
  sudo -E -H update-alternatives --install "$BINDIR/$FN" "$FN" "$FP" "$PRIORITY"
done < <(find "$JAVADIR" -perm /u=x,g=x,o=x -type f -print0)

# Link the default-java file to this folder
cmd=(ln -sf -T "$JAVADIR" "$JVM_VERS_DIR/default-java")
log "sudo ${cmd[*]}"
sudo "${cmd[@]}"
unset -v cmd
