#!/usr/bin/env bash
# Sets up rg function for paging rg output, if rg and delta are both available
set -euC -o pipefail
function has_cmd() { command -v -- "$@" &>/dev/null; }

function find_in_path() {
  local path cmd exclude="${2:-${BASH_SOURCE[0]}}"
  cmd=${1%/} cmd="${1##*/}" # remove trailing slash -- then get basename
  while read -r -d: path; do
    path=${path:-$PWD}                         # empty path means pwd
    [ "$path/$cmd" != "$exclude" ] || continue # skip this_file
    [ -x "$path/$cmd" ] || continue
    printf '%s' "$path/$cmd" || true
    return 0
  done < <(printf '%s' "$PATH:")
  printf '%s\n' "$cmd: command not found" >&2 || true
  return 127
}

rg=$(find_in_path rg) || exit
{ [ -t 1 ] && has_cmd delta; } || exec "$rg" "$@" || exit
"$rg" --json "$@" | exec delta
