#!/usr/bin/env bash
# TODO: less "/home/aaron" more "$HOME" -- need to investigate interactions with existing backups
set -euC -o pipefail

# Calls duplicity to run a backup. Passes user arguments to first arguments of duplicity.
# Requires duplicity to be installed

# ----------------------------------------------------------------
# ----------------------------------------------------------------
# ------------------------ CONFIGURATION -------------------------
# ----------------------------------------------------------------
# ----------------------------------------------------------------

# Set the symbolic name of the backup being operated on. The intent is to use a separate name for each logically distinct backup. For example, someone
# may use "home_daily_s3" for the daily backup of a home directory to Amazon S3. The structure of the name is up to the user, it is only important that
# the names be distinct. The symbolic name is currently only used to affect the expansion of --archive-dir , but may be used for additional features in
# the future. Users running more than one distinct backup are encouraged to use this option. If not specified, the default value is a hash of the backend URL.
os=$(. /etc/os-release && printf '%s\n' "${ID:-${NAME:-}}" || printf '')
host=$(uname -n || printf '')
NAME="full-system-$host-$os"

# use '-path' to exclude
# use '+path' or just 'path' to include
# spaces are also permitted after the '+/-' (ie '+ path')
# to use a path starting with '-' or '+', simply pass two of them (ie '--path' and '++path')
# NOTE: order is important. the first matching pattern will be applied. (see man duplicity)

if [ "$HOME" != "/home/aaron" ]; then
  printf '%s\n' "This script is hackish and hardcoded to /home/aaron" >&2
  exit 1
fi

# from man:duplicity:
# The include and exclude options accept some extended shell globbing patterns. These patterns can contain '*', '**', '?', and '[...]'.
# As in a normal shell, '*' can be expanded to any string of characters not containing "/", '?' expands to any character except "/",
# and '[...]' expands to a single character of those characters specified (ranges are acceptable).
# The new special pattern, '**', expands to any string of characters whether or not it contains "/".
# Furthermore, if the pattern starts with "ignorecase:" (case insensitive), then this prefix will be removed and
# any character in the string can be replaced with an upper- or lowercase version of itself.
files=(
  '-/home/aaron/.cache'
  '-/home/aaron/.cache/deja-dup'
  '-/home/aaron/.config/Code'
  '-/home/aaron/.config/TabNine'
  '-/home/aaron/.config/google-chrome'
  '-/home/aaron/.config/google-chrome-static'
  '-/home/aaron/.config/vivaldi'
  '-/home/aaron/.config/vivaldi-static'
  '-/home/aaron/.local/share'
  '-/home/aaron/.local/share/Trash'
  '-/home/aaron/.local/state'
  '-/home/aaron/.luckyBackup/logs'
  '-/home/aaron/.luckyBackup/snaps'
  '-/home/aaron/.thunderbird'
  '-/home/aaron/.var'
  '-/home/aaron/.vscode'
  '-/home/aaron/.xsession-errors'
  '-/home/aaron/.Xauthority'
  '-/home/aaron/Documents/.soh'
  '-/home/aaron/Downloads'
  '-/home/aaron/snap/*/*/.cache'
  '-/home/aaron/vscode/repos'

  '+/home/aaron'

  '-/sys'
  '-/run'
  '-/proc'
  '-/dev'
  '-/dev/shm'
  '-/var/tmp'
  '-/tmp'
  '-/media/aaron/Backup/UbuntuLaptop/duplicity_backup' # don't backup the backup :)
  '-/**/lost+found'
  '-**'
)

# Exclude directories if filename is present. Allows the user to specify folders
# that they do not wish to backup by adding a specified file (e.g. ".nobackup")
# instead of maintaining a comprehensive exclude/include list.
exclude_if_present=(
  'CACHEDIR.TAG'
  '.deja-dup-ignore'
  '.nobackup'
)

# Change the volume size to number MB. Default is 200MB.
VOLSIZE=200

# The source directory *to* backup (usually / or "$HOME")
SOURCE_DIR=/

# Searching for usb drive
external=

# Search for a mountpoint - uuid
dev=UUID=86eb0e3c-c03a-4414-9bfc-f20bef42f2ba
external=$(findmnt -nr -o target -S "$dev") || true

# Search by name - automounted (label)
# usbname=Backup
# for dir in "/media/$USER" "/run/media/$USER"; do
#   if [ -d "$dir" ] && [ -d "$dir/$usbname" ]; then external=file://$dir/$usbname && break; fi
# done

if [ -z "$external" ]; then
  printf '%s\n' "Could not find usb drive for backup. Please check that it's mounted." >&2
  exit 1
fi

# The destination directory to backup *to* (usually a remote location or external storage)
if [ "$host" = "aaron-HP-Laptop-15-dy2xxx" ] && [ "$os" = ubuntu ]; then
  DESTINATION_URI=file://$external/UbuntuLaptop/duplicity_backup
else
  DESTINATION_URI=file://$external/duplicity_backup/$host-$os
fi

# Currently only 'no' is fully supported.
ENCRYPTION_TYPE=no

# Perform a full backup if an incremental backup is requested, but the latest full backup in the collection is older than the given time.
FULL_IF_OLDER=15D

# Use seconds as the socket timeout value if duplicity begins to timeout during network operations. The default is 30 seconds.
TIMEOUT=120
# Specify output verbosity level (log level).
# Named levels and corresponding values are 0 Error, 2 Warning, 4 Notice (default), 8 Info, 9 Debug (noisiest).
#          level may also be a character: e, w, n, i, d
#          or a word: error, warning, notice, info, debug
VERBOSITY=4
# Write specially-formatted versions of output messages to the specified file.  The format used is designed to be easily consumable by other programs.
LOGFILE=

# Delete incremental sets of all backups sets that are older than the count:th last full backup (in other words, keep only old full backups and not their increments).
# count must be larger than zero. A value of 1 means that only the single most recent backup chain will be kept intact.
REMOVE_ALL_INC_OF_BUT_N_FULL=3
# Delete all backup sets older than the given time.  Old backup sets will not be deleted if backup sets newer than time depend on them.
# See the TIME FORMATS section for more information.
REMOVE_OLDER_THAN=3M

# When backing up or restoring, this option specifies that the local archive directory is to be created in path.
# If the archive directory is not specified, the default will be to create the archive directory in ~/.cache/duplicity/.
# ARCHIVE_DIR=~/.cache/duplicity/

# Use this existing directory for duplicity temporary files instead of the system default, which is usually the /tmp directory.
# TEMP_DIR=/tmp

# ----------------------------------------------------------------
# ----------------------------------------------------------------
# -------------------------- PROCESSING --------------------------
# ----------------------------------------------------------------
# ----------------------------------------------------------------

function usage() {
  cat <<-EOF
backup [opts]...

Run a system backup using duplicity.
Pass --full to specify full backup or --incr to specify incremental backup
If neither argument is passed, a full will be made if the most recent full backup is FULL_IF_OLDER old

Flags:
--full,--incr   passed to duplicity to force a full or incremental backup
--help          show this message
--cleanup,-c    Cleanup old backups
--dry-run,-n    Do not run any duplicity commands, just show them (set BACKUP_DRY_RUN to set this)
--verbose,-v    Show all duplicity commands before running them (set BACKUP_VERBOSE to set this)
EOF
}
function log() { printf '%s\n' "$@"; }
function err() { printf '%s\n' "$@" >&2; }
function abort() {
  err "$1"
  exit "${2:-1}"
}

# Array of arguments to pass to duplicity
args=()

cleanup=0
command=() # an array for the sake of empty strings (allows to skip the command and dynamically create full backups)
for arg in "$@"; do
  case "$arg" in
  --full | --incr) command=("${arg#--}") ;;
  --help | -h) usage && exit 0 ;;
  --cleanup | -c) cleanup=1 ;;
  --dry-run | -n) BACKUP_DRY_RUN=1 ;; # overrides environment variables
  --verbose | -v) BACKUP_VERBOSE=1 ;; # overrides environment variables
  --*) abort "Unknown option: '$arg'" ;;
  -*) abort "Unknown option: '$arg'" ;;
  *) abort "this script does not support positional arguments" ;;
  esac
done

log ''
log "--- Backup at $(date) ---"
log ''

if [ -z "${DUPLICITY:-}" ]; then
  if ! command -v which &>/dev/null; then
    abort "Which is required to find duplicity in PATH. Plese ensure it is installed or set \$DUPLICITY variable." 1
  fi
  DUPLICITY=$(which duplicity 2>/dev/null || printf '')
fi
# Ensure duplicity can be accessed
if [ -z "$DUPLICITY" ]; then
  abort "Could not find duplicity. Please ensure it is installed" 1
elif ! [ -x "$DUPLICITY" ]; then
  abort "Could not run '$DUPLICITY'. Please ensure it is executable." 3
fi

# include/exclude
for pat in "${files[@]}"; do
  case "$pat" in
  '- '*) args+=("--exclude=${pat#- }") ;; # '- path' -> '--exclude=path'
  -*) args+=("--exclude=${pat#-}") ;;     # '-path' -> '--exclude=path'

  '+ '*) args+=("--include=${pat#+ }") ;; # '+ path' -> '--include=path'
  +*) args+=("--include=${pat#+}") ;;     # '+path' -> '--include=path'

  *) args+=("--include=$pat") ;; # 'path' -> 'include=path'
  esac
done

# exclude-if-present
for file in "${exclude_if_present[@]}"; do
  args=("${args[@]}" "--exclude-if-present=$file")
done

# volsize
args=("${args[@]}" "--volsize=$VOLSIZE")

# Encryption
if [ "$ENCRYPTION_TYPE" = 'no' ]; then
  args=("${args[@]}" "--no-encryption")
fi

# verbosity
if [ -n "${VERBOSITY:-}" ]; then
  args=("${args[@]}" "--verbosity=$VERBOSITY")
fi

# timeout
if [ -n "${TIMEOUT:-}" ]; then
  args=("${args[@]}" "--timeout=$TIMEOUT")
fi

# archive-dir
if [ -n "${ARCHIVE_DIR:-}" ]; then
  args=("${args[@]}" "--archive-dir=$ARCHIVE_DIR")
fi

# tempdir
if [ -n "${TEMP_DIR:-}" ]; then
  args=("${args[@]}" "--tempdir=$TEMP_DIR")
fi

# log-file
if [ -n "${LOGFILE:-}" ]; then
  args=("${args[@]}" "--log-file=$LOGFILE")
fi

# name
if [ -n "${NAME:-}" ]; then
  args=("${args[@]}" "--name=$NAME")
fi

# ----------------------------------------------------------------
# ----------------------------------------------------------------
# -------------------------- EXECUTION ---------------------------
# ----------------------------------------------------------------
# ----------------------------------------------------------------

function verbose() {
  # a dry-run likely wants to be verbose
  if [ -n "${BACKUP_VERBOSE:-}" ] || [ -n "${BACKUP_DRY_RUN:-}" ]; then
    printf "'%s' " "$@" # print it
    printf '\n'
  fi
  if [ -z "${BACKUP_DRY_RUN:-}" ]; then
    "$@" # run it
  fi
}

if [ "${#args[@]}" -eq 0 ]; then
  abort "No arguments were specified. Something went wrong" 3
fi

if [ "$cleanup" -eq 0 ]; then
  log "Backing up to $DESTINATION_URI"
  verbose "$DUPLICITY" --full-if-older-than="${FULL_IF_OLDER:-1M}" "${command[@]}" "${args[@]}" -- "$SOURCE_DIR" "$DESTINATION_URI"
else
  log "Cleaning up $DESTINATION_URI"
  did_something=0
  if [ -n "${REMOVE_OLDER_THAN:-}" ]; then # only if defined
    log "Removing backups older than $REMOVE_OLDER_THAN"
    did_something=1
    command=(remove-older-than "$REMOVE_OLDER_THAN" --force)
    verbose "$DUPLICITY" "${command[@]}" "${args[@]}" -- "$DESTINATION_URI"
  fi
  if [ -n "$REMOVE_ALL_INC_OF_BUT_N_FULL" ]; then # only if defined
    log
    log "Removing all incremental backups except for $REMOVE_ALL_INC_OF_BUT_N_FULL of full at $DESTINATION_URI"
    did_something=1
    command=(remove-all-inc-of-but-n-full "$REMOVE_ALL_INC_OF_BUT_N_FULL" --force)
    verbose "$DUPLICITY" "${command[@]}" "${args[@]}" -- "$DESTINATION_URI"
  fi
  if [ "$did_something" -eq 0 ]; then abort "Didn't do anything. Please check your configuration and try again." 2; fi
fi

log
log "Verifying $DESTINATION_URI"
verbose "$DUPLICITY" verify "${args[@]}" -- "$DESTINATION_URI" "$SOURCE_DIR"
