#!/bin/bash
set -euC -o pipefail
shopt -s nullglob # Globs with no match result in NUL string

THIS=snap-cleanup
# Color settings
YELLOW_COLOR="$(tput setaf 3 2>/dev/null || printf '')"
RED_COLOR="$(tput setaf 1 2>/dev/null || printf '')"
OFF_COLOR="$(tput sgr0 2>/dev/null || printf '')"

# Set English language
LANG=en_US.UTF-8

usage() {
  cat <<EOF
$THIS [options] [--] [arguments]
Cleans up the excess snap revisions and files. Use \$SUDO to change the program used.
the environment variable \`SUDO\` can be set to use a different
program for root elevation. It will be split by the shell, so
spaces in the program name will likely be mutilited.

Options:
-h, --help        show this message
-y, --yes         Don't ask for confirmation
EOF
  return 0
}

log() { printf '%s\n' "$@"; }
color() { printf '%b' "$@"; }
err() { printf "$RED_COLOR$THIS: %s\n$OFF_COLOR" "$@" >&2; }
abort() {
  err "$1"
  exit "${2:-1}"
}
# use like `"${sudo[@]}" do_something`
# shellcheck disable=SC2206 # Splitting is intentional.
sudo=(${SUDO:-sudo})
[ "$(id -u)" -eq 0 ] && sudo=()

# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  local parsed
  local code=0 && getopt --test &>/dev/null || code=$?
  if [ "$code" -ne 4 ]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
  parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@") ||
    exit 2                     # getopt has already complained about wrong arguments to stdout - Exit script
  printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
}

# option --long/-l requires 1 argument
LONGOPTS=help,yes SHORTOPTS=h,y
ARGSTRING="$(parse_args "$@")"
eval "$ARGSTRING"

yes=0
while true; do
  case "$1" in
  -h | --help) usage && exit 0 ;;
  -y | --yes) yes=1 && shift ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

# Current status
USED_BEFORE="$(df -k / | awk 'NR>1 {print $3}')"

# snapd revisions clean
if [ -x "$(command -v snap)" ]; then
  # shellcheck disable=SC2162
  if [ "$yes" = "0" ]; then
    read -p "> Do you want to remove unused snapd revisions? [Y/n] " KEY
    KEY="${KEY:0:1}" && KEY="${KEY,,}"
    if [ -n "$KEY" ] && [ "$KEY" != "y" ]; then abort "aborting" 2; fi
  fi
  # remove unused snapd revisions
  log "Removing unused snapd revisions..."
  "${sudo[@]}" snap set system refresh.retain=2
  "${sudo[@]}" snap list --all | awk '/disabled/ {print $1, $3}' |
    while read -r SNAP_NAME SNAP_REV; do
      "${sudo[@]}" snap remove "${SNAP_NAME}" --revision="${SNAP_REV}"
    done
  if [ -d /var/lib/snapd/cache ]; then
    for file in /var/lib/snapd/cache/*; do
      "${sudo[@]}" rm "$file"
    done
  fi
  log "Nothing unused to uninstall"
fi

# Current status
USED_AFTER="$(df -k / | awk 'NR>1 {print $3}')"

# Summary
color "${YELLOW_COLOR}"
log "Freed up space: $(((USED_BEFORE - USED_AFTER) / 1024)) MB"
color "${OFF_COLOR}"
