#!/usr/bin/env bash
#
# This file echoes a bunch of color codes to the
# terminal to demonstrate what's available.  Each
# line is the color code of one forground color,
# out of 17 (default + 16 escapes), followed by a
# test use of that color on all nine background
# colors (default + 8 escapes).
#
set -euC -o pipefail

## UTILS ##################################
THIS='colors'
function usage() {

  cat <<EOF
$THIS [options]
Echoes all the color codes to the terminal to demonstrate what's
available. Each line is the color code of one forground color,
out of 17 (default + 16 escapes), followed by a test use of that
color on all nine background colors (default + 8 escapes).

OPTIONS:
  -h, --help      display this help message
EOF
  return 0
}
function log() { printf '%s\n' "$@"; }
function err() { printf "$THIS: %s\n" "$@" >&2; }
function abort() {
  err "$1"
  exit "${2:-1}"
}

## PARSE ARGS #############################
# Returns a string that should be 'eval'ed to set the positional arguments
# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
# Input: $LONGOPTS,$SHORTOPTS
# eval "$(parse_args "$@")"
function parse_args() {
  local parsed
  local code=0 && getopt --test &>/dev/null || code=$?
  if [ "$code" -ne 4 ]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
  parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@") ||
    exit 2                     # getopt has already complained about wrong arguments to stdout - Exit script
  printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
}

LONGOPTS=help SHORTOPTS=h
ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit

for arg; do
  case "$arg" in
  --help | -h) usage && exit 0 ;;
  --) shift && break ;;
  *) abort "This is a bug" 3 ;;
  esac
done

## VARS ###################################
T='T'              # The test text
declare -i W_COL=5 # The width of the widest column (FG)

BGs=(49m 40m 41m 42m 43m 44m 45m 46m 47m)
FGs=('m' '1m' '30m' '1;30m' '31m' '1;31m' '32m' '1;32m' '33m'
  '1;33m' '34m' '1;34m' '35m' '1;35m' '36m' '1;36m' '37m' '1;37m')

## HEADER #################################
printf '\n'
printf "%${W_COL}s " "" # indent
printf " %3s " "${BGs[@]}"
printf '\n' # newline

## ROW ####################################
for FG in "${FGs[@]}"; do
  printf "%${W_COL}s " "$FG"
  ## COLUMN ##
  for BG in "${BGs[@]}"; do
    printf "\033[%s\033[%s  %s  \033[0m" "$FG" "$BG" "$T"
  done
  printf '\n'
done
printf '\n'
