#!/usr/bin/env bash
set -euC -o pipefail
# usage: visual awesome :2 || visual :3 || visual || visual awesome args -- :3
THIS=visual
function usage() {
  cat <<EOF || true
Usage: $THIS [-t|-h] [client] [client-args --] [:display] 
Run an X server and a client.

if run without arguments, x-window-manager will be used
server will be found in the \$PATH. 
if \$2 is not a valid server and a client is provided,
the arguments will be passed directly to the startx script

If -t is passed as the first argument, the server will be detected but not started.
This can be used to determine if a subsequent run will succeed.
EOF
}

function log() { printf '%s\n' "$@" || true; }
function err() { printf "%s\n" "$@" >&2 || true; }
function abort() { err "$1" && exit "${2:-1}"; }
function has_cmd() { command -v "$@" &>/dev/null; }
function cmd_path() { command -v "$@"; }
function first_cmd() {
  local c && for c; do
    has_cmd "$c" || continue
    printf '%s' "$c" || true
    return 0
  done
  return 1
}
function verbose() {
  printf '%s\n' "> ${*@Q}" || true
  # If this is a dry run, exit here because we don't need to do anything else
  [ "$dry_run" -eq 0 ] || return 0
  "$@"
}

has_cmd startx || abort "startx is required for this script" 1

dry_run=0
case "${1:-}" in
-h | --help) usage && exit 0 ;;
-t) dry_run=1 && shift ;;
esac

wm=${1:-}
server=${2-}
rest=("${@:3}")

is_integer() { [ -n "$1" ] && case "$1" in *[!0123456789]*) return 1 ;; esac }
# returns true if the argument is a valid display number (:integer)
is_display() { [ -n "$1" ] && [ "${1:0:1}" == ":" ] && is_integer "${1#:}"; }

# visual -- [:3] --server-args
if [ "$wm" == '--' ]; then
  wm='' server=--
  rest=("${@:2}") # [:3] --server-args
fi

# visual :3
if [ -z "$server" ] && is_display "$wm"; then server="$wm" wm=''; fi

# visual :3 OR visual awesome
[ -n "$wm" ] || wm=$(first_cmd x-window-manager x-terminal-emulator) || abort "Could not find a default window manager!"

wmpath=$(cmd_path "$wm") || abort "$wm: command not found" 2
cmd=()
# HACK: startx on ubuntu still unsets DBUS_SESSION_BUS_ADDRESS (even though it's fixed in upstream)
# IF this is the case, call it again with *this* script as the wm.
if [ -z "${__IN_VISUAL_SPAWN:-}" ]; then
  startx=$(cmd_path startx) || abort "startx: command not found" 1
  cmd=("$startx")
  if grep -q 'unset DBUS_SESSION_BUS_ADDRESS' "$startx"; then
    export __IN_VISUAL_SPAWN=1
    cmd+=("${BASH_SOURCE[0]}")
  fi
fi
cmd+=("$wmpath")

# if server is defined
if is_display "$server"; then cmd+=(--); fi
if [ -n "$server" ]; then cmd+=("$server"); fi
cmd+=("${rest[@]}")

# from /etc/X11/Xsession.d/20dbus_xdg-runtime
if [ -z "${DBUS_SESSION_BUS_ADDRESS:-}" ] && [ -n "${XDG_RUNTIME_DIR:-}" ] &&
  [ "$XDG_RUNTIME_DIR" = "/run/user/$(id -u)" ] && [ -S "$XDG_RUNTIME_DIR/bus" ]; then
  # We are under systemd-logind or something remarkably similar, and
  # a user-session socket has already been set up.
  #
  # Be nice to non-libdbus, non-sd-bus implementations by using
  # that as the session bus address in the environment. The check for
  # XDG_RUNTIME_DIR = "/run/user/`id -u`" is because we know that
  # form of the address, from systemd-logind, doesn't need escaping,
  # whereas arbitrary addresses might.
  DBUS_SESSION_BUS_ADDRESS="unix:path=$XDG_RUNTIME_DIR/bus"
  export DBUS_SESSION_BUS_ADDRESS
fi

if [ -z "${XAUTHORITY:-}" ] && [ -d "${XDG_RUNTIME_DIR:-}" ]; then
  # NOTE: this path was chosen because it is permitted in the default AppArmor config.
  # See /etc/apparmor.d/abstractions/X.
  export XAUTHORITY="$XDG_RUNTIME_DIR/X11/Xauthority"
  verbose mkdir -p -- "$(dirname "$XAUTHORITY")" # Ensure the directory exists
  verbose touch -- "$XAUTHORITY"
fi

verbose exec "${cmd[@]}"
