#!/usr/bin/env bash
function err() { printf '%s\n' "$@" >&2; }
function log() { printf '%s\n' "$@"; }
function abort() {
  err "$1"
  exit "${2:-1}"
}

if [ "$#" -lt 1 ]; then
  err "usage: $0 <dir>..."
fi

date=$(date '+%m/%d/%Y')

for dir in "$@"; do
  dir=${dir%/} # strip trailing slash
  if [ -e "$dir" ] || [ -L "$dir" ]; then
    abort "file '$dir' already exists. Please move it or create a new name." 1
  fi
  classname=$(basename "$dir")
  cp -T -ri ~/code/java/template/ "$dir"
  for f in "$dir"/*; do
    fbn=$(basename "$f")
    fdn=$(dirname "$f")
    mv "$f" "$fdn/${fbn/ClassName/$classname}"
  done
  # okish since $classname can't contain any slashes
  sed -i "s/ClassName/$classname/g" "$dir/$classname.java"
  sed -i "s|\${DATE}|$date|g" "$dir/$classname.java"
done
