bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!" # quick reload

set -g mouse on
set -g mode-keys vi
set-option -g history-limit 10000
set -g renumber-windows on
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"
set -g allow-rename on # Allow escape codes to set window name

set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',screen-256color:RGB'
