#!/usr/bin/env bash
# Adds to chezmoi and adds to ~/.bashrc.d/30_functions/_update-config
# Imitates config add (without dash)

set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=../script_utils.sh
. "$utils"
USE_COLOR=1 # Enable color
this=$(get_script_path) || abort "Could not find current script path" 3
# shellcheck source=./common.sh
. "$(dirname -- "$this")/common.sh"

files=()
for file in "$@"; do
  [ -e "$file" ] || { err "$file is not a file" && continue; }
  [ -r "$file" ] || { err "$file is not readable (try cproot instead)" && continue; }
  # add to the array so i can update all at once
  file="$(resolve_path "$file" -s)"
  case "$file" in
  "$target"/*) files+=("$file") ;;
  *) err "$file is not under target directory: $target" ;;
  esac
done

[ "${#files[@]}" -gt 0 ] || abort "No files found" 1

chezmoi add --exact -- "${files[@]}" # Add all files to chezmoi repo

short_files=("${files#"$target/"}") # make relative to target
# Add files to the _update-config file
for file in "${short_files[@]}"; do
  ! grep -Fxq "$file" "$CONFIG_FILE" || continue
  printf '%s\n' "$file" >>"$CONFIG_FILE"
done

case "$(resolve_path "$CONFIG_FILE")" in
"$CHEZMOI_DIR"/*)
  log 'Committing config changes'
  commit_msg="Update autoupdate file: $(join ", " "${short_files[@]}")"
  update_file "$commit_msg" "$CONFIG_FILE"
  ;;
esac
