#!/usr/bin/env bash
set -euC -o pipefail && shopt -s nullglob globstar
utils=script_utils.sh dir=$(dirname -- "${BASH_SOURCE[0]}") || true
if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
# shellcheck source=../script_utils.sh
. "$utils"

USE_COLOR=1 # Enable color

this=$(get_script_path) || abort "Could not find current script path" 3
# shellcheck source=./common.sh
. "$(dirname -- "$this")/common.sh"
cd "$target" # add from target so files are relative to target
check_dependencies chezmoi yes basename

if has_cmd crontab; then # Update crontab backup
  crontab -l >|"$CRONTAB_FILE"
fi

# Finds files line-by-line
files=() dirs=()
add=()
[ -r "$CONFIG_FILES" ] || abort "Could not find config file list: ${CONFIG_FILES}"
while IFS= read -r file || [ -n "$file" ]; do
  file=$(trim "$file")                 # Strip leading and trailing whitespace
  [ -n "$file" ] || continue           # ignore empty lines
  [ "${file:0:1}" != "#" ] || continue # ignore lines starting with #

  is_managed "$file" || { add+=("$file") && continue; }
  has_changed "$file" || continue

  type=$(file_type "$file" -s) || { err "$file is not a file!" && continue; }
  case "$type" in
  directory) dirs+=("$file") ;;
  *) files+=("$file") ;;
  esac
done <"$CONFIG_FILES"

if [ "${#files[@]}" -gt 0 ] || [ "${#dirs[@]}" -gt 0 ]; then

  # Output a detail of which files are changing
  changed_files=$(chezmoi status -- "${files[@]}")
  changed_dirs=$(chezmoi status -- "${dirs[@]}")

  log 'Changed files:'
  [ -z "$changed_files" ] || log "$changed_files"
  [ -z "$changed_dirs" ] || log "$changed_dirs"

  # HACK: don't force a tty prompt, instead just take my no.
  # Note: yes will get killed by sigpipe
  { yes no || true; } | {
    chezmoi add --secrets ignore --exact --no-tty -- "${dirs[@]}" >/dev/null
    chezmoi add --secrets ignore --no-tty -- "${files[@]}" >/dev/null
  }
fi
chezmoi re-add # Ensure everything else is updated
if [ "${#add[@]}" -gt 0 ]; then
  log "You have included files in the list which are not managed."
  log "Run the following command to manage them:"
  print_cmd chezmoi add --exact -- "${add[@]}"
fi

# --------------------------------------------
# --------------------------------------------
# --------------- Update dconf ---------------
# --------------------------------------------
# --------------------------------------------

dconf dump / >|"$DCONF_BACKUP"
# Save to chezmoi
dconf_path="$source/encrypted_dconf-backup.ini"
commit_msg="Update $(basename -- "$DCONF_BACKUP")"
if ! cmp -s "$DCONF_BACKUP" <(chezmoi decrypt -- "$dconf_path"); then
  log 'Updating dconf backup'
  chezmoi encrypt "$DCONF_BACKUP" -o "$dconf_path"
  chezmoi git -- add "$dconf_path"
  chezmoi git -- commit --quiet -m "$commit_msg"
  chezmoi git -- push --quiet
fi

verbose chezmoi status
