#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/gsudo
#
# Creates a `gsudo` function that runs a GUI application as root
#
function gsudo() {
  pkexec env DISPLAY="$DISPLAY" XAUTHORITY="$XAUTHORITY" "$@"
}
