#! /usr/bin/env bash

# ~/.bashrc.d/30_functions/update-config
#
# Creates an update-config function to call chezmoi add on
# every file in _update-config
# Creates a cproot function to cp a file to ~/.root/FILEPATH
# and calls chezmoi add on it.
#

function update-config() (
  declare -a files
  declare target
  # Finds files line-by-line, ignoring the first 3 lines
  readarray -t files <<<"$(tail -n+4 -- ~/.bashrc.d/30_functions/_update-config)"
  if target=$(chezmoi target-path); then
    printf '%s\n' "Press 'n' if asked about encrypted files. They will still be updated!"
    # add from target so files are relative to target
    (cd "$target" && chezmoi add -- "${files[@]}")
    # Ensure everything is updated
    chezmoi re-add
  else
    return 2
  fi
  # Update dconf
  dconf dump / >|$(chezmoi source-path)/dconf-backup.ini
  chezmoi git add $(chezmoi source-path)/dconf-backup.ini &&
    chezmoi git -- commit -m 'update dconf-backup.ini' &&
    chezmoi git -- push
)

# Copies the files to $HOME/.root/FILEPATH. `.root` should be backed up
function cproot() {
  declare -i exitCode=0
  declare -a opts args
  opts=()
  args=()
  for arg; do
    if [[ "$arg" == --?* ]]; then
      opts+=("$arg")
    else
      args+=("$arg")
    fi
  done
  files=()
  for file in "${args[@]}"; do
    if [[ -e "$file" ]]; then
      local old_path new_dir new_path
      old_path="$(realpath -s -- "$file")"
      new_path="$HOME/.root$old_path"
      new_dir="$(dirname -- "$new_path")"
      # ensure destination exists
      mkdir -p "$new_dir"
      # cp to home, so files are relative to home.
      sudo cp -r "$file" "$new_dir"
      sudo chown --preserve-root -hR "$(whoami)" "$new_path"
      # add to the array so i can update all at once
      files+=("$new_path")
    else
      printf '%s is not a file\n' "$file"
      # Exit 1 at end if any args were invalid
      exitCode=1
    fi
  done
  # Add all files to chezmoi repo
  chezmoi add "${opts[@]}" -- "${files[@]}"

  # Exit with the saved code
  return $exitCode
}

function update-root-config() {
  local files rootpath homepath dotroot encrypted_files add_files
  dotroot="$HOME/.root"
  encrypted_files=()
  add_files=()
  while IFS= read -r -d $'\0' file; do
    rootpath="/$file"
    homepath="$dotroot/$file"
    if sudo cmp --quiet "$rootpath" "$homepath"; then
      # if same, move on
      continue
    fi
    # Doesn't need to be recursive bc is only files, not dirs.
    sudo cp -f -- "$rootpath" "$homepath"
    sudo chown --preserve-root -h -- "$(whoami)" "$homepath"

    #  Fails if not encrypted
    if [[ -n "$(chezmoi list --include=encrypted -- "$homepath")" ]]; then
      encrypted_files+=("$homepath")
    else
      add_files+=("$homepath")
    fi
  done < <(find "$dotroot" -type f -printf '%P\0')

  test ${#add_files[@]} -gt 0 && chezmoi add -- "${add_files[@]}"
  test ${#encrypted_files[@]} -gt 0 && chezmoi add --encrypt -- "${encrypted_files[@]}"
  if test ${#add_files[@]} -eq 0 && test ${#encrypted_files[@]} -eq 0; then
    echo "No files have changed (dirs not recursive)"
  fi
  return 0
}

# Adds to chezmoi and adds to ~/.bashrc.d/30_functions/_update-config
function add-config() {
  declare -i exitCode=0
  local file
  files=()
  for file in "$@"; do
    if [[ -r "$file" ]]; then
      # add to the array so i can update all at once
      files+=("$(realpath -s -- "$file")")
    else
      printf '%s is not a file\n' "$file"
      # Exit 1 at end if any args were invalid
      exitCode=1
    fi
  done

  # Add all files to chezmoi repo
  chezmoi add "${files[@]}"
  # Add files to the _update-config file
  for file in "${files[@]}"; do
    local short_file=${file#"$HOME"/} # remove /home/user/
    # If not already in the file
    if ! grep -F -x -q "$short_file" ~/.bashrc.d/30_functions/_update-config; then
      printf '%s\n' "$short_file" >>~/.bashrc.d/30_functions/_update-config
    fi
  done

  # Exit with the saved code
  return $exitCode
}
