" Set 'nocompatible' to ward off unexpected things that your distro might
" have made, as well as sanely reset options when re-sourcing .vimrc
set nocompatible

" Set tab and >> to be 2 spaces in bash files
autocmd FileType sh setlocal shiftwidth=2 tabstop=2 softtabstop=2 

" Change .conf syntax highlighting
autocmd BufEnter,BufRead *.conf setf dosini

if !has('nvim')
    " Create :W command to write as sudo
    command W :w !sudo tee %  > /dev/null
else
   " Create warning on :W command if in neovim 
   command W :echom "Running commands in neovim doesn't connect stdin to tty"
endif

" Plugins using vim-plug
"
"

if !has('autocmd') || !has('eval')
    echom 'Sorry, autocmd is not supported in this version of vim. Aborting plugin initiation.'
else
    " Install vim-plug
    let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
    if empty(glob(data_dir . '/autoload/plug.vim'))
      silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    endif

    " Run PlugInstall if there are missing plugins
    autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) | PlugInstall --sync | source $MYVIMRC | endif

    call plug#begin()
    " Plug code here

    if executable('sudo')
        " Setup suda.vim
        Plug 'lambdalisue/suda.vim' 
        " Config suda.vim to auto open restricted files
        let g:suda_smart_edit = 1
    endif

    call plug#end()
endif
