" Set 'nocompatible' to ward off unexpected things that your distro might
" have made, as well as sanely reset options when re-sourcing .vimrc
set nocompatible

" Stop recording of dir history
let g:netrw_dirhistmax=0

" Set tab and >> to be 2 spaces in bash files
autocmd FileType sh setlocal shiftwidth=2 tabstop=2 softtabstop=2 

" Change .conf syntax highlighting
autocmd BufEnter,BufRead *.conf setf dosini

" Create :W command to write as sudo
if !has('nvim')
    command W :w !sudo tee %  > /dev/null
else
   " Create warning on :W command if in neovim 
   command W :echom "Running commands in neovim doesn't connect stdin to tty"
endif

" Plugins using vim-plug
"
"

function! Cond(cond, ...)
  let opts = get(a:000, 0, {})
  return a:cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction

if !has('autocmd') || !has('eval') | echom 'Sorry, autocmd is not supported in this version of vim. Aborting plugin initiation.'
else
    " Install vim-plug
    let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
    if empty(glob(data_dir . '/autoload/plug.vim'))
      silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    endif

    " Run PlugInstall if there are missing plugins
    autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) | PlugInstall --sync | source $MYVIMRC | endif

    call plug#begin()
    " Plug code here

    " Setup suda.vim
    Plug 'lambdalisue/suda.vim', Cond(executable('sudo'))
    " Config suda.vim to auto open restricted files
    let g:suda_smart_edit = 1

    " Install YouCompleteMe for inline-completions
    Plug 'ycm-core/YouCompleteMe', { 'do': './install.py --all' }
    
    " Install ultisnips for snippets.
    Plug 'SirVer/ultisnips'
    " Snippets are separated from the engine. Add this if you want them:
    Plug 'honza/vim-snippets'
    let g:UltiSnipsExpandTrigger="<C-`>"
    let g:UltiSnipsJumpForwardTrigger="<C-b>"
    let g:UltiSnipsJumpBackwardTrigger="<C-z>"

    call plug#end()
endif
