" Set 'nocompatible' to ward off unexpected things that your distro might
" have made, as well as sanely reset options when re-sourcing .vimrc
set nocompatible

" Set leader key. Any references must be after!
let mapleader = ','

" Stop recording of dir history
let g:netrw_dirhistmax=0

" Set tab and >> to be 2 spaces in bash files
autocmd FileType sh setlocal shiftwidth=2 tabstop=2 softtabstop=2 

" Change .conf syntax highlighting
autocmd BufEnter,BufRead *.conf setf dosini

" Create :W command to write as sudo
if !has('nvim')
    command W :w !sudo tee %  > /dev/null
else
   " Create warning on :W command if in neovim 
   command W :echom "Running commands in neovim doesn't connect stdin to tty"
endif

" Plugins using vim-plug
"
"

function! Cond(cond, ...)
  let opts = get(a:000, 0, {})
  return a:cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction

if !has('autocmd') || !has('eval') | echom 'Sorry, autocmd is not supported in this version of vim. Aborting plugin initiation.'
else
    " Install vim-plug
    let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
    if empty(glob(data_dir . '/autoload/plug.vim'))
      silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    endif

    " Run PlugInstall if there are missing plugins
    autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) | PlugInstall --sync | source $MYVIMRC | endif

    call plug#begin()
    " Plug code here

    " Setup suda.vim
    Plug 'lambdalisue/suda.vim', Cond(executable('sudo'))
    " Config suda.vim to auto open restricted files
    let g:suda_smart_edit = 1

    " Install YouCompleteMe for inline-completions
    Plug 'ycm-core/YouCompleteMe', { 'do': './install.py --all' }
    " Handle completion keys
    let g:ycm_key_list_select_completion = ['<C-j>', '<DOWN>']
    let g:ycm_key_list_previous_completion = ['<C-k>', '<UP>']
    let g:ycm_key_list_stop_completion = ["<Enter>"]
    
    " Install ultisnips for snippets.
    Plug 'SirVer/ultisnips'
    " Snippets are separated from the engine. Add this if you want them:
    Plug 'honza/vim-snippets'
    " Handle snippet keys. Avoid conflict with YCM
    let g:UltiSnipsExpandTrigger = "<C-l>"
    let g:UltiSnipsJumpForwardTrigger = "<C-j>"
    let g:UltiSnipsJumpBackwardTrigger = "<C-k>"
    let g:UltiSnipsSnippetDirectories = ['~/.vim/UltiSnips', 'UltiSnips']
    let g:UltiSnipsEditSplit="vertical"

    " Plugin to add brackets, quotes, etc
    Plug 'raimondi/delimitmate'
    " Plugin to show unbalanced brackets
    Plug 'vim-scripts/Highlight-UnMatched-Brackets'
    " Give motions to sorround values/replace deliminators
    Plug 'tpope/vim-surround'
    
    " Shows +- Icons in gutter for git differences
    Plug 'airblade/vim-gitgutter'

    " The status bar
    Plug 'vim-airline/vim-airline'

    Plug 'ctrlpvim/ctrlp.vim'
    let g:ctrlp_working_path_mode = 'ra'
    let g:ctrlp_root_markers = ['package.json', 'node_modules']
    let g:ctrlp_switch_buffer = 'et'
    let g:ctrlp_custom_ignore = '^(\.git|node_modules)$'

    " Install nerdtree for file navigation
    Plug 'scrooloose/nerdtree'

    call plug#end()
endif
