#!/usr/bin/env bash

# ~/.bashrc.d/03_secrets
#
# Stores variables and functions which contain
# secret information which should be encrypted
#

# Release-it Github Key
export RELEASE_IT_GITHUB_KEY='***REMOVED***'
# Bitwarden session key
export BW_SESSION='***REMOVED***'
# freedesktop gitlab token
export FREEDESKTOP_GITLAB_TOKEN='***REMOVED***'
