#!/usr/bin/env bash
# this finds the largest swap partition and *offers* to replace important instances of the backed up source with the uuid
set -euC -o pipefail
# Source utils
SOURCE_DIR="${CHEZMOI_SOURCE_DIR:-"$(chezmoi source-path)"}"
# shellcheck source=../.utils.sh
. "$SOURCE_DIR/.chezmoiscripts/.utils.sh"

GRUB_KBD_FILE=/etc/default/grub.d/keyboard.cfg
confirm "Would you like to set intel keyboard to reset on boot?" || exit 0

# Setup grub config file
cat <<EOF | sudo_cmd tee "$GRUB_KBD_FILE" >/dev/null
#!/usr/bin/env sh
# THIS FILE IS AUTOGENERATED. Edits will likely be lost.
GRUB_CMDLINE_LINUX_DEFAULT="\$GRUB_CMDLINE_LINUX_DEFAULT i8042.reset atkbd.reset=1 i8042.dumbkbd i8042.direct"
EOF

success
log "Run this command to use the changes:" "'update-grub'" "Press enter to continue."
# Make sure the user reads this!
wait_key
