#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/bak
#
# Creates a bak function that moves a 'file' to 'file.bak' and vice-versa
#
function bak() {
  [ "$#" -eq 1 ] || {
    printf '%s\n' "usage: ${FUNCNAME[0]} <FILE>" >&2 || true
    return 2
  }
  local dest src="$1"
  case "$src" in
  *.bak) dest="${src%.bak}" ;; # move back to original location
  *) dest="$src.bak" ;;
  esac
  ! [ -e "$dest" ] || rm -ri -- "$dest" || {
    printf '%s\n' "Aborting remove $dest!" >&2 || true
    return 1
  }
  mv -i -- "$src" "$dest"
}
complete -f bak
