#! /usr/bin/env bash

# ~/.bashrc.d/30_functions/contents
#
# Creates a function to read the contents of a file or executable
# *Follows Symlinks*
#

contents() {
  local filein

  if [ "$1" = "--help" ]; then
    printf '%s\n\n%s\n' "contents [file|executable]" "outputs the contents of a file, calls which if file is not found"
    return 0
  fi
  filein=$1
  # If not a file, try which
  [ -f "$filein" ] || filein=$(which "$filein" 2>/dev/null || printf '%s' "$filein")
  # If not found path
  if ! [ -f "$filein" ]; then
    printf '%s is not a file\n' "$1" >&2
    return 1
  fi
  cat "$filein"
}
