#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/fp
#
# Sets up fp function for fuzzy finding files, and
# fpd function to fuzzy find directories. Each command displays a
# preview through bat/cat and tree/ls respectively.
#
# Also sets default fzf command for direct invocations
#
# By default is colorized, but can be disabled by unsetting FZF_USE_COLOR
# Important: Also unset FZF_DEFAULT_OPTS to accelerate scanning!
#

# only do these if fzf exists
if ! command -v fzf &>/dev/null; then
  return
fi
# Allow color, slows down scanning!
export FZF_USE_COLOR=true
export FZF_DEFAULT_OPTS='--ansi'

# Use better find if installed
if command -v fd &>/dev/null; then
  # Echo if FZF_USE_COLOR is set
  FZF_BASE_COMMAND() { fd --follow --hidden --exclude .git "$@"; }
  FZF_FIND_DIR() {
    FZF_BASE_COMMAND "$(test "$FZF_USE_COLOR" && printf -- "--color=always")" --type d . "$1"
  }
  FZF_FIND_FILE() {
    FZF_BASE_COMMAND "$(test "$FZF_USE_COLOR" && printf -- "--color=always")" --type f . "$1"
  }
else
  FZF_BASE_COMMAND() { find "$@"; }
  FZF_FIND_DIR() { FZF_BASE_COMMAND "$1" --type d; }
  FZF_FIND_FILE() { FZF_BASE_COMMAND "$1" --type f; }
fi

# Use better cat if installed
if command -v bat &>/dev/null; then
  FZF_CAT_CMD() {
    local use_color
    use_color=$(test "$FZF_USE_COLOR" && printf -- "--color=always")
    # shellcheck disable=SC2086
    bat --style=numbers $use_color "$@" | head -n 500
  }
  FZF_CAT_CMD_JSON() { cat - | FZF_CAT_CMD "--language" "JSON" "-"; }

else
  FZF_CAT_CMD() { cat -; }
  FZF_CAT_CMD_JSON() { cat - | FZF_CAT_CMD; }
fi

if command -v tree &>/dev/null; then
  FZF_DIR_PREVIEW() {
    local use_color
    use_color=$(test "$FZF_USE_COLOR" && printf -- "-C")
    # shellcheck disable=SC2086
    tree $use_color "$@"
  }
else
  FZF_DIR_PREVIEW() {
    local use_color
    use_color=$(test "$FZF_USE_COLOR" && printf -- "--color=always")
    # shellcheck disable=SC2086
    ls $use_color "$@"
  }
fi

FZF_FILE_PREVIEW() {
  local json
  # Attempt to prettify json before display
  # will return false if prettier isn't installed
  if json=$(prettier --parser json5 <"$1" 2>/dev/null); then
    printf '%s' "$json" | FZF_CAT_CMD_JSON
  else
    FZF_CAT_CMD "$1"
  fi
}

# Export the functions for subshell usage (IE, FZF)
export -f FZF_FIND_DIR FZF_FIND_FILE FZF_CAT_CMD FZF_CAT_CMD_JSON FZF_DIR_PREVIEW FZF_FILE_PREVIEW FZF_BASE_COMMAND

export FZF_DEFAULT_COMMAND="FZF_FIND_FILE ."

fp() (
  local output
  if [ "$1" = '--help' ]; then
    printf '%s\n' \
      'fp [--disable-color|-C] [PATH]' \
      '' \
      'find files in PATH to output the user'"'"'s choice' \
      'Opens editor if stdout is connected to a tty'
    return 0
  fi
  if [ "$1" = '--disable-color' ] || [ "$1" = '-C' ]; then
    unset FZF_USE_COLOR
    FZF_DEFAULT_OPTS=''
    shift 1
  fi
  # set the command to call with
  FZF_DEFAULT_COMMAND="FZF_FIND_FILE ${1:-.}"

  # Call with the path given, if applicable, and find all files
  output=$(
    fzf --preview "FZF_FILE_PREVIEW {} | head -n500" "${@:2}"
  ) || return
  if [[ -t 1 ]] && [[ -n "$output" ]]; then
    editor "$output"
  else
    printf '%s' "$output"
  fi
)

# For finding directories
fpd() (
  local output
  if [ "$1" = '--help' ]; then
    printf '%s\n' \
      'fpd [--disable-color|-C] [PATH]' \
      '' \
      'find directories in PATH to output the user'"'"'s choice' \
      'calls cd if stdout is connected to a tty'
    return 0
  fi
  if [ "$1" = '--disable-color' ] || [ "$1" = '-C' ]; then
    unset FZF_USE_COLOR
    FZF_DEFAULT_OPTS=''
    shift 1
  fi
  # set the command to call with
  FZF_DEFAULT_COMMAND="FZF_FIND_DIR ${1:-.}"

  # Call with the path given, if applicable, and find all directories
  output=$(
    fzf --preview "FZF_DIR_PREVIEW {} | head -n200" "${@:2}"
  ) || return
  if [[ -t 1 ]] && [[ -n "$output" ]]; then
    cd "$output" || return
  else
    printf '%s' "$output"
  fi
)
