#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/internet
#
# tests internet connection by pinging google.com
function internet() {
  ping -q -c 3 google.com
  local exit=$?
  if test $exit -eq 0; then
    printf '\n%s\n' "You have internet!"
  else
    printf '\n%s\n' "Your internet connection is not functional"
  fi
  return $exit
}
