#!/usr/bin/env bash
function new-java() {
  local classname fbn fdn date
  date=$(date '+%m/%d/%Y')
  for dir in "$@"; do
    dir=${dir%/} # strip trailing slash
    if [ -e "$dir" ] || [ -L "$dir" ]; then
      printf '%s\n' "file '$dir' already exists. Please move it or create a new name."
      return 1
    fi
    classname=$(basename "$dir")
    cp -T -ri ~/vscode/Java/template/ "$dir"
    for f in "$dir"/*; do
      fbn=$(basename "$f")
      fdn=$(dirname "$f")
      mv "$f" "$fdn/${fbn/ClassName/$classname}"
    done
    # okish since $classname and $date can't contain any slashes
    sed -i "s/ClassName/$classname/g" "$dir/$classname.java"
    sed -i "s/\$DATE/$date/g" "$dir/$classname.java"
  done
}
