#!/usr/bin/env bash
function new-java() {
  local classname fbn fdn date
  date=$(date '+%m/%d/%Y')
  for dir in "$@"; do
    dir=${dir%/} # strip trailing slash
    if [ -e "$dir" ] || [ -L "$dir" ]; then
      printf '%s\n' "file '$dir' already exists. Please move it or create a new name."
      return 1
    fi
    classname=$(basename "$dir")
    cp -T -ri ~/code/Java/template/ "$dir"
    for f in "$dir"/*; do
      fbn=$(basename "$f")
      fdn=$(dirname "$f")
      mv "$f" "$fdn/${fbn/ClassName/$classname}"
    done
    # okish since $classname can't contain any slashes
    sed -i "s/ClassName/$classname/g" "$dir/$classname.java"
    sed -i "s|\$DATE|$date|g" "$dir/$classname.java"
  done
}

function new() {
  local lang="${1:-}"
  local dest="${2:-new}"
  if [ -z "$lang" ]; then
    printf '%s\n' "usage: new <lang> [dest]" >&2
    return 2
  fi
  shift # remove lang from arguments
  if command -v "new-$lang" &>/dev/null; then
    "new-$lang" "$@"
    return
  fi

  local template_dir="$HOME/code/$lang/template"
  if ! [ -d "$template_dir" ]; then
    printf '%s\n' "Could not find $template_dir" >&2
    return 1
  fi
  cp -ri "$template_dir" "$dest"
}
