#! /usr/bin/env bash

# ~/.bashrc.d/30_functions/no-npm
#
# overrides `npm` with a function that
# echos a suggestion to use pnpm, then
# calls npm
#
function npm() {
  local RED='\033[0;31m'
  local NONE='\033[0m' # No Color
  local message="no-npm: ${RED}Perhaps you meant pnpm?${NONE}\n"
  local OUTPUT=""
  # Print to stderr if possible, else stdout if possible
  if [[ -t 2 ]]; then
    OUTPUT=/proc/self/fd/2
  elif [[ -t 1 ]]; then
    OUTPUT=/proc/self/fd/1
  fi

  if ! command -v pnpm || [ -z "$OUTPUT" ]; then
    command npm "$@"
    return
  fi

  printf "%b" "$message" >"$OUTPUT"
  # Defaults to no
  read -rep "Are you sure you want to use NPM? (y/N) " confirmation
  if [[ -n "$confirmation" && "${confirmation,,}" =~ ^\s*y(es)?\s*$ ]]; then
    command npm "$@"
  fi
}
