#! /usr/bin/env bash

# ~/.bashrc.d/30_functions/no-npm
#
# overrides `npm` with a function that
# echos a suggestion to use pnpm, then
# calls npm
#
function npm() {
  local RED='\033[0;31m' NONE='\033[0m' # No Color
  local output=""
  # Print to stderr if possible, else stdout if possible
  if [ -t 2 ]; then
    output=/proc/self/fd/2
  elif [ -t 1 ]; then
    output=/proc/self/fd/1
  fi

  if ! command -v pnpm >&/dev/null || [ -z "$output" ]; then
    command npm "$@"
    return
  fi

  printf "%b\n" "no-npm: ${RED}Perhaps you meant pnpm?${NONE}" >"$output"
  read -rep "Are you sure you want to use NPM? (Y/n) " confirmation # Defaults to yes
  [ -z "$confirmation" ] || [[ "${confirmation,,}" =~ ^\s*y(es)?\s*$ ]] || return 1
  command npm "$@"
}
