#!/usr/bin/env bash
function path() {
  local arg &&
    for arg; do
      [ "$arg" != --help ] || continue
      printf '%s\n' "usage: ${FUNCNAME[0]} PATH [sep]"
      return 0
    done
  local c="${2:-:}"
  c="${c:0:1}" # only first char
  tr "$c" "\n" <<<"$1"
}
