#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/post-temp
#
# Hosts a temporary file on the internet for 60 mins and returns the url.
#
#
function post-temp() {
  local this='post-temp'
  local verbose result status url message quiet

  local done='' args=() arg
  for arg; do
    # stop processing when hit --
    if [ "$done" = true ]; then args+=("$arg") && continue; fi
    case "$arg" in
    --help | -h)
      cat <<-EOF
			$this [-v|--verbose] FILE

			Hosts a temporary file on the internet for 60 mins and returns the url.
EOF
      return 0
      ;;
    -v | --verbose) verbose=true ;;                                            # Verbose option
    -q | --quiet) quiet=true ;;                                                # Quiet option
    --) done=true ;;                                                           # End of args. this is not one.
    -*) printf '%s\n' "$this: invalid option -- '${arg#-}'" >&2 && return 2 ;; # Invalid -flag
    *) args+=("$arg") ;;                                                       # Any other argument
    esac
  done

  local fx
  fx=$(which fx 2>/dev/null || printf '')
  if [ -z "$fx" ] && [ "$quiet" != "true" ]; then printf '%s\n' "$this: This script works much better with 'fx' installed." >&2; fi
  local RED="\e[1;41m"
  local BLANK="\e[0m"

  declare -i exitcode=0
  for file in "${args[@]}"; do
    if ! [[ -f "$file" ]]; then
      printf "%s\n" "'$file' is not a file" >&2
      exitcode=2 && continue
    fi

    result="$(curl -sSfL -F "file=@$file" https://tmpfiles.org/api/v1/upload)" || {
      printf '%s\n' 'Something went wrong during curl command. Aborting.' >&2
      return 1 # Exit function, not loop
    }
    # Example outputs:
    # {"message": "server error"}
    # {"status":"success","data":{"url":"https://tmpfiles.org/######/file"}}

    # If verbose, or fx not installed, print entire json
    if [ "$verbose" = true ] || [ -z "$fx" ]; then
      printf '%s\n' "$result"
      [ -z "$fx" ] && continue # Stops loop here because fx is not installed
    fi

    # Print the result thru fx to get the data
    # Already strings, if present, but trying to error
    status="$("$fx" '.status.toString()' <<<"$result" 2>/dev/null)"
    url="$("$fx" '.data.url.toString()' <<<"$result" 2>/dev/null)"

    if [ -z "$status" ] || [ -z "$url" ]; then
      message="$("$fx" '.message.toString()' <<<"$result" 2>/dev/null)"
      if [ -n "$message" ]; then
        printf "$RED%s$BLANK\n" "$message" >&2
      else
        printf '%s\n' "$this: An unknown error occured" >&2
      fi
    else
      [ "$verbose" != true ] && printf '%s\n' "$status"
      printf '%s\n' "${url/tmpfiles.org\//tmpfiles.org\/dl\/}"
    fi

  done
  return $exitcode
}
