#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/post-temp
#
# Hosts a temporary file on the internet for 60 mins and returns the url.
#
#
function post-temp() {
  local verbose result status url message

  for arg; do #if any arg is --help
    if [ "$arg" = "--help" ]; then
      printf '%s\n' "post-temp [-v|--verbose] FILE"
      printf '\n'
      printf '%s\n' "Hosts a temporary file on the internet for 60 mins and returns the url."
      return 0
    fi
  done

  if [ "$1" = -v ] || [ "$1" = --verbose ]; then verbose=true; fi
  function is_verbose() { test -n "$verbose"; }
  if is_verbose; then shift; fi # remove first arg if is --verbose

  file=$1
  if ! [[ -f "$file" ]]; then
    printf "The path given is not a file\n"
    return 2
  fi

  result="$(curl -F "file=@$file" https://tmpfiles.org/api/v1/upload)"
  # Example outputs:
  # {"message": "server error"}
  # {"status":"success","data":{"url":"https://tmpfiles.org/######/file"}}
  declare -i subshell_exit
  (
    if ! command -v 'fx' &>/dev/null; then return 1; fi

    # Print the result thru fx to get the data
    # Already strings, if present, but trying to error
    status="$(fx '.status.toString()' <<<"$result" 2>/dev/null)" &&
      url="$(fx '.data.url.toString()' <<<"$result" 2>/dev/null)" && {
      printf '%s\n' "$status" "$url"
      return 0 # returns from subshell
    }
    # On error: (should've returned already on success)
    RED="\e[1;41m"
    BLANK="\e[0m"
    message="$(fx '.message.toString()' <<<"$result" 2>/dev/null)" && {
      printf "$RED%s$BLANK\n" "$message" >&2
      return 1 # returns from subshell
    }
  )
  subshell_exit=$?
  # If verbose, or subshell failed (fx not installed or error returned), print entire json
  if is_verbose || [ $subshell_exit -ne 0 ]; then
    printf '%s\n' "$result"
  fi
}
