#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/private
#
# Unsets histfile and opens a shell
function private() {
  cmd=(bash -i)
  [ "$#" -gt 0 ] && cmd=("$@") # run the input
  HISTFILE='' "${cmd[@]}"
  # If is in history - could false positive, but better than false negative
  if history 1 | grep -q 'private'; then
    history -d "$HISTCMD"
  fi
}
alias private='private ' # expand aliases
function soh() {
  sudo -- env PATH="$PATH" bash -c 'cd ~/Documents/.soh/; exec bash -i'
}
