#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/private
#
# Unsets histfile and opens a shell
function private() {
  if [ "$#" -eq 0 ]; then
    HISTFILE='' bash -i
  else
    # run the input
    HISTFILE='' "$@"
  fi
  # If is in history - could false positive, but better than false negative
  if history 1 | grep -q 'private'; then
    history -d "$HISTCMD"
  fi
}
alias private='private ' # expand aliases
