#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/rge
#
# Sets up bde function for editing all results of rg

function rge() {
  local rg=(rg -l)
  if ! command -v rg &>/dev/null; then
    rg=(grep -r -l) # Closest to rg available
  fi
  "${rg[@]}" "$@" | xargs -- "${EDITOR:-editor}"
}
