#!/usr/bin/env bash

# Kills the shell!
function self-destruct() {
  for i in {30..1}; do
    printf "%s\n" "Self destructing in $i seconds"
    sleep 1
  done || return
  printf "%s\n" "BOOM!"
  sleep 1
  exit 0
}
