#!/usr/bin/env bash

# ~/.bashrc.d/30_functions/swap
#
# Swap two files

function swap() {
  if [ "$#" -ne 2 ]; then
    echo "Usage: swap <file> <file>" >&2
    return 2
  fi
  local tmp TMPDIR
  TMPDIR=$(dirname -- "$1")
  # Use TMPDIR to enable atomic moves (for the tmpfile)
  tmp=$(mktemp --tmpdir="$TMPDIR" "$(basename -- "$1")_XXXXXX")
  echo "Using $tmp as temporary file"
  if mv -f "$1" "$tmp" && mv "$2" "$1"; then
    mv "$tmp" "$2"
    rm -f "$tmp"
  else
    echo "Failed to swap $1 and $2" >&2
    mv -i "$tmp" "$1"
  fi
  return 0
}
