#!/usr/bin/env sh
# shellcheck disable=SC2034 # This file is sourced, there's lots of unused variables. It's fine.
# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'

# run this command to create a new grub font (-b means bold, else omit)
# sudo grub-mkfont -s <SIZE> -n '<NAME>' -b -o /boot/grub/themes/<THEME>/<NAME>_<SIZE>.pf2 <FONT_PATH>.ttf
# Example using Terminus Bold 32:
# sudo grub-mkfont -s 32 -n 'Terminus' -b -o /boot/grub/themes/argon/Terminus_32.pf2 /usr/share/fonts/truetype/terminus/TerminusTTF-4.46.0.ttf

# Set default to the last OS used
GRUB_DEFAULT="saved"
GRUB_SAVEDEFAULT="true"

# Make grub hidden, but wait 2 seconds for shift key
GRUB_TIMEOUT_STYLE="countdown"
GRUB_TIMEOUT=2

# Uncomment to display grub menu on startup
# GRUB_TIMEOUT_STYLE=menu
# GRUB_TIMEOUT=10

GRUB_DISTRIBUTOR="$(lsb_release -i -s 2>/dev/null || (. /etc/os-release && printf '%s\n' "$NAME") 2>/dev/null || echo 'Linux')"
# Prevent keyboard freeze on unsuspend
GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 i8042.reset atkbd.reset=1 i8042.dumbkbd i8042.direct fbcon=nodefer"
GRUB_CMDLINE_LINUX=""

# Uncomment to enable BadRAM filtering, modify to suit your needs
# This works with Linux (no patch required) and with any kernel that obtains
# the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
#GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

# Uncomment to disable graphical terminal (grub-pc only)
#GRUB_TERMINAL="console"

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `vbeinfo'
#GRUB_GFXMODE="640x480"
GRUB_GFXMODE="1366x768x32;1024x768x32;auto"

# Attempt to preserve the grub resolution into linux boot
GRUB_GFXPAYLOAD_LINUX=keep

# Use a PNG or 8-bit JPG file for grub background image
GRUB_BACKGROUND=""
GRUB_THEME="/boot/grub/themes/argon/theme.txt"

# Set menu coloring
GRUB_COLOR_NORMAL=white/black
GRUB_COLOR_HIGHLIGHT=black/light-gray

# Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
#GRUB_DISABLE_LINUX_UUID="true"

# Uncomment to disable generation of recovery mode menu entries
#GRUB_DISABLE_RECOVERY="true"

# Uncomment to get a beep at grub start
#GRUB_INIT_TUNE="480 440 1"
GRUB_DISABLE_OS_PROBER="false"
# vim:ft=sh:
