#!/usr/bin/env bash
set -euC -o pipefail
function err() { printf '%s\n' "$@" >&2; }
function abort() { err "$1" && exit "${2:-1}"; }
this_dir=
if [ -f "$0" ]; then
  this_dir=$(dirname -- "$0")
fi
if ! [ -d "$this_dir" ]; then
  abort "Could not find directory of this script." 2
fi
DEST=$(dirname -- "$this_dir")

install_deps() {                                                 # {{{ 1
  if [ -f "$DEST/build/.has_installed_deps" ]; then return 0; fi # already did it :)
  if ! [ -d "$this_dir" ]; then err "Couldn't find script dir" && return 1; fi

  names=(deps packages pkgs) exts=('-apt' '-APT' '') pkg_file=
  for f in "${names[@]}"; do
    for ext in "${exts[@]}"; do
      if [ -f "$this_dir/$f$ext" ]; then pkg_file="$this_dir/$f$ext" && break; fi
    done
  done

  if ! [ -f "$pkg_file" ]; then err "couldn't find a list of packages in script dir" && return 1; fi

  # shellcheck disable=SC2206
  sudo=() && if [ "$(id -u)" -ne 0 ]; then sudo=(${SUDO:-sudo}); fi

  xargs -d$'\n' -r -a "$pkg_file" -- "${sudo[@]}" apt install --mark-auto
  touch "$DEST/build/.has_installed_deps"
} # }}}
install_deps

export LUA_DIR=/usr/include/lua5.3/
export CPATH="$LUA_DIR"
export LUA_PATH='/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;;'
export LUA_CPATH='/usr/lib/x86_64-linux-gnu/lua/5.3/?.so;;'

cd "$DEST"
make CMAKE_ARGS="-DGENERATE_DOC:BOOLEAN=OFF -DAWESOME_DATA_PATH=$DEST/build/" "$@"
