#!/usr/bin/env bash
set -euC -o pipefail
function err() { printf '%s\n' "$@" >&2; }
function abort() { err "$1" && exit "${2:-1}"; }
function has() { command -v "$1" &>/dev/null; }
# shellcheck disable=SC2206
sudo=() && if [ "$(id -u)" -ne 0 ]; then sudo=(${SUDO:-sudo}); fi

this_dir=$(dirname -- "$0") || abort "Could not find current script filepath"
[ -d "$this_dir" ] || abort "Could not find directory of this script."

DEST=$(dirname -- "$this_dir")

if has pacman; then exec "$this_dir/arch/makepkg.sh" "$DEST"; fi

install_deps() {
  if [ -f "$DEST/build/.has_installed_deps" ]; then return 0; fi # already did it :)
  if ! [ -d "$this_dir" ]; then err "Couldn't find script dir" && return 1; fi

  pkg_manager=
  pkg_manager_exec=()
  if has nala; then
    pkg_manager=apt pkg_manager_exec=("${sudo[@]}" nala install)
  elif has apt; then
    pkg_manager=apt pkg_manager_exec=("${sudo[@]}" apt install --mark-auto)
  fi
  [ -n "$pkg_manager" ] || { err "Couldn't find suitable package manager" && return 1; }

  pkg_file="deps.$pkg_manager"
  [ -f "$pkg_file" ] || { err "Couldn't find a list of package to install" && return 1; }

  xargs -d$'\n' -r -a "$pkg_file" -- "${pkg_manager_exec[@]}"
  mkdir -p "$DEST/build"
  touch "$DEST/build/.has_installed_deps"
}
install_deps || { err "Warning: could not install dependencies. Continuing will likely fail!" && sleep 2; }

export LUA_DIR=/usr/include/lua5.3/
export CPATH="$LUA_DIR"
export LUA_PATH='/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;;'
export LUA_CPATH='/usr/lib/x86_64-linux-gnu/lua/5.3/?.so;;'

cd "$DEST"
make CMAKE_ARGS="-DGENERATE_DOC:BOOLEAN=OFF -DAWESOME_DATA_PATH=$DEST/build/ -DGENERATE_MANPAGES:BOOLEAN=OFF" "$@"
