# ------------------------------------------------------------------------------
# /etc/tlp.conf - TLP user configuration (version 1.4)
# See full explanation: https://linrunner.de/tlp/settings
#
# Settings are read in the following order:
#
# 1. Intrinsic defaults
# 2. /etc/tlp.d/*.conf - Drop-in customization snippets
# 3. /etc/tlp.conf     - User configuration (this file)
#
# Notes:
# - In case of identical parameters, the last occurence has precedence
# - This also means, parameters enabled here will override anything else
# - However you may append values to a parameter already defined as intrinsic
#   default or in a previously read file: use PARAMETER+="add values"
# ------------------------------------------------------------------------------

# Restore radio device state from previous shutdown on system startup
RESTORE_DEVICE_STATE_ON_STARTUP=1

# Battery Care -- Charge thresholds
# Charging starts when the charge level is below the START_CHARGE_THRESH value
# when the charger is connected. It stops when the STOP_CHARGE_THRESH value is reached.

# BAT0: Primary / Main / Internal battery (values in %)
START_CHARGE_THRESH_BAT0=90
STOP_CHARGE_THRESH_BAT0=95

# Restore charge thresholds when AC is unplugged
RESTORE_THRESHOLDS_ON_BAT=1
