Section "InputClass"
        Identifier "Keyboards"
        MatchIsKeyboard "on"
        # Set caps lock to control!
        Option "XkbOptions" "ctrl:nocaps"
        # Set left windows to meta, no multikey
        Option "XkbOptions" "altwin:left_meta_win"
EndSection
