Section "Device"
   Identifier  "Intel Graphics"
   Driver      "modesetting"
   # Driver      "intel"
# The modesetting driver doesn't *yet* support TearFree on Ubuntu
# This can be remedied using a compositor (picom), but if needed,
# the `intel` driver can be used instead, until it's supported
# on modesetting.
   Option      "TearFree"  "true"
EndSection
