#!/usr/bin/env bash
_cpumode() {
  COMPREPLY=()
  local cur
  # Pointer to current completion word.
  # By convention, it's named "cur" but this isn't strictly necessary.

  cur=${COMP_WORDS[COMP_CWORD]}

  # shellcheck disable=SC2207
  case "$cur" in
  -*) COMPREPLY=($(compgen -W '--help' -- "$cur")) ;;
  *)
    modes="$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors)"
    COMPREPLY=($(compgen -W "$modes" -- "$cur"))
    ;;
  esac

  return 0

}
complete -o bashdefault -F _cpumode cpumode
