#!/usr/bin/env bash
# vim:set ft=sh ts=2 sw=2 sts=2 et nospell:
# shellcheck disable=SC2207
_todo() {
  local _cmd=$1 cur=$2 _pre=$3
  local todo_dir="${XDG_DATA_HOME:-~/.local/share}/todo"
  COMPREPLY=()

  case "$cur" in
  -*) COMPREPLY=($(compgen -W "$(todo --handle-completion-options)" -- "$cur")) && return 0 ;;
  esac

  # todo <action> (complete)
  if [ "$COMP_CWORD" -eq 1 ]; then # complete the actions
    COMPREPLY=($(compgen -W "$(todo --handle-completion-actions)" -- "$cur"))
    return 0
  fi
  # shellcheck disable=SC2207
  local arr=($(cd "$todo_dir" && compgen -f -- "$cur")) # complete the todos
  local file && for file in "${arr[@]}"; do
    case "$file" in
    .*) continue ;; esac # Skip dotfiles
    ! [ -d "$todo_dir/$file" ] || file+=/
    COMPREPLY+=("$file")
  done
}
complete -o bashdefault -F _todo todo
